// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file_transfer_storage_grpc.proto

package com.lanjiu.pro.fileStorage;

/**
 * <pre>
 * 语音
 * </pre>
 *
 * Protobuf type {@code com.lanjiu.pro.fileStorage.Voice}
 */
public  final class Voice extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.lanjiu.pro.fileStorage.Voice)
    VoiceOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Voice.newBuilder() to construct.
  private Voice(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Voice() {
    allLength_ = "";
    content_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Voice();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Voice(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            allLength_ = s;
            break;
          }
          case 18: {

            content_ = input.readBytes();
            break;
          }
          case 24: {

            pos_ = input.readInt32();
            break;
          }
          case 32: {

            length_ = input.readInt32();
            break;
          }
          case 42: {
            com.lanjiu.pro.fileStorage.Friends.Builder subBuilder = null;
            if (friends_ != null) {
              subBuilder = friends_.toBuilder();
            }
            friends_ = input.readMessage(com.lanjiu.pro.fileStorage.Friends.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(friends_);
              friends_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            com.lanjiu.pro.fileStorage.GroupMember.Builder subBuilder = null;
            if (groupMember_ != null) {
              subBuilder = groupMember_.toBuilder();
            }
            groupMember_ = input.readMessage(com.lanjiu.pro.fileStorage.GroupMember.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(groupMember_);
              groupMember_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.lanjiu.pro.fileStorage.FileStorageProto.internal_static_com_lanjiu_pro_fileStorage_Voice_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.lanjiu.pro.fileStorage.FileStorageProto.internal_static_com_lanjiu_pro_fileStorage_Voice_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.lanjiu.pro.fileStorage.Voice.class, com.lanjiu.pro.fileStorage.Voice.Builder.class);
  }

  public static final int ALL_LENGTH_FIELD_NUMBER = 1;
  private volatile java.lang.Object allLength_;
  /**
   * <pre>
   * 文本长度
   * </pre>
   *
   * <code>string all_length = 1;</code>
   * @return The allLength.
   */
  public java.lang.String getAllLength() {
    java.lang.Object ref = allLength_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      allLength_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 文本长度
   * </pre>
   *
   * <code>string all_length = 1;</code>
   * @return The bytes for allLength.
   */
  public com.google.protobuf.ByteString
      getAllLengthBytes() {
    java.lang.Object ref = allLength_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      allLength_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTENT_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString content_;
  /**
   * <pre>
   * 文本内容
   * </pre>
   *
   * <code>bytes content = 2;</code>
   * @return The content.
   */
  public com.google.protobuf.ByteString getContent() {
    return content_;
  }

  public static final int POS_FIELD_NUMBER = 3;
  private int pos_;
  /**
   * <pre>
   *当前坐标
   * </pre>
   *
   * <code>int32 pos = 3;</code>
   * @return The pos.
   */
  public int getPos() {
    return pos_;
  }

  public static final int LENGTH_FIELD_NUMBER = 4;
  private int length_;
  /**
   * <pre>
   *当前文件内容大小
   * </pre>
   *
   * <code>int32 length = 4;</code>
   * @return The length.
   */
  public int getLength() {
    return length_;
  }

  public static final int FRIENDS_FIELD_NUMBER = 5;
  private com.lanjiu.pro.fileStorage.Friends friends_;
  /**
   * <pre>
   *好友结构体
   * </pre>
   *
   * <code>.com.lanjiu.pro.fileStorage.Friends friends = 5;</code>
   * @return Whether the friends field is set.
   */
  public boolean hasFriends() {
    return friends_ != null;
  }
  /**
   * <pre>
   *好友结构体
   * </pre>
   *
   * <code>.com.lanjiu.pro.fileStorage.Friends friends = 5;</code>
   * @return The friends.
   */
  public com.lanjiu.pro.fileStorage.Friends getFriends() {
    return friends_ == null ? com.lanjiu.pro.fileStorage.Friends.getDefaultInstance() : friends_;
  }
  /**
   * <pre>
   *好友结构体
   * </pre>
   *
   * <code>.com.lanjiu.pro.fileStorage.Friends friends = 5;</code>
   */
  public com.lanjiu.pro.fileStorage.FriendsOrBuilder getFriendsOrBuilder() {
    return getFriends();
  }

  public static final int GROUPMEMBER_FIELD_NUMBER = 6;
  private com.lanjiu.pro.fileStorage.GroupMember groupMember_;
  /**
   * <code>.com.lanjiu.pro.fileStorage.GroupMember groupMember = 6;</code>
   * @return Whether the groupMember field is set.
   */
  public boolean hasGroupMember() {
    return groupMember_ != null;
  }
  /**
   * <code>.com.lanjiu.pro.fileStorage.GroupMember groupMember = 6;</code>
   * @return The groupMember.
   */
  public com.lanjiu.pro.fileStorage.GroupMember getGroupMember() {
    return groupMember_ == null ? com.lanjiu.pro.fileStorage.GroupMember.getDefaultInstance() : groupMember_;
  }
  /**
   * <code>.com.lanjiu.pro.fileStorage.GroupMember groupMember = 6;</code>
   */
  public com.lanjiu.pro.fileStorage.GroupMemberOrBuilder getGroupMemberOrBuilder() {
    return getGroupMember();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAllLengthBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, allLength_);
    }
    if (!content_.isEmpty()) {
      output.writeBytes(2, content_);
    }
    if (pos_ != 0) {
      output.writeInt32(3, pos_);
    }
    if (length_ != 0) {
      output.writeInt32(4, length_);
    }
    if (friends_ != null) {
      output.writeMessage(5, getFriends());
    }
    if (groupMember_ != null) {
      output.writeMessage(6, getGroupMember());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAllLengthBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, allLength_);
    }
    if (!content_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, content_);
    }
    if (pos_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, pos_);
    }
    if (length_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, length_);
    }
    if (friends_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getFriends());
    }
    if (groupMember_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getGroupMember());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.lanjiu.pro.fileStorage.Voice)) {
      return super.equals(obj);
    }
    com.lanjiu.pro.fileStorage.Voice other = (com.lanjiu.pro.fileStorage.Voice) obj;

    if (!getAllLength()
        .equals(other.getAllLength())) return false;
    if (!getContent()
        .equals(other.getContent())) return false;
    if (getPos()
        != other.getPos()) return false;
    if (getLength()
        != other.getLength()) return false;
    if (hasFriends() != other.hasFriends()) return false;
    if (hasFriends()) {
      if (!getFriends()
          .equals(other.getFriends())) return false;
    }
    if (hasGroupMember() != other.hasGroupMember()) return false;
    if (hasGroupMember()) {
      if (!getGroupMember()
          .equals(other.getGroupMember())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ALL_LENGTH_FIELD_NUMBER;
    hash = (53 * hash) + getAllLength().hashCode();
    hash = (37 * hash) + CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getContent().hashCode();
    hash = (37 * hash) + POS_FIELD_NUMBER;
    hash = (53 * hash) + getPos();
    hash = (37 * hash) + LENGTH_FIELD_NUMBER;
    hash = (53 * hash) + getLength();
    if (hasFriends()) {
      hash = (37 * hash) + FRIENDS_FIELD_NUMBER;
      hash = (53 * hash) + getFriends().hashCode();
    }
    if (hasGroupMember()) {
      hash = (37 * hash) + GROUPMEMBER_FIELD_NUMBER;
      hash = (53 * hash) + getGroupMember().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.lanjiu.pro.fileStorage.Voice parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lanjiu.pro.fileStorage.Voice parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lanjiu.pro.fileStorage.Voice parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lanjiu.pro.fileStorage.Voice parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lanjiu.pro.fileStorage.Voice parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lanjiu.pro.fileStorage.Voice parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lanjiu.pro.fileStorage.Voice parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lanjiu.pro.fileStorage.Voice parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lanjiu.pro.fileStorage.Voice parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.lanjiu.pro.fileStorage.Voice parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lanjiu.pro.fileStorage.Voice parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lanjiu.pro.fileStorage.Voice parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.lanjiu.pro.fileStorage.Voice prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 语音
   * </pre>
   *
   * Protobuf type {@code com.lanjiu.pro.fileStorage.Voice}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.lanjiu.pro.fileStorage.Voice)
      com.lanjiu.pro.fileStorage.VoiceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lanjiu.pro.fileStorage.FileStorageProto.internal_static_com_lanjiu_pro_fileStorage_Voice_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lanjiu.pro.fileStorage.FileStorageProto.internal_static_com_lanjiu_pro_fileStorage_Voice_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lanjiu.pro.fileStorage.Voice.class, com.lanjiu.pro.fileStorage.Voice.Builder.class);
    }

    // Construct using com.lanjiu.pro.fileStorage.Voice.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      allLength_ = "";

      content_ = com.google.protobuf.ByteString.EMPTY;

      pos_ = 0;

      length_ = 0;

      if (friendsBuilder_ == null) {
        friends_ = null;
      } else {
        friends_ = null;
        friendsBuilder_ = null;
      }
      if (groupMemberBuilder_ == null) {
        groupMember_ = null;
      } else {
        groupMember_ = null;
        groupMemberBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.lanjiu.pro.fileStorage.FileStorageProto.internal_static_com_lanjiu_pro_fileStorage_Voice_descriptor;
    }

    @java.lang.Override
    public com.lanjiu.pro.fileStorage.Voice getDefaultInstanceForType() {
      return com.lanjiu.pro.fileStorage.Voice.getDefaultInstance();
    }

    @java.lang.Override
    public com.lanjiu.pro.fileStorage.Voice build() {
      com.lanjiu.pro.fileStorage.Voice result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.lanjiu.pro.fileStorage.Voice buildPartial() {
      com.lanjiu.pro.fileStorage.Voice result = new com.lanjiu.pro.fileStorage.Voice(this);
      result.allLength_ = allLength_;
      result.content_ = content_;
      result.pos_ = pos_;
      result.length_ = length_;
      if (friendsBuilder_ == null) {
        result.friends_ = friends_;
      } else {
        result.friends_ = friendsBuilder_.build();
      }
      if (groupMemberBuilder_ == null) {
        result.groupMember_ = groupMember_;
      } else {
        result.groupMember_ = groupMemberBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.lanjiu.pro.fileStorage.Voice) {
        return mergeFrom((com.lanjiu.pro.fileStorage.Voice)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.lanjiu.pro.fileStorage.Voice other) {
      if (other == com.lanjiu.pro.fileStorage.Voice.getDefaultInstance()) return this;
      if (!other.getAllLength().isEmpty()) {
        allLength_ = other.allLength_;
        onChanged();
      }
      if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
        setContent(other.getContent());
      }
      if (other.getPos() != 0) {
        setPos(other.getPos());
      }
      if (other.getLength() != 0) {
        setLength(other.getLength());
      }
      if (other.hasFriends()) {
        mergeFriends(other.getFriends());
      }
      if (other.hasGroupMember()) {
        mergeGroupMember(other.getGroupMember());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.lanjiu.pro.fileStorage.Voice parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.lanjiu.pro.fileStorage.Voice) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object allLength_ = "";
    /**
     * <pre>
     * 文本长度
     * </pre>
     *
     * <code>string all_length = 1;</code>
     * @return The allLength.
     */
    public java.lang.String getAllLength() {
      java.lang.Object ref = allLength_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        allLength_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 文本长度
     * </pre>
     *
     * <code>string all_length = 1;</code>
     * @return The bytes for allLength.
     */
    public com.google.protobuf.ByteString
        getAllLengthBytes() {
      java.lang.Object ref = allLength_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        allLength_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 文本长度
     * </pre>
     *
     * <code>string all_length = 1;</code>
     * @param value The allLength to set.
     * @return This builder for chaining.
     */
    public Builder setAllLength(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      allLength_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 文本长度
     * </pre>
     *
     * <code>string all_length = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAllLength() {
      
      allLength_ = getDefaultInstance().getAllLength();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 文本长度
     * </pre>
     *
     * <code>string all_length = 1;</code>
     * @param value The bytes for allLength to set.
     * @return This builder for chaining.
     */
    public Builder setAllLengthBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      allLength_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * 文本内容
     * </pre>
     *
     * <code>bytes content = 2;</code>
     * @return The content.
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }
    /**
     * <pre>
     * 文本内容
     * </pre>
     *
     * <code>bytes content = 2;</code>
     * @param value The content to set.
     * @return This builder for chaining.
     */
    public Builder setContent(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      content_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 文本内容
     * </pre>
     *
     * <code>bytes content = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearContent() {
      
      content_ = getDefaultInstance().getContent();
      onChanged();
      return this;
    }

    private int pos_ ;
    /**
     * <pre>
     *当前坐标
     * </pre>
     *
     * <code>int32 pos = 3;</code>
     * @return The pos.
     */
    public int getPos() {
      return pos_;
    }
    /**
     * <pre>
     *当前坐标
     * </pre>
     *
     * <code>int32 pos = 3;</code>
     * @param value The pos to set.
     * @return This builder for chaining.
     */
    public Builder setPos(int value) {
      
      pos_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *当前坐标
     * </pre>
     *
     * <code>int32 pos = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPos() {
      
      pos_ = 0;
      onChanged();
      return this;
    }

    private int length_ ;
    /**
     * <pre>
     *当前文件内容大小
     * </pre>
     *
     * <code>int32 length = 4;</code>
     * @return The length.
     */
    public int getLength() {
      return length_;
    }
    /**
     * <pre>
     *当前文件内容大小
     * </pre>
     *
     * <code>int32 length = 4;</code>
     * @param value The length to set.
     * @return This builder for chaining.
     */
    public Builder setLength(int value) {
      
      length_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *当前文件内容大小
     * </pre>
     *
     * <code>int32 length = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLength() {
      
      length_ = 0;
      onChanged();
      return this;
    }

    private com.lanjiu.pro.fileStorage.Friends friends_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.lanjiu.pro.fileStorage.Friends, com.lanjiu.pro.fileStorage.Friends.Builder, com.lanjiu.pro.fileStorage.FriendsOrBuilder> friendsBuilder_;
    /**
     * <pre>
     *好友结构体
     * </pre>
     *
     * <code>.com.lanjiu.pro.fileStorage.Friends friends = 5;</code>
     * @return Whether the friends field is set.
     */
    public boolean hasFriends() {
      return friendsBuilder_ != null || friends_ != null;
    }
    /**
     * <pre>
     *好友结构体
     * </pre>
     *
     * <code>.com.lanjiu.pro.fileStorage.Friends friends = 5;</code>
     * @return The friends.
     */
    public com.lanjiu.pro.fileStorage.Friends getFriends() {
      if (friendsBuilder_ == null) {
        return friends_ == null ? com.lanjiu.pro.fileStorage.Friends.getDefaultInstance() : friends_;
      } else {
        return friendsBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *好友结构体
     * </pre>
     *
     * <code>.com.lanjiu.pro.fileStorage.Friends friends = 5;</code>
     */
    public Builder setFriends(com.lanjiu.pro.fileStorage.Friends value) {
      if (friendsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        friends_ = value;
        onChanged();
      } else {
        friendsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *好友结构体
     * </pre>
     *
     * <code>.com.lanjiu.pro.fileStorage.Friends friends = 5;</code>
     */
    public Builder setFriends(
        com.lanjiu.pro.fileStorage.Friends.Builder builderForValue) {
      if (friendsBuilder_ == null) {
        friends_ = builderForValue.build();
        onChanged();
      } else {
        friendsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *好友结构体
     * </pre>
     *
     * <code>.com.lanjiu.pro.fileStorage.Friends friends = 5;</code>
     */
    public Builder mergeFriends(com.lanjiu.pro.fileStorage.Friends value) {
      if (friendsBuilder_ == null) {
        if (friends_ != null) {
          friends_ =
            com.lanjiu.pro.fileStorage.Friends.newBuilder(friends_).mergeFrom(value).buildPartial();
        } else {
          friends_ = value;
        }
        onChanged();
      } else {
        friendsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *好友结构体
     * </pre>
     *
     * <code>.com.lanjiu.pro.fileStorage.Friends friends = 5;</code>
     */
    public Builder clearFriends() {
      if (friendsBuilder_ == null) {
        friends_ = null;
        onChanged();
      } else {
        friends_ = null;
        friendsBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *好友结构体
     * </pre>
     *
     * <code>.com.lanjiu.pro.fileStorage.Friends friends = 5;</code>
     */
    public com.lanjiu.pro.fileStorage.Friends.Builder getFriendsBuilder() {
      
      onChanged();
      return getFriendsFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *好友结构体
     * </pre>
     *
     * <code>.com.lanjiu.pro.fileStorage.Friends friends = 5;</code>
     */
    public com.lanjiu.pro.fileStorage.FriendsOrBuilder getFriendsOrBuilder() {
      if (friendsBuilder_ != null) {
        return friendsBuilder_.getMessageOrBuilder();
      } else {
        return friends_ == null ?
            com.lanjiu.pro.fileStorage.Friends.getDefaultInstance() : friends_;
      }
    }
    /**
     * <pre>
     *好友结构体
     * </pre>
     *
     * <code>.com.lanjiu.pro.fileStorage.Friends friends = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.lanjiu.pro.fileStorage.Friends, com.lanjiu.pro.fileStorage.Friends.Builder, com.lanjiu.pro.fileStorage.FriendsOrBuilder> 
        getFriendsFieldBuilder() {
      if (friendsBuilder_ == null) {
        friendsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.lanjiu.pro.fileStorage.Friends, com.lanjiu.pro.fileStorage.Friends.Builder, com.lanjiu.pro.fileStorage.FriendsOrBuilder>(
                getFriends(),
                getParentForChildren(),
                isClean());
        friends_ = null;
      }
      return friendsBuilder_;
    }

    private com.lanjiu.pro.fileStorage.GroupMember groupMember_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.lanjiu.pro.fileStorage.GroupMember, com.lanjiu.pro.fileStorage.GroupMember.Builder, com.lanjiu.pro.fileStorage.GroupMemberOrBuilder> groupMemberBuilder_;
    /**
     * <code>.com.lanjiu.pro.fileStorage.GroupMember groupMember = 6;</code>
     * @return Whether the groupMember field is set.
     */
    public boolean hasGroupMember() {
      return groupMemberBuilder_ != null || groupMember_ != null;
    }
    /**
     * <code>.com.lanjiu.pro.fileStorage.GroupMember groupMember = 6;</code>
     * @return The groupMember.
     */
    public com.lanjiu.pro.fileStorage.GroupMember getGroupMember() {
      if (groupMemberBuilder_ == null) {
        return groupMember_ == null ? com.lanjiu.pro.fileStorage.GroupMember.getDefaultInstance() : groupMember_;
      } else {
        return groupMemberBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.lanjiu.pro.fileStorage.GroupMember groupMember = 6;</code>
     */
    public Builder setGroupMember(com.lanjiu.pro.fileStorage.GroupMember value) {
      if (groupMemberBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        groupMember_ = value;
        onChanged();
      } else {
        groupMemberBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.lanjiu.pro.fileStorage.GroupMember groupMember = 6;</code>
     */
    public Builder setGroupMember(
        com.lanjiu.pro.fileStorage.GroupMember.Builder builderForValue) {
      if (groupMemberBuilder_ == null) {
        groupMember_ = builderForValue.build();
        onChanged();
      } else {
        groupMemberBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.lanjiu.pro.fileStorage.GroupMember groupMember = 6;</code>
     */
    public Builder mergeGroupMember(com.lanjiu.pro.fileStorage.GroupMember value) {
      if (groupMemberBuilder_ == null) {
        if (groupMember_ != null) {
          groupMember_ =
            com.lanjiu.pro.fileStorage.GroupMember.newBuilder(groupMember_).mergeFrom(value).buildPartial();
        } else {
          groupMember_ = value;
        }
        onChanged();
      } else {
        groupMemberBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.lanjiu.pro.fileStorage.GroupMember groupMember = 6;</code>
     */
    public Builder clearGroupMember() {
      if (groupMemberBuilder_ == null) {
        groupMember_ = null;
        onChanged();
      } else {
        groupMember_ = null;
        groupMemberBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.lanjiu.pro.fileStorage.GroupMember groupMember = 6;</code>
     */
    public com.lanjiu.pro.fileStorage.GroupMember.Builder getGroupMemberBuilder() {
      
      onChanged();
      return getGroupMemberFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.lanjiu.pro.fileStorage.GroupMember groupMember = 6;</code>
     */
    public com.lanjiu.pro.fileStorage.GroupMemberOrBuilder getGroupMemberOrBuilder() {
      if (groupMemberBuilder_ != null) {
        return groupMemberBuilder_.getMessageOrBuilder();
      } else {
        return groupMember_ == null ?
            com.lanjiu.pro.fileStorage.GroupMember.getDefaultInstance() : groupMember_;
      }
    }
    /**
     * <code>.com.lanjiu.pro.fileStorage.GroupMember groupMember = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.lanjiu.pro.fileStorage.GroupMember, com.lanjiu.pro.fileStorage.GroupMember.Builder, com.lanjiu.pro.fileStorage.GroupMemberOrBuilder> 
        getGroupMemberFieldBuilder() {
      if (groupMemberBuilder_ == null) {
        groupMemberBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.lanjiu.pro.fileStorage.GroupMember, com.lanjiu.pro.fileStorage.GroupMember.Builder, com.lanjiu.pro.fileStorage.GroupMemberOrBuilder>(
                getGroupMember(),
                getParentForChildren(),
                isClean());
        groupMember_ = null;
      }
      return groupMemberBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.lanjiu.pro.fileStorage.Voice)
  }

  // @@protoc_insertion_point(class_scope:com.lanjiu.pro.fileStorage.Voice)
  private static final com.lanjiu.pro.fileStorage.Voice DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.lanjiu.pro.fileStorage.Voice();
  }

  public static com.lanjiu.pro.fileStorage.Voice getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Voice>
      PARSER = new com.google.protobuf.AbstractParser<Voice>() {
    @java.lang.Override
    public Voice parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Voice(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Voice> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Voice> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.lanjiu.pro.fileStorage.Voice getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

