// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login_regist_storage.proto

package com.lanjiu.im.storage;

/**
 * Protobuf type {@code com.lanjiu.im.storage.UserInfomation}
 */
public  final class UserInfomation extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.lanjiu.im.storage.UserInfomation)
    UserInfomationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UserInfomation.newBuilder() to construct.
  private UserInfomation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserInfomation() {
    userType_ = "";
    userId_ = "";
    nickname_ = "";
    avatar_ = "";
    modifyTime_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UserInfomation();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UserInfomation(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            userType_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            userId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            nickname_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            avatar_ = s;
            break;
          }
          case 40: {

            offMsgSetting_ = input.readBool();
            break;
          }
          case 48: {

            onlineStatus_ = input.readBool();
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            modifyTime_ = s;
            break;
          }
          case 64: {

            burnAfterReadingSetting_ = input.readBool();
            break;
          }
          case 72: {

            burnAfterReadingTimeUnit_ = input.readInt32();
            break;
          }
          case 80: {

            burnAfterReadingTimeLength_ = input.readInt32();
            break;
          }
          case 88: {

            exitClean_ = input.readBool();
            break;
          }
          case 96: {

            timerClean_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.lanjiu.im.storage.RegisterStorageProto.internal_static_com_lanjiu_im_storage_UserInfomation_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.lanjiu.im.storage.RegisterStorageProto.internal_static_com_lanjiu_im_storage_UserInfomation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.lanjiu.im.storage.UserInfomation.class, com.lanjiu.im.storage.UserInfomation.Builder.class);
  }

  public static final int USER_TYPE_FIELD_NUMBER = 1;
  private volatile java.lang.Object userType_;
  /**
   * <code>string user_type = 1;</code>
   * @return The userType.
   */
  public java.lang.String getUserType() {
    java.lang.Object ref = userType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userType_ = s;
      return s;
    }
  }
  /**
   * <code>string user_type = 1;</code>
   * @return The bytes for userType.
   */
  public com.google.protobuf.ByteString
      getUserTypeBytes() {
    java.lang.Object ref = userType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USER_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object userId_;
  /**
   * <code>string user_id = 2;</code>
   * @return The userId.
   */
  public java.lang.String getUserId() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userId_ = s;
      return s;
    }
  }
  /**
   * <code>string user_id = 2;</code>
   * @return The bytes for userId.
   */
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NICKNAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object nickname_;
  /**
   * <code>string nickname = 3;</code>
   * @return The nickname.
   */
  public java.lang.String getNickname() {
    java.lang.Object ref = nickname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nickname_ = s;
      return s;
    }
  }
  /**
   * <code>string nickname = 3;</code>
   * @return The bytes for nickname.
   */
  public com.google.protobuf.ByteString
      getNicknameBytes() {
    java.lang.Object ref = nickname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nickname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AVATAR_FIELD_NUMBER = 4;
  private volatile java.lang.Object avatar_;
  /**
   * <code>string avatar = 4;</code>
   * @return The avatar.
   */
  public java.lang.String getAvatar() {
    java.lang.Object ref = avatar_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      avatar_ = s;
      return s;
    }
  }
  /**
   * <code>string avatar = 4;</code>
   * @return The bytes for avatar.
   */
  public com.google.protobuf.ByteString
      getAvatarBytes() {
    java.lang.Object ref = avatar_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      avatar_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OFF_MSG_SETTING_FIELD_NUMBER = 5;
  private boolean offMsgSetting_;
  /**
   * <code>bool off_msg_setting = 5;</code>
   * @return The offMsgSetting.
   */
  public boolean getOffMsgSetting() {
    return offMsgSetting_;
  }

  public static final int ONLINE_STATUS_FIELD_NUMBER = 6;
  private boolean onlineStatus_;
  /**
   * <code>bool online_status = 6;</code>
   * @return The onlineStatus.
   */
  public boolean getOnlineStatus() {
    return onlineStatus_;
  }

  public static final int MODIFY_TIME_FIELD_NUMBER = 7;
  private volatile java.lang.Object modifyTime_;
  /**
   * <code>string modify_time = 7;</code>
   * @return The modifyTime.
   */
  public java.lang.String getModifyTime() {
    java.lang.Object ref = modifyTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      modifyTime_ = s;
      return s;
    }
  }
  /**
   * <code>string modify_time = 7;</code>
   * @return The bytes for modifyTime.
   */
  public com.google.protobuf.ByteString
      getModifyTimeBytes() {
    java.lang.Object ref = modifyTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      modifyTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BURN_AFTER_READING_SETTING_FIELD_NUMBER = 8;
  private boolean burnAfterReadingSetting_;
  /**
   * <code>bool burn_after_reading_setting = 8;</code>
   * @return The burnAfterReadingSetting.
   */
  public boolean getBurnAfterReadingSetting() {
    return burnAfterReadingSetting_;
  }

  public static final int BURN_AFTER_READING_TIME_UNIT_FIELD_NUMBER = 9;
  private int burnAfterReadingTimeUnit_;
  /**
   * <code>int32 burn_after_reading_time_unit = 9;</code>
   * @return The burnAfterReadingTimeUnit.
   */
  public int getBurnAfterReadingTimeUnit() {
    return burnAfterReadingTimeUnit_;
  }

  public static final int BURN_AFTER_READING_TIME_LENGTH_FIELD_NUMBER = 10;
  private int burnAfterReadingTimeLength_;
  /**
   * <code>int32 burn_after_reading_time_length = 10;</code>
   * @return The burnAfterReadingTimeLength.
   */
  public int getBurnAfterReadingTimeLength() {
    return burnAfterReadingTimeLength_;
  }

  public static final int EXIT_CLEAN_FIELD_NUMBER = 11;
  private boolean exitClean_;
  /**
   * <pre>
   * 是否开启退出清理
   * </pre>
   *
   * <code>bool exit_clean = 11;</code>
   * @return The exitClean.
   */
  public boolean getExitClean() {
    return exitClean_;
  }

  public static final int TIMER_CLEAN_FIELD_NUMBER = 12;
  private int timerClean_;
  /**
   * <pre>
   * 定期清理（0:每月，1:每周，2:每天）
   * </pre>
   *
   * <code>int32 timer_clean = 12;</code>
   * @return The timerClean.
   */
  public int getTimerClean() {
    return timerClean_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getUserTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userType_);
    }
    if (!getUserIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userId_);
    }
    if (!getNicknameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, nickname_);
    }
    if (!getAvatarBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, avatar_);
    }
    if (offMsgSetting_ != false) {
      output.writeBool(5, offMsgSetting_);
    }
    if (onlineStatus_ != false) {
      output.writeBool(6, onlineStatus_);
    }
    if (!getModifyTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, modifyTime_);
    }
    if (burnAfterReadingSetting_ != false) {
      output.writeBool(8, burnAfterReadingSetting_);
    }
    if (burnAfterReadingTimeUnit_ != 0) {
      output.writeInt32(9, burnAfterReadingTimeUnit_);
    }
    if (burnAfterReadingTimeLength_ != 0) {
      output.writeInt32(10, burnAfterReadingTimeLength_);
    }
    if (exitClean_ != false) {
      output.writeBool(11, exitClean_);
    }
    if (timerClean_ != 0) {
      output.writeInt32(12, timerClean_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getUserTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userType_);
    }
    if (!getUserIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userId_);
    }
    if (!getNicknameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, nickname_);
    }
    if (!getAvatarBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, avatar_);
    }
    if (offMsgSetting_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, offMsgSetting_);
    }
    if (onlineStatus_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, onlineStatus_);
    }
    if (!getModifyTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, modifyTime_);
    }
    if (burnAfterReadingSetting_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, burnAfterReadingSetting_);
    }
    if (burnAfterReadingTimeUnit_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, burnAfterReadingTimeUnit_);
    }
    if (burnAfterReadingTimeLength_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, burnAfterReadingTimeLength_);
    }
    if (exitClean_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(11, exitClean_);
    }
    if (timerClean_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(12, timerClean_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.lanjiu.im.storage.UserInfomation)) {
      return super.equals(obj);
    }
    com.lanjiu.im.storage.UserInfomation other = (com.lanjiu.im.storage.UserInfomation) obj;

    if (!getUserType()
        .equals(other.getUserType())) return false;
    if (!getUserId()
        .equals(other.getUserId())) return false;
    if (!getNickname()
        .equals(other.getNickname())) return false;
    if (!getAvatar()
        .equals(other.getAvatar())) return false;
    if (getOffMsgSetting()
        != other.getOffMsgSetting()) return false;
    if (getOnlineStatus()
        != other.getOnlineStatus()) return false;
    if (!getModifyTime()
        .equals(other.getModifyTime())) return false;
    if (getBurnAfterReadingSetting()
        != other.getBurnAfterReadingSetting()) return false;
    if (getBurnAfterReadingTimeUnit()
        != other.getBurnAfterReadingTimeUnit()) return false;
    if (getBurnAfterReadingTimeLength()
        != other.getBurnAfterReadingTimeLength()) return false;
    if (getExitClean()
        != other.getExitClean()) return false;
    if (getTimerClean()
        != other.getTimerClean()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USER_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getUserType().hashCode();
    hash = (37 * hash) + USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId().hashCode();
    hash = (37 * hash) + NICKNAME_FIELD_NUMBER;
    hash = (53 * hash) + getNickname().hashCode();
    hash = (37 * hash) + AVATAR_FIELD_NUMBER;
    hash = (53 * hash) + getAvatar().hashCode();
    hash = (37 * hash) + OFF_MSG_SETTING_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getOffMsgSetting());
    hash = (37 * hash) + ONLINE_STATUS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getOnlineStatus());
    hash = (37 * hash) + MODIFY_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getModifyTime().hashCode();
    hash = (37 * hash) + BURN_AFTER_READING_SETTING_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getBurnAfterReadingSetting());
    hash = (37 * hash) + BURN_AFTER_READING_TIME_UNIT_FIELD_NUMBER;
    hash = (53 * hash) + getBurnAfterReadingTimeUnit();
    hash = (37 * hash) + BURN_AFTER_READING_TIME_LENGTH_FIELD_NUMBER;
    hash = (53 * hash) + getBurnAfterReadingTimeLength();
    hash = (37 * hash) + EXIT_CLEAN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getExitClean());
    hash = (37 * hash) + TIMER_CLEAN_FIELD_NUMBER;
    hash = (53 * hash) + getTimerClean();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.lanjiu.im.storage.UserInfomation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lanjiu.im.storage.UserInfomation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lanjiu.im.storage.UserInfomation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lanjiu.im.storage.UserInfomation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lanjiu.im.storage.UserInfomation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lanjiu.im.storage.UserInfomation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lanjiu.im.storage.UserInfomation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lanjiu.im.storage.UserInfomation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lanjiu.im.storage.UserInfomation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.lanjiu.im.storage.UserInfomation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lanjiu.im.storage.UserInfomation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lanjiu.im.storage.UserInfomation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.lanjiu.im.storage.UserInfomation prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.lanjiu.im.storage.UserInfomation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.lanjiu.im.storage.UserInfomation)
      com.lanjiu.im.storage.UserInfomationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lanjiu.im.storage.RegisterStorageProto.internal_static_com_lanjiu_im_storage_UserInfomation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lanjiu.im.storage.RegisterStorageProto.internal_static_com_lanjiu_im_storage_UserInfomation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lanjiu.im.storage.UserInfomation.class, com.lanjiu.im.storage.UserInfomation.Builder.class);
    }

    // Construct using com.lanjiu.im.storage.UserInfomation.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      userType_ = "";

      userId_ = "";

      nickname_ = "";

      avatar_ = "";

      offMsgSetting_ = false;

      onlineStatus_ = false;

      modifyTime_ = "";

      burnAfterReadingSetting_ = false;

      burnAfterReadingTimeUnit_ = 0;

      burnAfterReadingTimeLength_ = 0;

      exitClean_ = false;

      timerClean_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.lanjiu.im.storage.RegisterStorageProto.internal_static_com_lanjiu_im_storage_UserInfomation_descriptor;
    }

    @java.lang.Override
    public com.lanjiu.im.storage.UserInfomation getDefaultInstanceForType() {
      return com.lanjiu.im.storage.UserInfomation.getDefaultInstance();
    }

    @java.lang.Override
    public com.lanjiu.im.storage.UserInfomation build() {
      com.lanjiu.im.storage.UserInfomation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.lanjiu.im.storage.UserInfomation buildPartial() {
      com.lanjiu.im.storage.UserInfomation result = new com.lanjiu.im.storage.UserInfomation(this);
      result.userType_ = userType_;
      result.userId_ = userId_;
      result.nickname_ = nickname_;
      result.avatar_ = avatar_;
      result.offMsgSetting_ = offMsgSetting_;
      result.onlineStatus_ = onlineStatus_;
      result.modifyTime_ = modifyTime_;
      result.burnAfterReadingSetting_ = burnAfterReadingSetting_;
      result.burnAfterReadingTimeUnit_ = burnAfterReadingTimeUnit_;
      result.burnAfterReadingTimeLength_ = burnAfterReadingTimeLength_;
      result.exitClean_ = exitClean_;
      result.timerClean_ = timerClean_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.lanjiu.im.storage.UserInfomation) {
        return mergeFrom((com.lanjiu.im.storage.UserInfomation)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.lanjiu.im.storage.UserInfomation other) {
      if (other == com.lanjiu.im.storage.UserInfomation.getDefaultInstance()) return this;
      if (!other.getUserType().isEmpty()) {
        userType_ = other.userType_;
        onChanged();
      }
      if (!other.getUserId().isEmpty()) {
        userId_ = other.userId_;
        onChanged();
      }
      if (!other.getNickname().isEmpty()) {
        nickname_ = other.nickname_;
        onChanged();
      }
      if (!other.getAvatar().isEmpty()) {
        avatar_ = other.avatar_;
        onChanged();
      }
      if (other.getOffMsgSetting() != false) {
        setOffMsgSetting(other.getOffMsgSetting());
      }
      if (other.getOnlineStatus() != false) {
        setOnlineStatus(other.getOnlineStatus());
      }
      if (!other.getModifyTime().isEmpty()) {
        modifyTime_ = other.modifyTime_;
        onChanged();
      }
      if (other.getBurnAfterReadingSetting() != false) {
        setBurnAfterReadingSetting(other.getBurnAfterReadingSetting());
      }
      if (other.getBurnAfterReadingTimeUnit() != 0) {
        setBurnAfterReadingTimeUnit(other.getBurnAfterReadingTimeUnit());
      }
      if (other.getBurnAfterReadingTimeLength() != 0) {
        setBurnAfterReadingTimeLength(other.getBurnAfterReadingTimeLength());
      }
      if (other.getExitClean() != false) {
        setExitClean(other.getExitClean());
      }
      if (other.getTimerClean() != 0) {
        setTimerClean(other.getTimerClean());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.lanjiu.im.storage.UserInfomation parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.lanjiu.im.storage.UserInfomation) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object userType_ = "";
    /**
     * <code>string user_type = 1;</code>
     * @return The userType.
     */
    public java.lang.String getUserType() {
      java.lang.Object ref = userType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string user_type = 1;</code>
     * @return The bytes for userType.
     */
    public com.google.protobuf.ByteString
        getUserTypeBytes() {
      java.lang.Object ref = userType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string user_type = 1;</code>
     * @param value The userType to set.
     * @return This builder for chaining.
     */
    public Builder setUserType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string user_type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserType() {
      
      userType_ = getDefaultInstance().getUserType();
      onChanged();
      return this;
    }
    /**
     * <code>string user_type = 1;</code>
     * @param value The bytes for userType to set.
     * @return This builder for chaining.
     */
    public Builder setUserTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object userId_ = "";
    /**
     * <code>string user_id = 2;</code>
     * @return The userId.
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string user_id = 2;</code>
     * @return The bytes for userId.
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string user_id = 2;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string user_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      
      userId_ = getDefaultInstance().getUserId();
      onChanged();
      return this;
    }
    /**
     * <code>string user_id = 2;</code>
     * @param value The bytes for userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object nickname_ = "";
    /**
     * <code>string nickname = 3;</code>
     * @return The nickname.
     */
    public java.lang.String getNickname() {
      java.lang.Object ref = nickname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nickname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string nickname = 3;</code>
     * @return The bytes for nickname.
     */
    public com.google.protobuf.ByteString
        getNicknameBytes() {
      java.lang.Object ref = nickname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string nickname = 3;</code>
     * @param value The nickname to set.
     * @return This builder for chaining.
     */
    public Builder setNickname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nickname_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string nickname = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNickname() {
      
      nickname_ = getDefaultInstance().getNickname();
      onChanged();
      return this;
    }
    /**
     * <code>string nickname = 3;</code>
     * @param value The bytes for nickname to set.
     * @return This builder for chaining.
     */
    public Builder setNicknameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nickname_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object avatar_ = "";
    /**
     * <code>string avatar = 4;</code>
     * @return The avatar.
     */
    public java.lang.String getAvatar() {
      java.lang.Object ref = avatar_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        avatar_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string avatar = 4;</code>
     * @return The bytes for avatar.
     */
    public com.google.protobuf.ByteString
        getAvatarBytes() {
      java.lang.Object ref = avatar_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        avatar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string avatar = 4;</code>
     * @param value The avatar to set.
     * @return This builder for chaining.
     */
    public Builder setAvatar(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      avatar_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string avatar = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAvatar() {
      
      avatar_ = getDefaultInstance().getAvatar();
      onChanged();
      return this;
    }
    /**
     * <code>string avatar = 4;</code>
     * @param value The bytes for avatar to set.
     * @return This builder for chaining.
     */
    public Builder setAvatarBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      avatar_ = value;
      onChanged();
      return this;
    }

    private boolean offMsgSetting_ ;
    /**
     * <code>bool off_msg_setting = 5;</code>
     * @return The offMsgSetting.
     */
    public boolean getOffMsgSetting() {
      return offMsgSetting_;
    }
    /**
     * <code>bool off_msg_setting = 5;</code>
     * @param value The offMsgSetting to set.
     * @return This builder for chaining.
     */
    public Builder setOffMsgSetting(boolean value) {
      
      offMsgSetting_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool off_msg_setting = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearOffMsgSetting() {
      
      offMsgSetting_ = false;
      onChanged();
      return this;
    }

    private boolean onlineStatus_ ;
    /**
     * <code>bool online_status = 6;</code>
     * @return The onlineStatus.
     */
    public boolean getOnlineStatus() {
      return onlineStatus_;
    }
    /**
     * <code>bool online_status = 6;</code>
     * @param value The onlineStatus to set.
     * @return This builder for chaining.
     */
    public Builder setOnlineStatus(boolean value) {
      
      onlineStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool online_status = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearOnlineStatus() {
      
      onlineStatus_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object modifyTime_ = "";
    /**
     * <code>string modify_time = 7;</code>
     * @return The modifyTime.
     */
    public java.lang.String getModifyTime() {
      java.lang.Object ref = modifyTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        modifyTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string modify_time = 7;</code>
     * @return The bytes for modifyTime.
     */
    public com.google.protobuf.ByteString
        getModifyTimeBytes() {
      java.lang.Object ref = modifyTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        modifyTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string modify_time = 7;</code>
     * @param value The modifyTime to set.
     * @return This builder for chaining.
     */
    public Builder setModifyTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      modifyTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string modify_time = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearModifyTime() {
      
      modifyTime_ = getDefaultInstance().getModifyTime();
      onChanged();
      return this;
    }
    /**
     * <code>string modify_time = 7;</code>
     * @param value The bytes for modifyTime to set.
     * @return This builder for chaining.
     */
    public Builder setModifyTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      modifyTime_ = value;
      onChanged();
      return this;
    }

    private boolean burnAfterReadingSetting_ ;
    /**
     * <code>bool burn_after_reading_setting = 8;</code>
     * @return The burnAfterReadingSetting.
     */
    public boolean getBurnAfterReadingSetting() {
      return burnAfterReadingSetting_;
    }
    /**
     * <code>bool burn_after_reading_setting = 8;</code>
     * @param value The burnAfterReadingSetting to set.
     * @return This builder for chaining.
     */
    public Builder setBurnAfterReadingSetting(boolean value) {
      
      burnAfterReadingSetting_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool burn_after_reading_setting = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearBurnAfterReadingSetting() {
      
      burnAfterReadingSetting_ = false;
      onChanged();
      return this;
    }

    private int burnAfterReadingTimeUnit_ ;
    /**
     * <code>int32 burn_after_reading_time_unit = 9;</code>
     * @return The burnAfterReadingTimeUnit.
     */
    public int getBurnAfterReadingTimeUnit() {
      return burnAfterReadingTimeUnit_;
    }
    /**
     * <code>int32 burn_after_reading_time_unit = 9;</code>
     * @param value The burnAfterReadingTimeUnit to set.
     * @return This builder for chaining.
     */
    public Builder setBurnAfterReadingTimeUnit(int value) {
      
      burnAfterReadingTimeUnit_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 burn_after_reading_time_unit = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearBurnAfterReadingTimeUnit() {
      
      burnAfterReadingTimeUnit_ = 0;
      onChanged();
      return this;
    }

    private int burnAfterReadingTimeLength_ ;
    /**
     * <code>int32 burn_after_reading_time_length = 10;</code>
     * @return The burnAfterReadingTimeLength.
     */
    public int getBurnAfterReadingTimeLength() {
      return burnAfterReadingTimeLength_;
    }
    /**
     * <code>int32 burn_after_reading_time_length = 10;</code>
     * @param value The burnAfterReadingTimeLength to set.
     * @return This builder for chaining.
     */
    public Builder setBurnAfterReadingTimeLength(int value) {
      
      burnAfterReadingTimeLength_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 burn_after_reading_time_length = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearBurnAfterReadingTimeLength() {
      
      burnAfterReadingTimeLength_ = 0;
      onChanged();
      return this;
    }

    private boolean exitClean_ ;
    /**
     * <pre>
     * 是否开启退出清理
     * </pre>
     *
     * <code>bool exit_clean = 11;</code>
     * @return The exitClean.
     */
    public boolean getExitClean() {
      return exitClean_;
    }
    /**
     * <pre>
     * 是否开启退出清理
     * </pre>
     *
     * <code>bool exit_clean = 11;</code>
     * @param value The exitClean to set.
     * @return This builder for chaining.
     */
    public Builder setExitClean(boolean value) {
      
      exitClean_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否开启退出清理
     * </pre>
     *
     * <code>bool exit_clean = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearExitClean() {
      
      exitClean_ = false;
      onChanged();
      return this;
    }

    private int timerClean_ ;
    /**
     * <pre>
     * 定期清理（0:每月，1:每周，2:每天）
     * </pre>
     *
     * <code>int32 timer_clean = 12;</code>
     * @return The timerClean.
     */
    public int getTimerClean() {
      return timerClean_;
    }
    /**
     * <pre>
     * 定期清理（0:每月，1:每周，2:每天）
     * </pre>
     *
     * <code>int32 timer_clean = 12;</code>
     * @param value The timerClean to set.
     * @return This builder for chaining.
     */
    public Builder setTimerClean(int value) {
      
      timerClean_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 定期清理（0:每月，1:每周，2:每天）
     * </pre>
     *
     * <code>int32 timer_clean = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimerClean() {
      
      timerClean_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.lanjiu.im.storage.UserInfomation)
  }

  // @@protoc_insertion_point(class_scope:com.lanjiu.im.storage.UserInfomation)
  private static final com.lanjiu.im.storage.UserInfomation DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.lanjiu.im.storage.UserInfomation();
  }

  public static com.lanjiu.im.storage.UserInfomation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserInfomation>
      PARSER = new com.google.protobuf.AbstractParser<UserInfomation>() {
    @java.lang.Override
    public UserInfomation parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UserInfomation(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UserInfomation> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserInfomation> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.lanjiu.im.storage.UserInfomation getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

