// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: information_other_storage_grpc.proto

package com.lanjiu.im.grpc;

public final class InformationStorageProto {
  private InformationStorageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_TransmissionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_TransmissionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_BeautifulNumberCommonResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_BeautifulNumberCommonResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_BurnAfterReadingPriorityResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_BurnAfterReadingPriorityResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_GroupAnnouncementsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_GroupAnnouncementsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_GuestGroupResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_GuestGroupResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_GuestGroupAdministratorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_GuestGroupAdministratorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_GuestGroupGuestUserMemberRelationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_GuestGroupGuestUserMemberRelationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_GuestGroupMemberResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_GuestGroupMemberResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_GuestGroupRegisteredUserMemberRelationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_GuestGroupRegisteredUserMemberRelationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_GuestUserFriendResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_GuestUserFriendResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_OfflineMessagePriorityResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_OfflineMessagePriorityResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_RegisteredGroupResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_RegisteredGroupResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_RegisteredGroupAdministratorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_RegisteredGroupAdministratorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_RegisteredGroupGuestUserMemberRelationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_RegisteredGroupGuestUserMemberRelationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_RegisteredGroupMemberResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_RegisteredGroupMemberResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_RegisteredGroupRegisteredUserMemberRelationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_RegisteredGroupRegisteredUserMemberRelationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_RegisteredUserFriendResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_RegisteredUserFriendResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_GroupRemarkResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_GroupRemarkResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_GroupMemberNicknameResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_GroupMemberNicknameResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_RpcBeautifulNumberCommon_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_RpcBeautifulNumberCommon_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_RpcBurnAfterReadingPriority_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_RpcBurnAfterReadingPriority_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_RpcGroupAnnouncements_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_RpcGroupAnnouncements_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_RpcGuestGroup_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_RpcGuestGroup_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_RpcGuestGroupAdministrator_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_RpcGuestGroupAdministrator_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_RpcGuestGroupGuestUserMemberRelation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_RpcGuestGroupGuestUserMemberRelation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_RpcGuestGroupMember_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_RpcGuestGroupMember_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_RpcGuestGroupRegisteredUserMemberRelation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_RpcGuestGroupRegisteredUserMemberRelation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_RpcGuestUserFriend_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_RpcGuestUserFriend_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_RpcOfflineMessagePriority_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_RpcOfflineMessagePriority_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_RpcRegisteredGroup_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_RpcRegisteredGroup_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_RpcRegisteredGroupAdministrator_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_RpcRegisteredGroupAdministrator_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_RpcRegisteredGroupGuestUserMemberRelation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_RpcRegisteredGroupGuestUserMemberRelation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_RpcRegisteredGroupMember_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_RpcRegisteredGroupMember_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_RpcRegisteredGroupRegisteredUserMemberRelation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_RpcRegisteredGroupRegisteredUserMemberRelation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_RpcRegisteredUserFriend_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_RpcRegisteredUserFriend_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_RpcGroupRemark_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_RpcGroupRemark_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_AllGroupMemberVO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_AllGroupMemberVO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_AllGroupsMemberResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_AllGroupsMemberResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_SelectGroupMemberRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_SelectGroupMemberRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_RpcGroupMemberNickname_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_RpcGroupMemberNickname_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$information_other_storage_grpc.proto\022\022" +
      "com.lanjiu.im.grpc\"\350\013\n\023TransmissionReque" +
      "st\022M\n\027beautiful_number_common\030\001 \001(\0132,.co" +
      "m.lanjiu.im.grpc.RpcBeautifulNumberCommo" +
      "n\022T\n\033burn_after_reading_priority\030\002 \001(\0132/" +
      ".com.lanjiu.im.grpc.RpcBurnAfterReadingP" +
      "riority\022F\n\023group_announcements\030\003 \001(\0132).c" +
      "om.lanjiu.im.grpc.RpcGroupAnnouncements\022" +
      "6\n\013guest_group\030\004 \001(\0132!.com.lanjiu.im.grp" +
      "c.RpcGuestGroup\022Q\n\031guest_group_administr" +
      "ator\030\005 \001(\0132..com.lanjiu.im.grpc.RpcGuest" +
      "GroupAdministrator\022a\n\037guest_group_guest_" +
      "user_relation\030\006 \001(\01328.com.lanjiu.im.grpc" +
      ".RpcGuestGroupGuestUserMemberRelation\022C\n" +
      "\022guest_group_member\030\007 \001(\0132\'.com.lanjiu.i" +
      "m.grpc.RpcGuestGroupMember\022k\n$guest_grou" +
      "p_registered_user_relation\030\010 \001(\0132=.com.l" +
      "anjiu.im.grpc.RpcGuestGroupRegisteredUse" +
      "rMemberRelation\022A\n\021guest_user_friend\030\t \001" +
      "(\0132&.com.lanjiu.im.grpc.RpcGuestUserFrie" +
      "nd\022O\n\030offline_message_priority\030\n \001(\0132-.c" +
      "om.lanjiu.im.grpc.RpcOfflineMessagePrior" +
      "ity\022@\n\020registered_group\030\013 \001(\0132&.com.lanj" +
      "iu.im.grpc.RpcRegisteredGroup\022[\n\036registe" +
      "red_group_administrator\030\014 \001(\01323.com.lanj" +
      "iu.im.grpc.RpcRegisteredGroupAdministrat" +
      "or\022k\n$registered_group_guest_user_relati" +
      "on\030\r \001(\0132=.com.lanjiu.im.grpc.RpcRegiste" +
      "redGroupGuestUserMemberRelation\022M\n\027regis" +
      "tered_group_member\030\016 \001(\0132,.com.lanjiu.im" +
      ".grpc.RpcRegisteredGroupMember\022u\n)regist" +
      "ered_group_registered_user_relation\030\017 \001(" +
      "\0132B.com.lanjiu.im.grpc.RpcRegisteredGrou" +
      "pRegisteredUserMemberRelation\022K\n\026registe" +
      "red_user_friend\030\020 \001(\0132+.com.lanjiu.im.gr" +
      "pc.RpcRegisteredUserFriend\0228\n\014group_rema" +
      "rk\030\021 \001(\0132\".com.lanjiu.im.grpc.RpcGroupRe" +
      "mark\022\024\n\014request_kind\030\022 \001(\t\022A\n\023all_group_" +
      "member_vo\030\023 \001(\0132$.com.lanjiu.im.grpc.All" +
      "GroupMemberVO\"{\n\035BeautifulNumberCommonRe" +
      "sponse\022\025\n\rstatus_detail\030\001 \001(\t\022C\n\rrespons" +
      "e_data\030\002 \003(\0132,.com.lanjiu.im.grpc.RpcBea" +
      "utifulNumberCommon\"\201\001\n BurnAfterReadingP" +
      "riorityResponse\022\025\n\rstatus_detail\030\001 \001(\t\022F" +
      "\n\rresponse_data\030\002 \003(\0132/.com.lanjiu.im.gr" +
      "pc.RpcBurnAfterReadingPriority\"u\n\032GroupA" +
      "nnouncementsResponse\022\025\n\rstatus_detail\030\001 " +
      "\001(\t\022@\n\rresponse_data\030\002 \003(\0132).com.lanjiu." +
      "im.grpc.RpcGroupAnnouncements\"\245\003\n\022GuestG" +
      "roupResponse\022\025\n\rstatus_detail\030\001 \001(\t\022?\n\024r" +
      "esponse_guest_group\030\002 \003(\0132!.com.lanjiu.i" +
      "m.grpc.RpcGuestGroup\022I\n\031response_registe" +
      "red_group\030\003 \003(\0132&.com.lanjiu.im.grpc.Rpc" +
      "RegisteredGroup\022L\n\033response_guest_group_" +
      "member\030\004 \003(\0132\'.com.lanjiu.im.grpc.RpcGue" +
      "stGroupMember\022V\n response_registered_gro" +
      "up_member\030\005 \003(\0132,.com.lanjiu.im.grpc.Rpc" +
      "RegisteredGroupMember\022F\n\030response_group_" +
      "member_vo\030\006 \003(\0132$.com.lanjiu.im.grpc.All" +
      "GroupMemberVO\"\177\n\037GuestGroupAdministrator" +
      "Response\022\025\n\rstatus_detail\030\001 \001(\t\022E\n\rrespo" +
      "nse_data\030\002 \003(\0132..com.lanjiu.im.grpc.RpcG" +
      "uestGroupAdministrator\"\223\001\n)GuestGroupGue" +
      "stUserMemberRelationResponse\022\025\n\rstatus_d" +
      "etail\030\001 \001(\t\022O\n\rresponse_data\030\002 \003(\01328.com" +
      ".lanjiu.im.grpc.RpcGuestGroupGuestUserMe" +
      "mberRelation\"\365\001\n\030GuestGroupMemberRespons" +
      "e\022\025\n\rstatus_detail\030\001 \001(\t\022>\n\rresponse_dat" +
      "a\030\002 \003(\0132\'.com.lanjiu.im.grpc.RpcGuestGro" +
      "upMember\022E\n\025registered_group_data\030\003 \003(\0132" +
      "&.com.lanjiu.im.grpc.RpcRegisteredGroup\022" +
      ";\n\020guest_group_data\030\004 \003(\0132!.com.lanjiu.i" +
      "m.grpc.RpcGuestGroup\"\235\001\n.GuestGroupRegis" +
      "teredUserMemberRelationResponse\022\025\n\rstatu" +
      "s_detail\030\001 \001(\t\022T\n\rresponse_data\030\002 \003(\0132=." +
      "com.lanjiu.im.grpc.RpcGuestGroupRegister" +
      "edUserMemberRelation\"o\n\027GuestUserFriendR" +
      "esponse\022\025\n\rstatus_detail\030\001 \001(\t\022=\n\rrespon" +
      "se_data\030\002 \003(\0132&.com.lanjiu.im.grpc.RpcGu" +
      "estUserFriend\"}\n\036OfflineMessagePriorityR" +
      "esponse\022\025\n\rstatus_detail\030\001 \001(\t\022D\n\rrespon" +
      "se_data\030\002 \003(\0132-.com.lanjiu.im.grpc.RpcOf" +
      "flineMessagePriority\"\252\003\n\027RegisteredGroup" +
      "Response\022\025\n\rstatus_detail\030\001 \001(\t\022I\n\031respo" +
      "nse_registered_group\030\002 \003(\0132&.com.lanjiu." +
      "im.grpc.RpcRegisteredGroup\022?\n\024response_g" +
      "uest_group\030\003 \003(\0132!.com.lanjiu.im.grpc.Rp" +
      "cGuestGroup\022V\n response_registered_group" +
      "_member\030\004 \003(\0132,.com.lanjiu.im.grpc.RpcRe" +
      "gisteredGroupMember\022L\n\033response_guest_gr" +
      "oup_member\030\005 \003(\0132\'.com.lanjiu.im.grpc.Rp" +
      "cGuestGroupMember\022F\n\030response_group_memb" +
      "er_vo\030\006 \003(\0132$.com.lanjiu.im.grpc.AllGrou" +
      "pMemberVO\"\211\001\n$RegisteredGroupAdministrat" +
      "orResponse\022\025\n\rstatus_detail\030\001 \001(\t\022J\n\rres" +
      "ponse_data\030\002 \003(\01323.com.lanjiu.im.grpc.Rp" +
      "cRegisteredGroupAdministrator\"\235\001\n.Regist" +
      "eredGroupGuestUserMemberRelationResponse" +
      "\022\025\n\rstatus_detail\030\001 \001(\t\022T\n\rresponse_data" +
      "\030\002 \003(\0132=.com.lanjiu.im.grpc.RpcRegistere" +
      "dGroupGuestUserMemberRelation\"\377\001\n\035Regist" +
      "eredGroupMemberResponse\022\025\n\rstatus_detail" +
      "\030\001 \001(\t\022C\n\rresponse_data\030\002 \003(\0132,.com.lanj" +
      "iu.im.grpc.RpcRegisteredGroupMember\022E\n\025r" +
      "egistered_group_data\030\003 \003(\0132&.com.lanjiu." +
      "im.grpc.RpcRegisteredGroup\022;\n\020guest_grou" +
      "p_data\030\004 \003(\0132!.com.lanjiu.im.grpc.RpcGue" +
      "stGroup\"\247\001\n3RegisteredGroupRegisteredUse" +
      "rMemberRelationResponse\022\025\n\rstatus_detail" +
      "\030\001 \001(\t\022Y\n\rresponse_data\030\002 \003(\0132B.com.lanj" +
      "iu.im.grpc.RpcRegisteredGroupRegisteredU" +
      "serMemberRelation\"y\n\034RegisteredUserFrien" +
      "dResponse\022\025\n\rstatus_detail\030\001 \001(\t\022B\n\rresp" +
      "onse_data\030\002 \003(\0132+.com.lanjiu.im.grpc.Rpc" +
      "RegisteredUserFriend\"g\n\023GroupRemarkRespo" +
      "nse\022\025\n\rstatus_detail\030\001 \001(\t\0229\n\rresponse_d" +
      "ata\030\002 \003(\0132\".com.lanjiu.im.grpc.RpcGroupR" +
      "emark\"w\n\033GroupMemberNicknameResponse\022\025\n\r" +
      "status_detail\030\001 \001(\t\022A\n\rresponse_data\030\002 \003" +
      "(\0132*.com.lanjiu.im.grpc.RpcGroupMemberNi" +
      "ckname\"\275\001\n\030RpcBeautifulNumberCommon\022\023\n\013t" +
      "en_million\030\001 \001(\005\022\023\n\013one_million\030\002 \001(\005\022\034\n" +
      "\024one_hundred_thousand\030\003 \001(\005\022\024\n\014ten_thous" +
      "and\030\004 \001(\005\022\024\n\014one_thousand\030\005 \001(\005\022\023\n\013one_h" +
      "undred\030\006 \001(\005\022\013\n\003ten\030\007 \001(\005\022\013\n\003one\030\010 \001(\005\"=" +
      "\n\033RpcBurnAfterReadingPriority\022\014\n\004type\030\001 " +
      "\001(\t\022\020\n\010priority\030\002 \001(\t\"p\n\025RpcGroupAnnounc" +
      "ements\022\035\n\025group_announcement_id\030\001 \001(\005\022\032\n" +
      "\022announcement_title\030\002 \001(\t\022\034\n\024announcemen" +
      "t_content\030\003 \001(\t\"\306\001\n\rRpcGuestGroup\022\025\n\rgue" +
      "st_user_id\030\001 \001(\005\022\020\n\010group_id\030\002 \001(\005\022\022\n\ngr" +
      "oup_name\030\003 \001(\t\022\035\n\025group_announcement_id\030" +
      "\004 \001(\005\022\025\n\rcreation_time\030\005 \001(\003\022\031\n\021modifica" +
      "tion_time\030\006 \001(\003\022\016\n\006amount\030\007 \001(\005\022\027\n\017group" +
      "_member_id\030\010 \001(\005\"n\n\032RpcGuestGroupAdminis" +
      "trator\022\030\n\020administrator_id\030\001 \001(\005\022\032\n\022admi" +
      "nistrator_type\030\002 \001(\t\022\032\n\022administrator_na" +
      "me\030\003 \001(\t\"\\\n$RpcGuestGroupGuestUserMember" +
      "Relation\022\026\n\016guest_group_id\030\001 \001(\005\022\034\n\024gues" +
      "t_user_member_id\030\002 \001(\005\"\261\002\n\023RpcGuestGroup" +
      "Member\022\027\n\017group_member_id\030\001 \001(\005\022\025\n\rguest" +
      "_user_id\030\002 \001(\005\022\025\n\rgroup_remarks\030\003 \001(\t\022\023\n" +
      "\013group_owner\030\004 \001(\t\022#\n\033burn_after_reading" +
      "_settings\030\005 \001(\t\022$\n\034burn_after_reading_ti" +
      "me_unit\030\006 \001(\t\022&\n\036burn_after_reading_time" +
      "_length\030\007 \001(\002\022\030\n\020group_entry_time\030\010 \001(\003\022" +
      "\037\n\027offline_message_setting\030\t \001(\t\022\020\n\010grou" +
      "p_id\030\n \001(\005\"f\n)RpcGuestGroupRegisteredUse" +
      "rMemberRelation\022\026\n\016guest_group_id\030\001 \001(\005\022" +
      "!\n\031registered_user_member_id\030\002 \001(\005\"\315\002\n\022R" +
      "pcGuestUserFriend\022\025\n\rguest_user_id\030\001 \001(\005" +
      "\022\021\n\tfriend_id\030\002 \001(\005\022\026\n\016friend_user_id\030\003 " +
      "\001(\005\022\026\n\016friend_comment\030\004 \001(\t\022\025\n\rcreation_" +
      "time\030\005 \001(\003\022\031\n\021modification_time\030\006 \001(\003\022\037\n" +
      "\027offline_message_setting\030\007 \001(\t\022\"\n\032burn_a" +
      "fter_reading_setting\030\010 \001(\t\022$\n\034burn_after" +
      "_reading_time_unit\030\t \001(\t\022&\n\036burn_after_r" +
      "eading_time_length\030\n \001(\002\022\030\n\020friend_nick_" +
      "name\030\013 \001(\t\";\n\031RpcOfflineMessagePriority\022" +
      "\014\n\004type\030\001 \001(\t\022\020\n\010priority\030\002 \001(\t\"\320\001\n\022RpcR" +
      "egisteredGroup\022\032\n\022registered_user_id\030\001 \001" +
      "(\005\022\020\n\010group_id\030\002 \001(\005\022\022\n\ngroup_name\030\003 \001(\t" +
      "\022\035\n\025group_announcement_id\030\004 \001(\005\022\025\n\rcreat" +
      "ion_time\030\005 \001(\003\022\031\n\021modification_time\030\006 \001(" +
      "\003\022\016\n\006amount\030\007 \001(\005\022\027\n\017group_member_id\030\010 \001" +
      "(\005\"s\n\037RpcRegisteredGroupAdministrator\022\030\n" +
      "\020administrator_id\030\001 \001(\005\022\032\n\022administrator" +
      "_type\030\002 \001(\t\022\032\n\022administrator_name\030\003 \001(\t\"" +
      "f\n)RpcRegisteredGroupGuestUserMemberRela" +
      "tion\022\033\n\023registered_group_id\030\001 \001(\005\022\034\n\024gue" +
      "st_user_member_id\030\002 \001(\005\"\273\002\n\030RpcRegistere" +
      "dGroupMember\022\027\n\017group_member_id\030\001 \001(\005\022\032\n" +
      "\022registered_user_id\030\002 \001(\005\022\025\n\rgroup_remar" +
      "ks\030\003 \001(\t\022\023\n\013group_owner\030\004 \001(\t\022#\n\033burn_af" +
      "ter_reading_settings\030\005 \001(\t\022$\n\034burn_after" +
      "_reading_time_unit\030\006 \001(\t\022&\n\036burn_after_r" +
      "eading_time_length\030\007 \001(\002\022\030\n\020group_entry_" +
      "time\030\010 \001(\003\022\037\n\027offline_message_setting\030\t " +
      "\001(\t\022\020\n\010group_id\030\n \001(\005\"p\n.RpcRegisteredGr" +
      "oupRegisteredUserMemberRelation\022\033\n\023regis" +
      "tered_group_id\030\001 \001(\005\022!\n\031registered_user_" +
      "member_id\030\002 \001(\005\"\327\002\n\027RpcRegisteredUserFri" +
      "end\022\032\n\022registered_user_id\030\001 \001(\005\022\021\n\tfrien" +
      "d_id\030\002 \001(\005\022\026\n\016friend_user_id\030\003 \001(\005\022\026\n\016fr" +
      "iend_comment\030\004 \001(\t\022\025\n\rcreation_time\030\005 \001(" +
      "\003\022\031\n\021modification_time\030\006 \001(\003\022\037\n\027offline_" +
      "message_setting\030\007 \001(\t\022\"\n\032burn_after_read" +
      "ing_setting\030\010 \001(\t\022$\n\034burn_after_reading_" +
      "time_unit\030\t \001(\t\022&\n\036burn_after_reading_ti" +
      "me_length\030\n \001(\002\022\030\n\020friend_nick_name\030\013 \001(" +
      "\t\"m\n\016RpcGroupRemark\022\020\n\010group_id\030\001 \001(\005\022\027\n" +
      "\017group_member_id\030\002 \001(\005\022 \n\030group_member_i" +
      "d_remarked\030\003 \001(\005\022\016\n\006remark\030\004 \001(\t\"\233\004\n\020All" +
      "GroupMemberVO\022\027\n\017group_member_id\030\001 \001(\005\022\033" +
      "\n\023registered_group_id\030\002 \001(\005\022\026\n\016guest_gro" +
      "up_id\030\003 \001(\005\022\032\n\022registered_user_id\030\004 \001(\005\022" +
      "\025\n\rguest_user_id\030\005 \001(\005\022\025\n\rgroup_remarks\030" +
      "\006 \001(\t\022\023\n\013group_owner\030\007 \001(\t\022\"\n\032burn_after" +
      "_reading_setting\030\010 \001(\t\022$\n\034burn_after_rea" +
      "ding_time_unit\030\t \001(\t\022&\n\036burn_after_readi" +
      "ng_time_length\030\n \001(\002\022\030\n\020group_entry_time" +
      "\030\013 \001(\003\022\037\n\027offline_message_setting\030\014 \001(\t\022" +
      "\036\n\026register_user_nick_ame\030\r \001(\t\022\033\n\023guest" +
      "_user_nick_ame\030\016 \001(\t\022\022\n\ngroup_name\030\017 \001(\t" +
      "\022\016\n\006amount\030\020 \001(\005\022\032\n\022announcement_title\030\021" +
      " \001(\t\022\034\n\024announcement_content\030\022 \001(\t\022\022\n\nus" +
      "er_photo\030\023 \001(\t\"x\n\027AllGroupsMemberRespons" +
      "e\022\025\n\rstatus_detail\030\001 \001(\t\022F\n\030response_gro" +
      "up_member_vo\030\002 \003(\0132$.com.lanjiu.im.grpc." +
      "AllGroupMemberVO\";\n\030SelectGroupMemberReq" +
      "uest\022\020\n\010group_id\030\001 \001(\t\022\r\n\005spare\030\002 \001(\t\"i\n" +
      "\026RpcGroupMemberNickname\022\020\n\010group_id\030\001 \001(" +
      "\005\022\017\n\007user_id\030\002 \001(\005\022\027\n\017group_member_id\030\003 " +
      "\001(\005\022\023\n\013nick_remark\030\004 \001(\t2\314{\n\031Information" +
      "StorageService\022y\n\031selectBeautifulNumberR" +
      "eal\022\'.com.lanjiu.im.grpc.TransmissionReq" +
      "uest\0321.com.lanjiu.im.grpc.BeautifulNumbe" +
      "rCommonResponse\"\000\022y\n\031selectBeautifulNumb" +
      "erAuto\022\'.com.lanjiu.im.grpc.Transmission" +
      "Request\0321.com.lanjiu.im.grpc.BeautifulNu" +
      "mberCommonResponse\"\000\022\201\001\n\036selectBurnAfter" +
      "ReadingPriority\022\'.com.lanjiu.im.grpc.Tra" +
      "nsmissionRequest\0324.com.lanjiu.im.grpc.Bu" +
      "rnAfterReadingPriorityResponse\"\000\022\201\001\n!sel" +
      "ectFriendUnusedBeautifulNumber\022\'.com.lan" +
      "jiu.im.grpc.TransmissionRequest\0321.com.la" +
      "njiu.im.grpc.BeautifulNumberCommonRespon" +
      "se\"\000\022\177\n\037selectFriendUsedBeautifulNumber\022" +
      "\'.com.lanjiu.im.grpc.TransmissionRequest" +
      "\0321.com.lanjiu.im.grpc.BeautifulNumberCom" +
      "monResponse\"\000\022u\n\030selectGroupAnnouncement" +
      "s\022\'.com.lanjiu.im.grpc.TransmissionReque" +
      "st\032..com.lanjiu.im.grpc.GroupAnnouncemen" +
      "tsResponse\"\000\022\206\001\n&selectGroupMemberUnused" +
      "BeautifulNumber\022\'.com.lanjiu.im.grpc.Tra" +
      "nsmissionRequest\0321.com.lanjiu.im.grpc.Be" +
      "autifulNumberCommonResponse\"\000\022\204\001\n$select" +
      "GroupMemberUsedBeautifulNumber\022\'.com.lan" +
      "jiu.im.grpc.TransmissionRequest\0321.com.la" +
      "njiu.im.grpc.BeautifulNumberCommonRespon" +
      "se\"\000\022\200\001\n selectGroupUnusedBeautifulNumbe" +
      "r\022\'.com.lanjiu.im.grpc.TransmissionReque" +
      "st\0321.com.lanjiu.im.grpc.BeautifulNumberC" +
      "ommonResponse\"\000\022~\n\036selectGroupUsedBeauti" +
      "fulNumber\022\'.com.lanjiu.im.grpc.Transmiss" +
      "ionRequest\0321.com.lanjiu.im.grpc.Beautifu" +
      "lNumberCommonResponse\"\000\022e\n\020selectGuestGr" +
      "oup\022\'.com.lanjiu.im.grpc.TransmissionReq" +
      "uest\032&.com.lanjiu.im.grpc.GuestGroupResp" +
      "onse\"\000\022\177\n\035selectGuestGroupAdministrator\022" +
      "\'.com.lanjiu.im.grpc.TransmissionRequest" +
      "\0323.com.lanjiu.im.grpc.GuestGroupAdminist" +
      "ratorResponse\"\000\022\223\001\n\'selectGuestGroupGues" +
      "tUserMemberRelation\022\'.com.lanjiu.im.grpc" +
      ".TransmissionRequest\032=.com.lanjiu.im.grp" +
      "c.GuestGroupGuestUserMemberRelationRespo" +
      "nse\"\000\022q\n\026selectGuestGroupMember\022\'.com.la" +
      "njiu.im.grpc.TransmissionRequest\032,.com.l" +
      "anjiu.im.grpc.GuestGroupMemberResponse\"\000" +
      "\022\235\001\n,selectGuestGroupRegisteredUserMembe" +
      "rRelation\022\'.com.lanjiu.im.grpc.Transmiss" +
      "ionRequest\032B.com.lanjiu.im.grpc.GuestGro" +
      "upRegisteredUserMemberRelationResponse\"\000" +
      "\022o\n\025selectGuestUserFriend\022\'.com.lanjiu.i" +
      "m.grpc.TransmissionRequest\032+.com.lanjiu." +
      "im.grpc.GuestUserFriendResponse\"\000\022}\n\034sel" +
      "ectOfflineMessagePriority\022\'.com.lanjiu.i" +
      "m.grpc.TransmissionRequest\0322.com.lanjiu." +
      "im.grpc.OfflineMessagePriorityResponse\"\000" +
      "\022o\n\025selectRegisteredGroup\022\'.com.lanjiu.i" +
      "m.grpc.TransmissionRequest\032+.com.lanjiu." +
      "im.grpc.RegisteredGroupResponse\"\000\022\211\001\n\"se" +
      "lectRegisteredGroupAdministrator\022\'.com.l" +
      "anjiu.im.grpc.TransmissionRequest\0328.com." +
      "lanjiu.im.grpc.RegisteredGroupAdministra" +
      "torResponse\"\000\022\235\001\n,selectRegisteredGroupG" +
      "uestUserMemberRelation\022\'.com.lanjiu.im.g" +
      "rpc.TransmissionRequest\032B.com.lanjiu.im." +
      "grpc.RegisteredGroupGuestUserMemberRelat" +
      "ionResponse\"\000\022{\n\033selectRegisteredGroupMe" +
      "mber\022\'.com.lanjiu.im.grpc.TransmissionRe" +
      "quest\0321.com.lanjiu.im.grpc.RegisteredGro" +
      "upMemberResponse\"\000\022\247\001\n1selectRegisteredG" +
      "roupRegisteredUserMemberRelation\022\'.com.l" +
      "anjiu.im.grpc.TransmissionRequest\032G.com." +
      "lanjiu.im.grpc.RegisteredGroupRegistered" +
      "UserMemberRelationResponse\"\000\022y\n\032selectRe" +
      "gisteredUserFriend\022\'.com.lanjiu.im.grpc." +
      "TransmissionRequest\0320.com.lanjiu.im.grpc" +
      ".RegisteredUserFriendResponse\"\000\022\204\001\n$sele" +
      "ctGroupUnusedBeautifulNumberReal\022\'.com.l" +
      "anjiu.im.grpc.TransmissionRequest\0321.com." +
      "lanjiu.im.grpc.BeautifulNumberCommonResp" +
      "onse\"\000\022\202\001\n\"selectGroupUsedBeautifulNumbe" +
      "rReal\022\'.com.lanjiu.im.grpc.TransmissionR" +
      "equest\0321.com.lanjiu.im.grpc.BeautifulNum" +
      "berCommonResponse\"\000\022\212\001\n*selectGroupMembe" +
      "rUnusedBeautifulNumberReal\022\'.com.lanjiu." +
      "im.grpc.TransmissionRequest\0321.com.lanjiu" +
      ".im.grpc.BeautifulNumberCommonResponse\"\000" +
      "\022\210\001\n(selectGroupMemberUsedBeautifulNumbe" +
      "rReal\022\'.com.lanjiu.im.grpc.TransmissionR" +
      "equest\0321.com.lanjiu.im.grpc.BeautifulNum" +
      "berCommonResponse\"\000\022\205\001\n%selectFriendUnus" +
      "edBeautifulNumberReal\022\'.com.lanjiu.im.gr" +
      "pc.TransmissionRequest\0321.com.lanjiu.im.g" +
      "rpc.BeautifulNumberCommonResponse\"\000\022\203\001\n#" +
      "selectFriendUsedBeautifulNumberReal\022\'.co" +
      "m.lanjiu.im.grpc.TransmissionRequest\0321.c" +
      "om.lanjiu.im.grpc.BeautifulNumberCommonR" +
      "esponse\"\000\022g\n\021selectGroupRemark\022\'.com.lan" +
      "jiu.im.grpc.TransmissionRequest\032\'.com.la" +
      "njiu.im.grpc.GroupRemarkResponse\"\000\022w\n\032se" +
      "lectGroupMembersInfoList\022,.com.lanjiu.im" +
      ".grpc.SelectGroupMemberRequest\032+.com.lan" +
      "jiu.im.grpc.AllGroupsMemberResponse\022v\n\031q" +
      "ueryGroupMembersInfoList\022,.com.lanjiu.im" +
      ".grpc.SelectGroupMemberRequest\032+.com.lan" +
      "jiu.im.grpc.AllGroupsMemberResponse\022n\n\026s" +
      "earchAllGroupByUserId\022\'.com.lanjiu.im.gr" +
      "pc.TransmissionRequest\032+.com.lanjiu.im.g" +
      "rpc.AllGroupsMemberResponse\022u\n\031selectGro" +
      "upMemberNickname\022\'.com.lanjiu.im.grpc.Tr" +
      "ansmissionRequest\032/.com.lanjiu.im.grpc.G" +
      "roupMemberNicknameResponse\022\201\001\n!insertFri" +
      "endUnusedBeautifulNumber\022\'.com.lanjiu.im" +
      ".grpc.TransmissionRequest\0321.com.lanjiu.i" +
      "m.grpc.BeautifulNumberCommonResponse\"\000\022\177" +
      "\n\037insertFriendUsedBeautifulNumber\022\'.com." +
      "lanjiu.im.grpc.TransmissionRequest\0321.com" +
      ".lanjiu.im.grpc.BeautifulNumberCommonRes" +
      "ponse\"\000\022u\n\030insertGroupAnnouncements\022\'.co" +
      "m.lanjiu.im.grpc.TransmissionRequest\032..c" +
      "om.lanjiu.im.grpc.GroupAnnouncementsResp" +
      "onse\"\000\022\206\001\n&insertGroupMemberUnusedBeauti" +
      "fulNumber\022\'.com.lanjiu.im.grpc.Transmiss" +
      "ionRequest\0321.com.lanjiu.im.grpc.Beautifu" +
      "lNumberCommonResponse\"\000\022\204\001\n$insertGroupM" +
      "emberUsedBeautifulNumber\022\'.com.lanjiu.im" +
      ".grpc.TransmissionRequest\0321.com.lanjiu.i" +
      "m.grpc.BeautifulNumberCommonResponse\"\000\022\200" +
      "\001\n insertGroupUnusedBeautifulNumber\022\'.co" +
      "m.lanjiu.im.grpc.TransmissionRequest\0321.c" +
      "om.lanjiu.im.grpc.BeautifulNumberCommonR" +
      "esponse\"\000\022~\n\036insertGroupUsedBeautifulNum" +
      "ber\022\'.com.lanjiu.im.grpc.TransmissionReq" +
      "uest\0321.com.lanjiu.im.grpc.BeautifulNumbe" +
      "rCommonResponse\"\000\022e\n\020insertGuestGroup\022\'." +
      "com.lanjiu.im.grpc.TransmissionRequest\032&" +
      ".com.lanjiu.im.grpc.GuestGroupResponse\"\000" +
      "\022\177\n\035insertGuestGroupAdministrator\022\'.com." +
      "lanjiu.im.grpc.TransmissionRequest\0323.com" +
      ".lanjiu.im.grpc.GuestGroupAdministratorR" +
      "esponse\"\000\022\223\001\n\'insertGuestGroupGuestUserM" +
      "emberRelation\022\'.com.lanjiu.im.grpc.Trans" +
      "missionRequest\032=.com.lanjiu.im.grpc.Gues" +
      "tGroupGuestUserMemberRelationResponse\"\000\022" +
      "q\n\026insertGuestGroupMember\022\'.com.lanjiu.i" +
      "m.grpc.TransmissionRequest\032,.com.lanjiu." +
      "im.grpc.GuestGroupMemberResponse\"\000\022\235\001\n,i" +
      "nsertGuestGroupRegisteredUserMemberRelat" +
      "ion\022\'.com.lanjiu.im.grpc.TransmissionReq" +
      "uest\032B.com.lanjiu.im.grpc.GuestGroupRegi" +
      "steredUserMemberRelationResponse\"\000\022o\n\025in" +
      "sertGuestUserFriend\022\'.com.lanjiu.im.grpc" +
      ".TransmissionRequest\032+.com.lanjiu.im.grp" +
      "c.GuestUserFriendResponse\"\000\022}\n\034insertOff" +
      "lineMessagePriority\022\'.com.lanjiu.im.grpc" +
      ".TransmissionRequest\0322.com.lanjiu.im.grp" +
      "c.OfflineMessagePriorityResponse\"\000\022o\n\025in" +
      "sertRegisteredGroup\022\'.com.lanjiu.im.grpc" +
      ".TransmissionRequest\032+.com.lanjiu.im.grp" +
      "c.RegisteredGroupResponse\"\000\022\211\001\n\"insertRe" +
      "gisteredGroupAdministrator\022\'.com.lanjiu." +
      "im.grpc.TransmissionRequest\0328.com.lanjiu" +
      ".im.grpc.RegisteredGroupAdministratorRes" +
      "ponse\"\000\022\235\001\n,insertRegisteredGroupGuestUs" +
      "erMemberRelation\022\'.com.lanjiu.im.grpc.Tr" +
      "ansmissionRequest\032B.com.lanjiu.im.grpc.R" +
      "egisteredGroupGuestUserMemberRelationRes" +
      "ponse\"\000\022{\n\033insertRegisteredGroupMember\022\'" +
      ".com.lanjiu.im.grpc.TransmissionRequest\032" +
      "1.com.lanjiu.im.grpc.RegisteredGroupMemb" +
      "erResponse\"\000\022\247\001\n1insertRegisteredGroupRe" +
      "gisteredUserMemberRelation\022\'.com.lanjiu." +
      "im.grpc.TransmissionRequest\032G.com.lanjiu" +
      ".im.grpc.RegisteredGroupRegisteredUserMe" +
      "mberRelationResponse\"\000\022y\n\032insertRegister" +
      "edUserFriend\022\'.com.lanjiu.im.grpc.Transm" +
      "issionRequest\0320.com.lanjiu.im.grpc.Regis" +
      "teredUserFriendResponse\"\000\022\204\001\n$insertGrou" +
      "pUnusedBeautifulNumberReal\022\'.com.lanjiu." +
      "im.grpc.TransmissionRequest\0321.com.lanjiu" +
      ".im.grpc.BeautifulNumberCommonResponse\"\000" +
      "\022\202\001\n\"insertGroupUsedBeautifulNumberReal\022" +
      "\'.com.lanjiu.im.grpc.TransmissionRequest" +
      "\0321.com.lanjiu.im.grpc.BeautifulNumberCom" +
      "monResponse\"\000\022\212\001\n*insertGroupMemberUnuse" +
      "dBeautifulNumberReal\022\'.com.lanjiu.im.grp" +
      "c.TransmissionRequest\0321.com.lanjiu.im.gr",
      "pc.BeautifulNumberCommonResponse\"\000\022\210\001\n(i" +
      "nsertGroupMemberUsedBeautifulNumberReal\022" +
      "\'.com.lanjiu.im.grpc.TransmissionRequest" +
      "\0321.com.lanjiu.im.grpc.BeautifulNumberCom" +
      "monResponse\"\000\022\205\001\n%insertFriendUnusedBeau" +
      "tifulNumberReal\022\'.com.lanjiu.im.grpc.Tra" +
      "nsmissionRequest\0321.com.lanjiu.im.grpc.Be" +
      "autifulNumberCommonResponse\"\000\022\203\001\n#insert" +
      "FriendUsedBeautifulNumberReal\022\'.com.lanj" +
      "iu.im.grpc.TransmissionRequest\0321.com.lan" +
      "jiu.im.grpc.BeautifulNumberCommonRespons" +
      "e\"\000\022g\n\021insertGroupRemark\022\'.com.lanjiu.im" +
      ".grpc.TransmissionRequest\032\'.com.lanjiu.i" +
      "m.grpc.GroupRemarkResponse\"\000\022r\n\032insertIn" +
      "viteUsersJoinGroup\022\'.com.lanjiu.im.grpc." +
      "TransmissionRequest\032+.com.lanjiu.im.grpc" +
      ".AllGroupsMemberResponse\022k\n\023insertGroupP" +
      "hotoUrl\022\'.com.lanjiu.im.grpc.Transmissio" +
      "nRequest\032+.com.lanjiu.im.grpc.AllGroupsM" +
      "emberResponse\022\201\001\n!updateFriendUnusedBeau" +
      "tifulNumber\022\'.com.lanjiu.im.grpc.Transmi" +
      "ssionRequest\0321.com.lanjiu.im.grpc.Beauti" +
      "fulNumberCommonResponse\"\000\022\177\n\037updateFrien" +
      "dUsedBeautifulNumber\022\'.com.lanjiu.im.grp" +
      "c.TransmissionRequest\0321.com.lanjiu.im.gr" +
      "pc.BeautifulNumberCommonResponse\"\000\022u\n\030up" +
      "dateGroupAnnouncements\022\'.com.lanjiu.im.g" +
      "rpc.TransmissionRequest\032..com.lanjiu.im." +
      "grpc.GroupAnnouncementsResponse\"\000\022\206\001\n&up" +
      "dateGroupMemberUnusedBeautifulNumber\022\'.c" +
      "om.lanjiu.im.grpc.TransmissionRequest\0321." +
      "com.lanjiu.im.grpc.BeautifulNumberCommon" +
      "Response\"\000\022\204\001\n$updateGroupMemberUsedBeau" +
      "tifulNumber\022\'.com.lanjiu.im.grpc.Transmi" +
      "ssionRequest\0321.com.lanjiu.im.grpc.Beauti" +
      "fulNumberCommonResponse\"\000\022\200\001\n updateGrou" +
      "pUnusedBeautifulNumber\022\'.com.lanjiu.im.g" +
      "rpc.TransmissionRequest\0321.com.lanjiu.im." +
      "grpc.BeautifulNumberCommonResponse\"\000\022~\n\036" +
      "updateGroupUsedBeautifulNumber\022\'.com.lan" +
      "jiu.im.grpc.TransmissionRequest\0321.com.la" +
      "njiu.im.grpc.BeautifulNumberCommonRespon" +
      "se\"\000\022e\n\020updateGuestGroup\022\'.com.lanjiu.im" +
      ".grpc.TransmissionRequest\032&.com.lanjiu.i" +
      "m.grpc.GuestGroupResponse\"\000\022\177\n\035updateGue" +
      "stGroupAdministrator\022\'.com.lanjiu.im.grp" +
      "c.TransmissionRequest\0323.com.lanjiu.im.gr" +
      "pc.GuestGroupAdministratorResponse\"\000\022\223\001\n" +
      "\'updateGuestGroupGuestUserMemberRelation" +
      "\022\'.com.lanjiu.im.grpc.TransmissionReques" +
      "t\032=.com.lanjiu.im.grpc.GuestGroupGuestUs" +
      "erMemberRelationResponse\"\000\022q\n\026updateGues" +
      "tGroupMember\022\'.com.lanjiu.im.grpc.Transm" +
      "issionRequest\032,.com.lanjiu.im.grpc.Guest" +
      "GroupMemberResponse\"\000\022\235\001\n,updateGuestGro" +
      "upRegisteredUserMemberRelation\022\'.com.lan" +
      "jiu.im.grpc.TransmissionRequest\032B.com.la" +
      "njiu.im.grpc.GuestGroupRegisteredUserMem" +
      "berRelationResponse\"\000\022o\n\025updateGuestUser" +
      "Friend\022\'.com.lanjiu.im.grpc.Transmission" +
      "Request\032+.com.lanjiu.im.grpc.GuestUserFr" +
      "iendResponse\"\000\022}\n\034updateOfflineMessagePr" +
      "iority\022\'.com.lanjiu.im.grpc.Transmission" +
      "Request\0322.com.lanjiu.im.grpc.OfflineMess" +
      "agePriorityResponse\"\000\022o\n\025updateRegistere" +
      "dGroup\022\'.com.lanjiu.im.grpc.Transmission" +
      "Request\032+.com.lanjiu.im.grpc.RegisteredG" +
      "roupResponse\"\000\022\211\001\n\"updateRegisteredGroup" +
      "Administrator\022\'.com.lanjiu.im.grpc.Trans" +
      "missionRequest\0328.com.lanjiu.im.grpc.Regi" +
      "steredGroupAdministratorResponse\"\000\022\235\001\n,u" +
      "pdateRegisteredGroupGuestUserMemberRelat" +
      "ion\022\'.com.lanjiu.im.grpc.TransmissionReq" +
      "uest\032B.com.lanjiu.im.grpc.RegisteredGrou" +
      "pGuestUserMemberRelationResponse\"\000\022{\n\033up" +
      "dateRegisteredGroupMember\022\'.com.lanjiu.i" +
      "m.grpc.TransmissionRequest\0321.com.lanjiu." +
      "im.grpc.RegisteredGroupMemberResponse\"\000\022" +
      "\247\001\n1updateRegisteredGroupRegisteredUserM" +
      "emberRelation\022\'.com.lanjiu.im.grpc.Trans" +
      "missionRequest\032G.com.lanjiu.im.grpc.Regi" +
      "steredGroupRegisteredUserMemberRelationR" +
      "esponse\"\000\022y\n\032updateRegisteredUserFriend\022" +
      "\'.com.lanjiu.im.grpc.TransmissionRequest" +
      "\0320.com.lanjiu.im.grpc.RegisteredUserFrie" +
      "ndResponse\"\000\022\204\001\n$updateGroupUnusedBeauti" +
      "fulNumberReal\022\'.com.lanjiu.im.grpc.Trans" +
      "missionRequest\0321.com.lanjiu.im.grpc.Beau" +
      "tifulNumberCommonResponse\"\000\022\202\001\n\"updateGr" +
      "oupUsedBeautifulNumberReal\022\'.com.lanjiu." +
      "im.grpc.TransmissionRequest\0321.com.lanjiu" +
      ".im.grpc.BeautifulNumberCommonResponse\"\000" +
      "\022\212\001\n*updateGroupMemberUnusedBeautifulNum" +
      "berReal\022\'.com.lanjiu.im.grpc.Transmissio" +
      "nRequest\0321.com.lanjiu.im.grpc.BeautifulN" +
      "umberCommonResponse\"\000\022\210\001\n(updateGroupMem" +
      "berUsedBeautifulNumberReal\022\'.com.lanjiu." +
      "im.grpc.TransmissionRequest\0321.com.lanjiu" +
      ".im.grpc.BeautifulNumberCommonResponse\"\000" +
      "\022\205\001\n%updateFriendUnusedBeautifulNumberRe" +
      "al\022\'.com.lanjiu.im.grpc.TransmissionRequ" +
      "est\0321.com.lanjiu.im.grpc.BeautifulNumber" +
      "CommonResponse\"\000\022\203\001\n#updateFriendUsedBea" +
      "utifulNumberReal\022\'.com.lanjiu.im.grpc.Tr" +
      "ansmissionRequest\0321.com.lanjiu.im.grpc.B" +
      "eautifulNumberCommonResponse\"\000\022g\n\021update" +
      "GroupRemark\022\'.com.lanjiu.im.grpc.Transmi" +
      "ssionRequest\032\'.com.lanjiu.im.grpc.GroupR" +
      "emarkResponse\"\000\022x\n\032updateRegGroupMemberR" +
      "emark\022\'.com.lanjiu.im.grpc.TransmissionR" +
      "equest\0321.com.lanjiu.im.grpc.RegisteredGr" +
      "oupMemberResponse\022\201\001\n!deleteFriendUnused" +
      "BeautifulNumber\022\'.com.lanjiu.im.grpc.Tra" +
      "nsmissionRequest\0321.com.lanjiu.im.grpc.Be" +
      "autifulNumberCommonResponse\"\000\022\177\n\037deleteF" +
      "riendUsedBeautifulNumber\022\'.com.lanjiu.im" +
      ".grpc.TransmissionRequest\0321.com.lanjiu.i" +
      "m.grpc.BeautifulNumberCommonResponse\"\000\022u" +
      "\n\030deleteGroupAnnouncements\022\'.com.lanjiu." +
      "im.grpc.TransmissionRequest\032..com.lanjiu" +
      ".im.grpc.GroupAnnouncementsResponse\"\000\022\206\001" +
      "\n&deleteGroupMemberUnusedBeautifulNumber" +
      "\022\'.com.lanjiu.im.grpc.TransmissionReques" +
      "t\0321.com.lanjiu.im.grpc.BeautifulNumberCo" +
      "mmonResponse\"\000\022\204\001\n$deleteGroupMemberUsed" +
      "BeautifulNumber\022\'.com.lanjiu.im.grpc.Tra" +
      "nsmissionRequest\0321.com.lanjiu.im.grpc.Be" +
      "autifulNumberCommonResponse\"\000\022\200\001\n delete" +
      "GroupUnusedBeautifulNumber\022\'.com.lanjiu." +
      "im.grpc.TransmissionRequest\0321.com.lanjiu" +
      ".im.grpc.BeautifulNumberCommonResponse\"\000" +
      "\022~\n\036deleteGroupUsedBeautifulNumber\022\'.com" +
      ".lanjiu.im.grpc.TransmissionRequest\0321.co" +
      "m.lanjiu.im.grpc.BeautifulNumberCommonRe" +
      "sponse\"\000\022e\n\020deleteGuestGroup\022\'.com.lanji" +
      "u.im.grpc.TransmissionRequest\032&.com.lanj" +
      "iu.im.grpc.GuestGroupResponse\"\000\022\177\n\035delet" +
      "eGuestGroupAdministrator\022\'.com.lanjiu.im" +
      ".grpc.TransmissionRequest\0323.com.lanjiu.i" +
      "m.grpc.GuestGroupAdministratorResponse\"\000" +
      "\022\223\001\n\'deleteGuestGroupGuestUserMemberRela" +
      "tion\022\'.com.lanjiu.im.grpc.TransmissionRe" +
      "quest\032=.com.lanjiu.im.grpc.GuestGroupGue" +
      "stUserMemberRelationResponse\"\000\022q\n\026delete" +
      "GuestGroupMember\022\'.com.lanjiu.im.grpc.Tr" +
      "ansmissionRequest\032,.com.lanjiu.im.grpc.G" +
      "uestGroupMemberResponse\"\000\022\235\001\n,deleteGues" +
      "tGroupRegisteredUserMemberRelation\022\'.com" +
      ".lanjiu.im.grpc.TransmissionRequest\032B.co" +
      "m.lanjiu.im.grpc.GuestGroupRegisteredUse" +
      "rMemberRelationResponse\"\000\022o\n\025deleteGuest" +
      "UserFriend\022\'.com.lanjiu.im.grpc.Transmis" +
      "sionRequest\032+.com.lanjiu.im.grpc.GuestUs" +
      "erFriendResponse\"\000\022}\n\034deleteOfflineMessa" +
      "gePriority\022\'.com.lanjiu.im.grpc.Transmis" +
      "sionRequest\0322.com.lanjiu.im.grpc.Offline" +
      "MessagePriorityResponse\"\000\022o\n\025deleteRegis" +
      "teredGroup\022\'.com.lanjiu.im.grpc.Transmis" +
      "sionRequest\032+.com.lanjiu.im.grpc.Registe" +
      "redGroupResponse\"\000\022\211\001\n\"deleteRegisteredG" +
      "roupAdministrator\022\'.com.lanjiu.im.grpc.T" +
      "ransmissionRequest\0328.com.lanjiu.im.grpc." +
      "RegisteredGroupAdministratorResponse\"\000\022\235" +
      "\001\n,deleteRegisteredGroupGuestUserMemberR" +
      "elation\022\'.com.lanjiu.im.grpc.Transmissio" +
      "nRequest\032B.com.lanjiu.im.grpc.Registered" +
      "GroupGuestUserMemberRelationResponse\"\000\022{" +
      "\n\033deleteRegisteredGroupMember\022\'.com.lanj" +
      "iu.im.grpc.TransmissionRequest\0321.com.lan" +
      "jiu.im.grpc.RegisteredGroupMemberRespons" +
      "e\"\000\022\247\001\n1deleteRegisteredGroupRegisteredU" +
      "serMemberRelation\022\'.com.lanjiu.im.grpc.T" +
      "ransmissionRequest\032G.com.lanjiu.im.grpc." +
      "RegisteredGroupRegisteredUserMemberRelat" +
      "ionResponse\"\000\022y\n\032deleteRegisteredUserFri" +
      "end\022\'.com.lanjiu.im.grpc.TransmissionReq" +
      "uest\0320.com.lanjiu.im.grpc.RegisteredUser" +
      "FriendResponse\"\000\022\204\001\n$deleteGroupUnusedBe" +
      "autifulNumberReal\022\'.com.lanjiu.im.grpc.T" +
      "ransmissionRequest\0321.com.lanjiu.im.grpc." +
      "BeautifulNumberCommonResponse\"\000\022\202\001\n\"dele" +
      "teGroupUsedBeautifulNumberReal\022\'.com.lan" +
      "jiu.im.grpc.TransmissionRequest\0321.com.la" +
      "njiu.im.grpc.BeautifulNumberCommonRespon" +
      "se\"\000\022\212\001\n*deleteGroupMemberUnusedBeautifu" +
      "lNumberReal\022\'.com.lanjiu.im.grpc.Transmi" +
      "ssionRequest\0321.com.lanjiu.im.grpc.Beauti" +
      "fulNumberCommonResponse\"\000\022\210\001\n(deleteGrou" +
      "pMemberUsedBeautifulNumberReal\022\'.com.lan" +
      "jiu.im.grpc.TransmissionRequest\0321.com.la" +
      "njiu.im.grpc.BeautifulNumberCommonRespon" +
      "se\"\000\022\205\001\n%deleteFriendUnusedBeautifulNumb" +
      "erReal\022\'.com.lanjiu.im.grpc.Transmission" +
      "Request\0321.com.lanjiu.im.grpc.BeautifulNu" +
      "mberCommonResponse\"\000\022\203\001\n#deleteFriendUse" +
      "dBeautifulNumberReal\022\'.com.lanjiu.im.grp" +
      "c.TransmissionRequest\0321.com.lanjiu.im.gr" +
      "pc.BeautifulNumberCommonResponse\"\000\022g\n\021de" +
      "leteGroupRemark\022\'.com.lanjiu.im.grpc.Tra" +
      "nsmissionRequest\032\'.com.lanjiu.im.grpc.Gr" +
      "oupRemarkResponse\"\000\022s\n\031deleteGuestRelate" +
      "dAllInfo\022\'.com.lanjiu.im.grpc.Transmissi" +
      "onRequest\032+.com.lanjiu.im.grpc.AllGroups" +
      "MemberResponse\"\000\022s\n\031deleteMembersByGroup" +
      "Owner\022\'.com.lanjiu.im.grpc.TransmissionR" +
      "equest\032+.com.lanjiu.im.grpc.AllGroupsMem" +
      "berResponse\"\000\022p\n\030groupMemberExitGroupCha" +
      "t\022\'.com.lanjiu.im.grpc.TransmissionReque" +
      "st\032+.com.lanjiu.im.grpc.AllGroupsMemberR" +
      "esponseB1\n\022com.lanjiu.im.grpcB\027Informati" +
      "onStorageProtoH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_lanjiu_im_grpc_TransmissionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_lanjiu_im_grpc_TransmissionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_TransmissionRequest_descriptor,
        new java.lang.String[] { "BeautifulNumberCommon", "BurnAfterReadingPriority", "GroupAnnouncements", "GuestGroup", "GuestGroupAdministrator", "GuestGroupGuestUserRelation", "GuestGroupMember", "GuestGroupRegisteredUserRelation", "GuestUserFriend", "OfflineMessagePriority", "RegisteredGroup", "RegisteredGroupAdministrator", "RegisteredGroupGuestUserRelation", "RegisteredGroupMember", "RegisteredGroupRegisteredUserRelation", "RegisteredUserFriend", "GroupRemark", "RequestKind", "AllGroupMemberVo", });
    internal_static_com_lanjiu_im_grpc_BeautifulNumberCommonResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_lanjiu_im_grpc_BeautifulNumberCommonResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_BeautifulNumberCommonResponse_descriptor,
        new java.lang.String[] { "StatusDetail", "ResponseData", });
    internal_static_com_lanjiu_im_grpc_BurnAfterReadingPriorityResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_lanjiu_im_grpc_BurnAfterReadingPriorityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_BurnAfterReadingPriorityResponse_descriptor,
        new java.lang.String[] { "StatusDetail", "ResponseData", });
    internal_static_com_lanjiu_im_grpc_GroupAnnouncementsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_lanjiu_im_grpc_GroupAnnouncementsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_GroupAnnouncementsResponse_descriptor,
        new java.lang.String[] { "StatusDetail", "ResponseData", });
    internal_static_com_lanjiu_im_grpc_GuestGroupResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_lanjiu_im_grpc_GuestGroupResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_GuestGroupResponse_descriptor,
        new java.lang.String[] { "StatusDetail", "ResponseGuestGroup", "ResponseRegisteredGroup", "ResponseGuestGroupMember", "ResponseRegisteredGroupMember", "ResponseGroupMemberVo", });
    internal_static_com_lanjiu_im_grpc_GuestGroupAdministratorResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_lanjiu_im_grpc_GuestGroupAdministratorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_GuestGroupAdministratorResponse_descriptor,
        new java.lang.String[] { "StatusDetail", "ResponseData", });
    internal_static_com_lanjiu_im_grpc_GuestGroupGuestUserMemberRelationResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_lanjiu_im_grpc_GuestGroupGuestUserMemberRelationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_GuestGroupGuestUserMemberRelationResponse_descriptor,
        new java.lang.String[] { "StatusDetail", "ResponseData", });
    internal_static_com_lanjiu_im_grpc_GuestGroupMemberResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_lanjiu_im_grpc_GuestGroupMemberResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_GuestGroupMemberResponse_descriptor,
        new java.lang.String[] { "StatusDetail", "ResponseData", "RegisteredGroupData", "GuestGroupData", });
    internal_static_com_lanjiu_im_grpc_GuestGroupRegisteredUserMemberRelationResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_lanjiu_im_grpc_GuestGroupRegisteredUserMemberRelationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_GuestGroupRegisteredUserMemberRelationResponse_descriptor,
        new java.lang.String[] { "StatusDetail", "ResponseData", });
    internal_static_com_lanjiu_im_grpc_GuestUserFriendResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_lanjiu_im_grpc_GuestUserFriendResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_GuestUserFriendResponse_descriptor,
        new java.lang.String[] { "StatusDetail", "ResponseData", });
    internal_static_com_lanjiu_im_grpc_OfflineMessagePriorityResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_lanjiu_im_grpc_OfflineMessagePriorityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_OfflineMessagePriorityResponse_descriptor,
        new java.lang.String[] { "StatusDetail", "ResponseData", });
    internal_static_com_lanjiu_im_grpc_RegisteredGroupResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_lanjiu_im_grpc_RegisteredGroupResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_RegisteredGroupResponse_descriptor,
        new java.lang.String[] { "StatusDetail", "ResponseRegisteredGroup", "ResponseGuestGroup", "ResponseRegisteredGroupMember", "ResponseGuestGroupMember", "ResponseGroupMemberVo", });
    internal_static_com_lanjiu_im_grpc_RegisteredGroupAdministratorResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_com_lanjiu_im_grpc_RegisteredGroupAdministratorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_RegisteredGroupAdministratorResponse_descriptor,
        new java.lang.String[] { "StatusDetail", "ResponseData", });
    internal_static_com_lanjiu_im_grpc_RegisteredGroupGuestUserMemberRelationResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_com_lanjiu_im_grpc_RegisteredGroupGuestUserMemberRelationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_RegisteredGroupGuestUserMemberRelationResponse_descriptor,
        new java.lang.String[] { "StatusDetail", "ResponseData", });
    internal_static_com_lanjiu_im_grpc_RegisteredGroupMemberResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_com_lanjiu_im_grpc_RegisteredGroupMemberResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_RegisteredGroupMemberResponse_descriptor,
        new java.lang.String[] { "StatusDetail", "ResponseData", "RegisteredGroupData", "GuestGroupData", });
    internal_static_com_lanjiu_im_grpc_RegisteredGroupRegisteredUserMemberRelationResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_com_lanjiu_im_grpc_RegisteredGroupRegisteredUserMemberRelationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_RegisteredGroupRegisteredUserMemberRelationResponse_descriptor,
        new java.lang.String[] { "StatusDetail", "ResponseData", });
    internal_static_com_lanjiu_im_grpc_RegisteredUserFriendResponse_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_com_lanjiu_im_grpc_RegisteredUserFriendResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_RegisteredUserFriendResponse_descriptor,
        new java.lang.String[] { "StatusDetail", "ResponseData", });
    internal_static_com_lanjiu_im_grpc_GroupRemarkResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_com_lanjiu_im_grpc_GroupRemarkResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_GroupRemarkResponse_descriptor,
        new java.lang.String[] { "StatusDetail", "ResponseData", });
    internal_static_com_lanjiu_im_grpc_GroupMemberNicknameResponse_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_com_lanjiu_im_grpc_GroupMemberNicknameResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_GroupMemberNicknameResponse_descriptor,
        new java.lang.String[] { "StatusDetail", "ResponseData", });
    internal_static_com_lanjiu_im_grpc_RpcBeautifulNumberCommon_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_com_lanjiu_im_grpc_RpcBeautifulNumberCommon_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_RpcBeautifulNumberCommon_descriptor,
        new java.lang.String[] { "TenMillion", "OneMillion", "OneHundredThousand", "TenThousand", "OneThousand", "OneHundred", "Ten", "One", });
    internal_static_com_lanjiu_im_grpc_RpcBurnAfterReadingPriority_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_com_lanjiu_im_grpc_RpcBurnAfterReadingPriority_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_RpcBurnAfterReadingPriority_descriptor,
        new java.lang.String[] { "Type", "Priority", });
    internal_static_com_lanjiu_im_grpc_RpcGroupAnnouncements_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_com_lanjiu_im_grpc_RpcGroupAnnouncements_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_RpcGroupAnnouncements_descriptor,
        new java.lang.String[] { "GroupAnnouncementId", "AnnouncementTitle", "AnnouncementContent", });
    internal_static_com_lanjiu_im_grpc_RpcGuestGroup_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_com_lanjiu_im_grpc_RpcGuestGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_RpcGuestGroup_descriptor,
        new java.lang.String[] { "GuestUserId", "GroupId", "GroupName", "GroupAnnouncementId", "CreationTime", "ModificationTime", "Amount", "GroupMemberId", });
    internal_static_com_lanjiu_im_grpc_RpcGuestGroupAdministrator_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_com_lanjiu_im_grpc_RpcGuestGroupAdministrator_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_RpcGuestGroupAdministrator_descriptor,
        new java.lang.String[] { "AdministratorId", "AdministratorType", "AdministratorName", });
    internal_static_com_lanjiu_im_grpc_RpcGuestGroupGuestUserMemberRelation_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_com_lanjiu_im_grpc_RpcGuestGroupGuestUserMemberRelation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_RpcGuestGroupGuestUserMemberRelation_descriptor,
        new java.lang.String[] { "GuestGroupId", "GuestUserMemberId", });
    internal_static_com_lanjiu_im_grpc_RpcGuestGroupMember_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_com_lanjiu_im_grpc_RpcGuestGroupMember_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_RpcGuestGroupMember_descriptor,
        new java.lang.String[] { "GroupMemberId", "GuestUserId", "GroupRemarks", "GroupOwner", "BurnAfterReadingSettings", "BurnAfterReadingTimeUnit", "BurnAfterReadingTimeLength", "GroupEntryTime", "OfflineMessageSetting", "GroupId", });
    internal_static_com_lanjiu_im_grpc_RpcGuestGroupRegisteredUserMemberRelation_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_com_lanjiu_im_grpc_RpcGuestGroupRegisteredUserMemberRelation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_RpcGuestGroupRegisteredUserMemberRelation_descriptor,
        new java.lang.String[] { "GuestGroupId", "RegisteredUserMemberId", });
    internal_static_com_lanjiu_im_grpc_RpcGuestUserFriend_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_com_lanjiu_im_grpc_RpcGuestUserFriend_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_RpcGuestUserFriend_descriptor,
        new java.lang.String[] { "GuestUserId", "FriendId", "FriendUserId", "FriendComment", "CreationTime", "ModificationTime", "OfflineMessageSetting", "BurnAfterReadingSetting", "BurnAfterReadingTimeUnit", "BurnAfterReadingTimeLength", "FriendNickName", });
    internal_static_com_lanjiu_im_grpc_RpcOfflineMessagePriority_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_com_lanjiu_im_grpc_RpcOfflineMessagePriority_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_RpcOfflineMessagePriority_descriptor,
        new java.lang.String[] { "Type", "Priority", });
    internal_static_com_lanjiu_im_grpc_RpcRegisteredGroup_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_com_lanjiu_im_grpc_RpcRegisteredGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_RpcRegisteredGroup_descriptor,
        new java.lang.String[] { "RegisteredUserId", "GroupId", "GroupName", "GroupAnnouncementId", "CreationTime", "ModificationTime", "Amount", "GroupMemberId", });
    internal_static_com_lanjiu_im_grpc_RpcRegisteredGroupAdministrator_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_com_lanjiu_im_grpc_RpcRegisteredGroupAdministrator_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_RpcRegisteredGroupAdministrator_descriptor,
        new java.lang.String[] { "AdministratorId", "AdministratorType", "AdministratorName", });
    internal_static_com_lanjiu_im_grpc_RpcRegisteredGroupGuestUserMemberRelation_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_com_lanjiu_im_grpc_RpcRegisteredGroupGuestUserMemberRelation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_RpcRegisteredGroupGuestUserMemberRelation_descriptor,
        new java.lang.String[] { "RegisteredGroupId", "GuestUserMemberId", });
    internal_static_com_lanjiu_im_grpc_RpcRegisteredGroupMember_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_com_lanjiu_im_grpc_RpcRegisteredGroupMember_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_RpcRegisteredGroupMember_descriptor,
        new java.lang.String[] { "GroupMemberId", "RegisteredUserId", "GroupRemarks", "GroupOwner", "BurnAfterReadingSettings", "BurnAfterReadingTimeUnit", "BurnAfterReadingTimeLength", "GroupEntryTime", "OfflineMessageSetting", "GroupId", });
    internal_static_com_lanjiu_im_grpc_RpcRegisteredGroupRegisteredUserMemberRelation_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_com_lanjiu_im_grpc_RpcRegisteredGroupRegisteredUserMemberRelation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_RpcRegisteredGroupRegisteredUserMemberRelation_descriptor,
        new java.lang.String[] { "RegisteredGroupId", "RegisteredUserMemberId", });
    internal_static_com_lanjiu_im_grpc_RpcRegisteredUserFriend_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_com_lanjiu_im_grpc_RpcRegisteredUserFriend_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_RpcRegisteredUserFriend_descriptor,
        new java.lang.String[] { "RegisteredUserId", "FriendId", "FriendUserId", "FriendComment", "CreationTime", "ModificationTime", "OfflineMessageSetting", "BurnAfterReadingSetting", "BurnAfterReadingTimeUnit", "BurnAfterReadingTimeLength", "FriendNickName", });
    internal_static_com_lanjiu_im_grpc_RpcGroupRemark_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_com_lanjiu_im_grpc_RpcGroupRemark_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_RpcGroupRemark_descriptor,
        new java.lang.String[] { "GroupId", "GroupMemberId", "GroupMemberIdRemarked", "Remark", });
    internal_static_com_lanjiu_im_grpc_AllGroupMemberVO_descriptor =
      getDescriptor().getMessageTypes().get(36);
    internal_static_com_lanjiu_im_grpc_AllGroupMemberVO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_AllGroupMemberVO_descriptor,
        new java.lang.String[] { "GroupMemberId", "RegisteredGroupId", "GuestGroupId", "RegisteredUserId", "GuestUserId", "GroupRemarks", "GroupOwner", "BurnAfterReadingSetting", "BurnAfterReadingTimeUnit", "BurnAfterReadingTimeLength", "GroupEntryTime", "OfflineMessageSetting", "RegisterUserNickAme", "GuestUserNickAme", "GroupName", "Amount", "AnnouncementTitle", "AnnouncementContent", "UserPhoto", });
    internal_static_com_lanjiu_im_grpc_AllGroupsMemberResponse_descriptor =
      getDescriptor().getMessageTypes().get(37);
    internal_static_com_lanjiu_im_grpc_AllGroupsMemberResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_AllGroupsMemberResponse_descriptor,
        new java.lang.String[] { "StatusDetail", "ResponseGroupMemberVo", });
    internal_static_com_lanjiu_im_grpc_SelectGroupMemberRequest_descriptor =
      getDescriptor().getMessageTypes().get(38);
    internal_static_com_lanjiu_im_grpc_SelectGroupMemberRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_SelectGroupMemberRequest_descriptor,
        new java.lang.String[] { "GroupId", "Spare", });
    internal_static_com_lanjiu_im_grpc_RpcGroupMemberNickname_descriptor =
      getDescriptor().getMessageTypes().get(39);
    internal_static_com_lanjiu_im_grpc_RpcGroupMemberNickname_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_RpcGroupMemberNickname_descriptor,
        new java.lang.String[] { "GroupId", "UserId", "GroupMemberId", "NickRemark", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
