// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file_transfer_communication_grpc.proto

package com.lanjiu.pro.file;

/**
 * <pre>
 * 群上传申请
 * </pre>
 *
 * Protobuf type {@code com.lanjiu.pro.file.GroupTransmissionRequest}
 */
public  final class GroupTransmissionRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.lanjiu.pro.file.GroupTransmissionRequest)
    GroupTransmissionRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GroupTransmissionRequest.newBuilder() to construct.
  private GroupTransmissionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GroupTransmissionRequest() {
    checksum_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GroupTransmissionRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GroupTransmissionRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.lanjiu.pro.file.OriginalPictureVideoGroupTransmission.Builder subBuilder = null;
            if (groupPictureVideoMessage_ != null) {
              subBuilder = groupPictureVideoMessage_.toBuilder();
            }
            groupPictureVideoMessage_ = input.readMessage(com.lanjiu.pro.file.OriginalPictureVideoGroupTransmission.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(groupPictureVideoMessage_);
              groupPictureVideoMessage_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            checksum_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.lanjiu.pro.file.FileTransmissionProto.internal_static_com_lanjiu_pro_file_GroupTransmissionRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.lanjiu.pro.file.FileTransmissionProto.internal_static_com_lanjiu_pro_file_GroupTransmissionRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.lanjiu.pro.file.GroupTransmissionRequest.class, com.lanjiu.pro.file.GroupTransmissionRequest.Builder.class);
  }

  public static final int GROUP_PICTURE_VIDEO_MESSAGE_FIELD_NUMBER = 1;
  private com.lanjiu.pro.file.OriginalPictureVideoGroupTransmission groupPictureVideoMessage_;
  /**
   * <code>.com.lanjiu.pro.file.OriginalPictureVideoGroupTransmission Group_picture_video_message = 1;</code>
   * @return Whether the groupPictureVideoMessage field is set.
   */
  public boolean hasGroupPictureVideoMessage() {
    return groupPictureVideoMessage_ != null;
  }
  /**
   * <code>.com.lanjiu.pro.file.OriginalPictureVideoGroupTransmission Group_picture_video_message = 1;</code>
   * @return The groupPictureVideoMessage.
   */
  public com.lanjiu.pro.file.OriginalPictureVideoGroupTransmission getGroupPictureVideoMessage() {
    return groupPictureVideoMessage_ == null ? com.lanjiu.pro.file.OriginalPictureVideoGroupTransmission.getDefaultInstance() : groupPictureVideoMessage_;
  }
  /**
   * <code>.com.lanjiu.pro.file.OriginalPictureVideoGroupTransmission Group_picture_video_message = 1;</code>
   */
  public com.lanjiu.pro.file.OriginalPictureVideoGroupTransmissionOrBuilder getGroupPictureVideoMessageOrBuilder() {
    return getGroupPictureVideoMessage();
  }

  public static final int CHECKSUM_FIELD_NUMBER = 2;
  private volatile java.lang.Object checksum_;
  /**
   * <pre>
   *校验位
   * </pre>
   *
   * <code>string checksum = 2;</code>
   * @return The checksum.
   */
  public java.lang.String getChecksum() {
    java.lang.Object ref = checksum_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      checksum_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *校验位
   * </pre>
   *
   * <code>string checksum = 2;</code>
   * @return The bytes for checksum.
   */
  public com.google.protobuf.ByteString
      getChecksumBytes() {
    java.lang.Object ref = checksum_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      checksum_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (groupPictureVideoMessage_ != null) {
      output.writeMessage(1, getGroupPictureVideoMessage());
    }
    if (!getChecksumBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, checksum_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (groupPictureVideoMessage_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getGroupPictureVideoMessage());
    }
    if (!getChecksumBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, checksum_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.lanjiu.pro.file.GroupTransmissionRequest)) {
      return super.equals(obj);
    }
    com.lanjiu.pro.file.GroupTransmissionRequest other = (com.lanjiu.pro.file.GroupTransmissionRequest) obj;

    if (hasGroupPictureVideoMessage() != other.hasGroupPictureVideoMessage()) return false;
    if (hasGroupPictureVideoMessage()) {
      if (!getGroupPictureVideoMessage()
          .equals(other.getGroupPictureVideoMessage())) return false;
    }
    if (!getChecksum()
        .equals(other.getChecksum())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasGroupPictureVideoMessage()) {
      hash = (37 * hash) + GROUP_PICTURE_VIDEO_MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getGroupPictureVideoMessage().hashCode();
    }
    hash = (37 * hash) + CHECKSUM_FIELD_NUMBER;
    hash = (53 * hash) + getChecksum().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.lanjiu.pro.file.GroupTransmissionRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lanjiu.pro.file.GroupTransmissionRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lanjiu.pro.file.GroupTransmissionRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lanjiu.pro.file.GroupTransmissionRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lanjiu.pro.file.GroupTransmissionRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lanjiu.pro.file.GroupTransmissionRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lanjiu.pro.file.GroupTransmissionRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lanjiu.pro.file.GroupTransmissionRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lanjiu.pro.file.GroupTransmissionRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.lanjiu.pro.file.GroupTransmissionRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lanjiu.pro.file.GroupTransmissionRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lanjiu.pro.file.GroupTransmissionRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.lanjiu.pro.file.GroupTransmissionRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 群上传申请
   * </pre>
   *
   * Protobuf type {@code com.lanjiu.pro.file.GroupTransmissionRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.lanjiu.pro.file.GroupTransmissionRequest)
      com.lanjiu.pro.file.GroupTransmissionRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lanjiu.pro.file.FileTransmissionProto.internal_static_com_lanjiu_pro_file_GroupTransmissionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lanjiu.pro.file.FileTransmissionProto.internal_static_com_lanjiu_pro_file_GroupTransmissionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lanjiu.pro.file.GroupTransmissionRequest.class, com.lanjiu.pro.file.GroupTransmissionRequest.Builder.class);
    }

    // Construct using com.lanjiu.pro.file.GroupTransmissionRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (groupPictureVideoMessageBuilder_ == null) {
        groupPictureVideoMessage_ = null;
      } else {
        groupPictureVideoMessage_ = null;
        groupPictureVideoMessageBuilder_ = null;
      }
      checksum_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.lanjiu.pro.file.FileTransmissionProto.internal_static_com_lanjiu_pro_file_GroupTransmissionRequest_descriptor;
    }

    @java.lang.Override
    public com.lanjiu.pro.file.GroupTransmissionRequest getDefaultInstanceForType() {
      return com.lanjiu.pro.file.GroupTransmissionRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.lanjiu.pro.file.GroupTransmissionRequest build() {
      com.lanjiu.pro.file.GroupTransmissionRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.lanjiu.pro.file.GroupTransmissionRequest buildPartial() {
      com.lanjiu.pro.file.GroupTransmissionRequest result = new com.lanjiu.pro.file.GroupTransmissionRequest(this);
      if (groupPictureVideoMessageBuilder_ == null) {
        result.groupPictureVideoMessage_ = groupPictureVideoMessage_;
      } else {
        result.groupPictureVideoMessage_ = groupPictureVideoMessageBuilder_.build();
      }
      result.checksum_ = checksum_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.lanjiu.pro.file.GroupTransmissionRequest) {
        return mergeFrom((com.lanjiu.pro.file.GroupTransmissionRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.lanjiu.pro.file.GroupTransmissionRequest other) {
      if (other == com.lanjiu.pro.file.GroupTransmissionRequest.getDefaultInstance()) return this;
      if (other.hasGroupPictureVideoMessage()) {
        mergeGroupPictureVideoMessage(other.getGroupPictureVideoMessage());
      }
      if (!other.getChecksum().isEmpty()) {
        checksum_ = other.checksum_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.lanjiu.pro.file.GroupTransmissionRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.lanjiu.pro.file.GroupTransmissionRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.lanjiu.pro.file.OriginalPictureVideoGroupTransmission groupPictureVideoMessage_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.lanjiu.pro.file.OriginalPictureVideoGroupTransmission, com.lanjiu.pro.file.OriginalPictureVideoGroupTransmission.Builder, com.lanjiu.pro.file.OriginalPictureVideoGroupTransmissionOrBuilder> groupPictureVideoMessageBuilder_;
    /**
     * <code>.com.lanjiu.pro.file.OriginalPictureVideoGroupTransmission Group_picture_video_message = 1;</code>
     * @return Whether the groupPictureVideoMessage field is set.
     */
    public boolean hasGroupPictureVideoMessage() {
      return groupPictureVideoMessageBuilder_ != null || groupPictureVideoMessage_ != null;
    }
    /**
     * <code>.com.lanjiu.pro.file.OriginalPictureVideoGroupTransmission Group_picture_video_message = 1;</code>
     * @return The groupPictureVideoMessage.
     */
    public com.lanjiu.pro.file.OriginalPictureVideoGroupTransmission getGroupPictureVideoMessage() {
      if (groupPictureVideoMessageBuilder_ == null) {
        return groupPictureVideoMessage_ == null ? com.lanjiu.pro.file.OriginalPictureVideoGroupTransmission.getDefaultInstance() : groupPictureVideoMessage_;
      } else {
        return groupPictureVideoMessageBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.lanjiu.pro.file.OriginalPictureVideoGroupTransmission Group_picture_video_message = 1;</code>
     */
    public Builder setGroupPictureVideoMessage(com.lanjiu.pro.file.OriginalPictureVideoGroupTransmission value) {
      if (groupPictureVideoMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        groupPictureVideoMessage_ = value;
        onChanged();
      } else {
        groupPictureVideoMessageBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.lanjiu.pro.file.OriginalPictureVideoGroupTransmission Group_picture_video_message = 1;</code>
     */
    public Builder setGroupPictureVideoMessage(
        com.lanjiu.pro.file.OriginalPictureVideoGroupTransmission.Builder builderForValue) {
      if (groupPictureVideoMessageBuilder_ == null) {
        groupPictureVideoMessage_ = builderForValue.build();
        onChanged();
      } else {
        groupPictureVideoMessageBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.lanjiu.pro.file.OriginalPictureVideoGroupTransmission Group_picture_video_message = 1;</code>
     */
    public Builder mergeGroupPictureVideoMessage(com.lanjiu.pro.file.OriginalPictureVideoGroupTransmission value) {
      if (groupPictureVideoMessageBuilder_ == null) {
        if (groupPictureVideoMessage_ != null) {
          groupPictureVideoMessage_ =
            com.lanjiu.pro.file.OriginalPictureVideoGroupTransmission.newBuilder(groupPictureVideoMessage_).mergeFrom(value).buildPartial();
        } else {
          groupPictureVideoMessage_ = value;
        }
        onChanged();
      } else {
        groupPictureVideoMessageBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.lanjiu.pro.file.OriginalPictureVideoGroupTransmission Group_picture_video_message = 1;</code>
     */
    public Builder clearGroupPictureVideoMessage() {
      if (groupPictureVideoMessageBuilder_ == null) {
        groupPictureVideoMessage_ = null;
        onChanged();
      } else {
        groupPictureVideoMessage_ = null;
        groupPictureVideoMessageBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.lanjiu.pro.file.OriginalPictureVideoGroupTransmission Group_picture_video_message = 1;</code>
     */
    public com.lanjiu.pro.file.OriginalPictureVideoGroupTransmission.Builder getGroupPictureVideoMessageBuilder() {
      
      onChanged();
      return getGroupPictureVideoMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.lanjiu.pro.file.OriginalPictureVideoGroupTransmission Group_picture_video_message = 1;</code>
     */
    public com.lanjiu.pro.file.OriginalPictureVideoGroupTransmissionOrBuilder getGroupPictureVideoMessageOrBuilder() {
      if (groupPictureVideoMessageBuilder_ != null) {
        return groupPictureVideoMessageBuilder_.getMessageOrBuilder();
      } else {
        return groupPictureVideoMessage_ == null ?
            com.lanjiu.pro.file.OriginalPictureVideoGroupTransmission.getDefaultInstance() : groupPictureVideoMessage_;
      }
    }
    /**
     * <code>.com.lanjiu.pro.file.OriginalPictureVideoGroupTransmission Group_picture_video_message = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.lanjiu.pro.file.OriginalPictureVideoGroupTransmission, com.lanjiu.pro.file.OriginalPictureVideoGroupTransmission.Builder, com.lanjiu.pro.file.OriginalPictureVideoGroupTransmissionOrBuilder> 
        getGroupPictureVideoMessageFieldBuilder() {
      if (groupPictureVideoMessageBuilder_ == null) {
        groupPictureVideoMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.lanjiu.pro.file.OriginalPictureVideoGroupTransmission, com.lanjiu.pro.file.OriginalPictureVideoGroupTransmission.Builder, com.lanjiu.pro.file.OriginalPictureVideoGroupTransmissionOrBuilder>(
                getGroupPictureVideoMessage(),
                getParentForChildren(),
                isClean());
        groupPictureVideoMessage_ = null;
      }
      return groupPictureVideoMessageBuilder_;
    }

    private java.lang.Object checksum_ = "";
    /**
     * <pre>
     *校验位
     * </pre>
     *
     * <code>string checksum = 2;</code>
     * @return The checksum.
     */
    public java.lang.String getChecksum() {
      java.lang.Object ref = checksum_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        checksum_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *校验位
     * </pre>
     *
     * <code>string checksum = 2;</code>
     * @return The bytes for checksum.
     */
    public com.google.protobuf.ByteString
        getChecksumBytes() {
      java.lang.Object ref = checksum_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        checksum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *校验位
     * </pre>
     *
     * <code>string checksum = 2;</code>
     * @param value The checksum to set.
     * @return This builder for chaining.
     */
    public Builder setChecksum(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      checksum_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *校验位
     * </pre>
     *
     * <code>string checksum = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearChecksum() {
      
      checksum_ = getDefaultInstance().getChecksum();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *校验位
     * </pre>
     *
     * <code>string checksum = 2;</code>
     * @param value The bytes for checksum to set.
     * @return This builder for chaining.
     */
    public Builder setChecksumBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      checksum_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.lanjiu.pro.file.GroupTransmissionRequest)
  }

  // @@protoc_insertion_point(class_scope:com.lanjiu.pro.file.GroupTransmissionRequest)
  private static final com.lanjiu.pro.file.GroupTransmissionRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.lanjiu.pro.file.GroupTransmissionRequest();
  }

  public static com.lanjiu.pro.file.GroupTransmissionRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GroupTransmissionRequest>
      PARSER = new com.google.protobuf.AbstractParser<GroupTransmissionRequest>() {
    @java.lang.Override
    public GroupTransmissionRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GroupTransmissionRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GroupTransmissionRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GroupTransmissionRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.lanjiu.pro.file.GroupTransmissionRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

