// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file_transfer_communication_grpc.proto

package com.lanjiu.pro.file;

public interface PictureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.lanjiu.pro.file.Picture)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 原图下载URL
   * </pre>
   *
   * <code>string url = 1;</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <pre>
   * 原图下载URL
   * </pre>
   *
   * <code>string url = 1;</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <pre>
   * 原始图
   * </pre>
   *
   * <code>bytes origin_picture = 2;</code>
   * @return The originPicture.
   */
  com.google.protobuf.ByteString getOriginPicture();

  /**
   * <pre>
   *缩略图
   * </pre>
   *
   * <code>bytes thumbnail = 3;</code>
   * @return The thumbnail.
   */
  com.google.protobuf.ByteString getThumbnail();

  /**
   * <pre>
   *当前坐标
   * </pre>
   *
   * <code>int32 pos = 4;</code>
   * @return The pos.
   */
  int getPos();

  /**
   * <pre>
   *当前文件内容大小
   * </pre>
   *
   * <code>int32 length = 5;</code>
   * @return The length.
   */
  int getLength();

  /**
   * <pre>
   *好友结构体
   * </pre>
   *
   * <code>.com.lanjiu.pro.file.Friends friends = 6;</code>
   * @return Whether the friends field is set.
   */
  boolean hasFriends();
  /**
   * <pre>
   *好友结构体
   * </pre>
   *
   * <code>.com.lanjiu.pro.file.Friends friends = 6;</code>
   * @return The friends.
   */
  com.lanjiu.pro.file.Friends getFriends();
  /**
   * <pre>
   *好友结构体
   * </pre>
   *
   * <code>.com.lanjiu.pro.file.Friends friends = 6;</code>
   */
  com.lanjiu.pro.file.FriendsOrBuilder getFriendsOrBuilder();

  /**
   * <code>.com.lanjiu.pro.file.GroupMember groupMember = 7;</code>
   * @return Whether the groupMember field is set.
   */
  boolean hasGroupMember();
  /**
   * <code>.com.lanjiu.pro.file.GroupMember groupMember = 7;</code>
   * @return The groupMember.
   */
  com.lanjiu.pro.file.GroupMember getGroupMember();
  /**
   * <code>.com.lanjiu.pro.file.GroupMember groupMember = 7;</code>
   */
  com.lanjiu.pro.file.GroupMemberOrBuilder getGroupMemberOrBuilder();
}
