// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file_transfer_communication_grpc.proto

package com.lanjiu.pro.file;

public final class FileTransmissionProto {
  private FileTransmissionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_pro_file_FriendsTransmissionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_pro_file_FriendsTransmissionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_pro_file_FriendsTransmissionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_pro_file_FriendsTransmissionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_pro_file_GroupTransmissionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_pro_file_GroupTransmissionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_pro_file_GroupTransmissionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_pro_file_GroupTransmissionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_pro_file_OriginalPictureVideoFriendsTransmission_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_pro_file_OriginalPictureVideoFriendsTransmission_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_pro_file_OriginalPictureVideoGroupTransmission_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_pro_file_OriginalPictureVideoGroupTransmission_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_pro_file_FileContent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_pro_file_FileContent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_pro_file_BigFileHead_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_pro_file_BigFileHead_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_pro_file_BigFileFragment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_pro_file_BigFileFragment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_pro_file_BigFileFoot_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_pro_file_BigFileFoot_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_pro_file_RegisteredUser_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_pro_file_RegisteredUser_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_pro_file_Tourists_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_pro_file_Tourists_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_pro_file_Friends_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_pro_file_Friends_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_pro_file_GroupMember_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_pro_file_GroupMember_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_pro_file_Group_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_pro_file_Group_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_pro_file_Picture_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_pro_file_Picture_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_pro_file_Video_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_pro_file_Video_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_pro_file_Voice_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_pro_file_Voice_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_pro_file_Expression_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_pro_file_Expression_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_pro_file_Head_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_pro_file_Head_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&file_transfer_communication_grpc.proto" +
      "\022\023com.lanjiu.pro.file\"\223\001\n\032FriendsTransmi" +
      "ssionRequest\022c\n\035friends_picture_video_me" +
      "ssage\030\001 \001(\0132<.com.lanjiu.pro.file.Origin" +
      "alPictureVideoFriendsTransmission\022\020\n\010che" +
      "cksum\030\002 \001(\t\"\224\001\n\033FriendsTransmissionRespo" +
      "nse\022c\n\035friends_picture_video_message\030\001 \001" +
      "(\0132<.com.lanjiu.pro.file.OriginalPicture" +
      "VideoFriendsTransmission\022\020\n\010checksum\030\002 \001" +
      "(\t\"\215\001\n\030GroupTransmissionRequest\022_\n\033Group" +
      "_picture_video_message\030\001 \001(\0132:.com.lanji" +
      "u.pro.file.OriginalPictureVideoGroupTran" +
      "smission\022\020\n\010checksum\030\002 \001(\t\"\216\001\n\031GroupTran" +
      "smissionResponse\022_\n\033Group_picture_video_" +
      "message\030\001 \001(\0132:.com.lanjiu.pro.file.Orig" +
      "inalPictureVideoGroupTransmission\022\020\n\010che" +
      "cksum\030\002 \001(\t\"\303\003\n\'OriginalPictureVideoFrie" +
      "ndsTransmission\022\021\n\tuser_type\030\001 \001(\t\022\025\n\rse" +
      "ttings_type\030\002 \001(\t\022-\n\007picture\030\003 \001(\0132\034.com" +
      ".lanjiu.pro.file.Picture\022)\n\005video\030\004 \001(\0132" +
      "\032.com.lanjiu.pro.file.Video\0226\n\014file_cont" +
      "ent\030\005 \001(\0132 .com.lanjiu.pro.file.FileCont" +
      "ent\022-\n\007friends\030\006 \001(\0132\034.com.lanjiu.pro.fi" +
      "le.Friends\022/\n\010tourists\030\007 \001(\0132\035.com.lanji" +
      "u.pro.file.Tourists\022<\n\017registered_user\030\010" +
      " \001(\0132#.com.lanjiu.pro.file.RegisteredUse" +
      "r\022\025\n\rstatus_detail\030\t \001(\t\022\'\n\004head\030\n \001(\0132\031" +
      ".com.lanjiu.pro.file.Head\"\364\003\n%OriginalPi" +
      "ctureVideoGroupTransmission\022\021\n\tuser_type" +
      "\030\001 \001(\t\022\025\n\rsettings_type\030\002 \001(\t\022-\n\007picture" +
      "\030\003 \001(\0132\034.com.lanjiu.pro.file.Picture\022)\n\005" +
      "video\030\004 \001(\0132\032.com.lanjiu.pro.file.Video\022" +
      "6\n\014file_content\030\005 \001(\0132 .com.lanjiu.pro.f" +
      "ile.FileContent\0225\n\013GroupMember\030\006 \001(\0132 .c" +
      "om.lanjiu.pro.file.GroupMember\022)\n\005group\030" +
      "\007 \001(\0132\032.com.lanjiu.pro.file.Group\022/\n\010tou" +
      "rists\030\010 \001(\0132\035.com.lanjiu.pro.file.Touris" +
      "ts\022<\n\017registered_user\030\t \001(\0132#.com.lanjiu" +
      ".pro.file.RegisteredUser\022\025\n\rstatus_detai" +
      "l\030\n \001(\t\022\'\n\004head\030\013 \001(\0132\031.com.lanjiu.pro.f" +
      "ile.Head\"\326\001\n\013FileContent\0227\n\rbig_file_hea" +
      "d\030\001 \001(\0132 .com.lanjiu.pro.file.BigFileHea" +
      "d\022?\n\021big_file_fragment\030\002 \001(\0132$.com.lanji" +
      "u.pro.file.BigFileFragment\0227\n\rbig_file_f" +
      "oot\030\003 \001(\0132 .com.lanjiu.pro.file.BigFileF" +
      "oot\022\024\n\014package_kind\030\004 \001(\t\"T\n\013BigFileHead" +
      "\022\r\n\005count\030\001 \001(\005\022\016\n\006length\030\002 \001(\003\022\022\n\nserve" +
      "r_url\030\003 \001(\t\022\022\n\nclient_url\030\004 \001(\t\"A\n\017BigFi" +
      "leFragment\022\016\n\006length\030\001 \001(\003\022\014\n\004data\030\002 \001(\014" +
      "\022\020\n\010position\030\003 \001(\003\" \n\013BigFileFoot\022\021\n\tisS" +
      "uccess\030\001 \001(\010\"k\n\016RegisteredUser\022\017\n\007user_i" +
      "d\030\001 \001(\t\022\016\n\006secret\030\002 \001(\t\022\020\n\010nickname\030\003 \001(" +
      "\t\022\022\n\nuser_phone\030\004 \001(\t\022\022\n\nip_address\030\005 \001(" +
      "\t\"V\n\010Tourists\022\024\n\014temporary_id\030\001 \001(\t\022\022\n\ni" +
      "p_address\030\002 \001(\t\022\023\n\013mac_address\030\003 \001(\t\022\013\n\003" +
      "ime\030\004 \001(\t\"\245\002\n\007Friends\022\022\n\nfriends_id\030\001 \001(" +
      "\t\022\030\n\020friends_nickname\030\002 \001(\t\022\031\n\021friends_u" +
      "ser_type\030\003 \001(\t\022\037\n\027friends_offline_messag" +
      "e\030\004 \001(\t\022\"\n\032friends_burn_after_reading\030\005 " +
      "\001(\t\022\035\n\025friends_online_status\030\006 \001(\t\022/\n\010to" +
      "urists\030\007 \001(\0132\035.com.lanjiu.pro.file.Touri" +
      "sts\022<\n\017registered_user\030\010 \001(\0132#.com.lanji" +
      "u.pro.file.RegisteredUser\"\372\001\n\013GroupMembe" +
      "r\022\027\n\017group_member_id\030\001 \001(\t\022\035\n\025group_memb" +
      "er_nickname\030\002 \001(\t\022\031\n\021group_member_type\030\003" +
      " \001(\t\022/\n\010tourists\030\004 \001(\0132\035.com.lanjiu.pro." +
      "file.Tourists\022<\n\017registered_user\030\005 \001(\0132#" +
      ".com.lanjiu.pro.file.RegisteredUser\022)\n\005g" +
      "roup\030\006 \001(\0132\032.com.lanjiu.pro.file.Group\"]" +
      "\n\005Group\022\020\n\010group_id\030\001 \001(\t\022\026\n\016group_nickn" +
      "ame\030\002 \001(\t\022\022\n\ngroup_type\030\003 \001(\t\022\026\n\016group_q" +
      "uantity\030\004 \001(\005\"\304\001\n\007Picture\022\013\n\003url\030\001 \001(\t\022\026" +
      "\n\016origin_picture\030\002 \001(\014\022\021\n\tthumbnail\030\003 \001(" +
      "\014\022\013\n\003pos\030\004 \001(\005\022\016\n\006length\030\005 \001(\005\022-\n\007friend" +
      "s\030\006 \001(\0132\034.com.lanjiu.pro.file.Friends\0225\n" +
      "\013groupMember\030\007 \001(\0132 .com.lanjiu.pro.file" +
      ".GroupMember\"\300\001\n\005Video\022\013\n\003url\030\001 \001(\t\022\024\n\014o" +
      "rigin_video\030\002 \001(\014\022\013\n\003pos\030\003 \001(\005\022\016\n\006length" +
      "\030\004 \001(\005\022\021\n\tthumbnail\030\005 \001(\014\022-\n\007friends\030\006 \001" +
      "(\0132\034.com.lanjiu.pro.file.Friends\0225\n\013grou" +
      "pMember\030\007 \001(\0132 .com.lanjiu.pro.file.Grou" +
      "pMember\"\257\001\n\005Voice\022\022\n\nall_length\030\001 \001(\t\022\017\n" +
      "\007content\030\002 \001(\014\022\013\n\003pos\030\003 \001(\005\022\016\n\006length\030\004 " +
      "\001(\005\022-\n\007friends\030\005 \001(\0132\034.com.lanjiu.pro.fi" +
      "le.Friends\0225\n\013groupMember\030\006 \001(\0132 .com.la" +
      "njiu.pro.file.GroupMember\"\211\001\n\nExpression" +
      "\022\025\n\rexpression_id\030\001 \001(\t\022-\n\007friends\030\002 \001(\013" +
      "2\034.com.lanjiu.pro.file.Friends\0225\n\013groupM" +
      "ember\030\003 \001(\0132 .com.lanjiu.pro.file.GroupM" +
      "ember\"\224\001\n\004Head\022\r\n\005msgId\030\001 \001(\t\022\017\n\007msgType" +
      "\030\002 \001(\005\022\026\n\016msgContentType\030\003 \001(\005\022\016\n\006fromId" +
      "\030\004 \001(\t\022\014\n\004toId\030\005 \001(\t\022\021\n\ttimestamp\030\006 \001(\003\022" +
      "\r\n\005token\030\007 \001(\t\022\024\n\014statusReport\030\010 \001(\t2\345\006\n" +
      "\027FileTransmissionService\022\210\001\n!OriginalFri" +
      "endsTransmissionUpload\022/.com.lanjiu.pro." +
      "file.FriendsTransmissionRequest\0320.com.la" +
      "njiu.pro.file.FriendsTransmissionRespons" +
      "e\"\000\022\212\001\n#OriginalFriendsTransmissionDownl" +
      "oad\022/.com.lanjiu.pro.file.FriendsTransmi" +
      "ssionRequest\0320.com.lanjiu.pro.file.Frien" +
      "dsTransmissionResponse\"\000\022\202\001\n\037OriginalGro" +
      "upTransmissionUpload\022-.com.lanjiu.pro.fi" +
      "le.GroupTransmissionRequest\032..com.lanjiu" +
      ".pro.file.GroupTransmissionResponse\"\000\022\204\001" +
      "\n!OriginalGroupTransmissionDownload\022-.co" +
      "m.lanjiu.pro.file.GroupTransmissionReque" +
      "st\032..com.lanjiu.pro.file.GroupTransmissi" +
      "onResponse\"\000\022\216\001\n+GroupTransmissionFileDe" +
      "leteForStorageServer\022-.com.lanjiu.pro.fi" +
      "le.GroupTransmissionRequest\032..com.lanjiu" +
      ".pro.file.GroupTransmissionResponse\"\000\022\224\001" +
      "\n-FriendsTransmissionFileDeleteForStorag" +
      "eServer\022/.com.lanjiu.pro.file.FriendsTra" +
      "nsmissionRequest\0320.com.lanjiu.pro.file.F" +
      "riendsTransmissionResponse\"\000B0\n\023com.lanj" +
      "iu.pro.fileB\025FileTransmissionProtoH\001P\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_lanjiu_pro_file_FriendsTransmissionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_lanjiu_pro_file_FriendsTransmissionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_pro_file_FriendsTransmissionRequest_descriptor,
        new java.lang.String[] { "FriendsPictureVideoMessage", "Checksum", });
    internal_static_com_lanjiu_pro_file_FriendsTransmissionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_lanjiu_pro_file_FriendsTransmissionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_pro_file_FriendsTransmissionResponse_descriptor,
        new java.lang.String[] { "FriendsPictureVideoMessage", "Checksum", });
    internal_static_com_lanjiu_pro_file_GroupTransmissionRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_lanjiu_pro_file_GroupTransmissionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_pro_file_GroupTransmissionRequest_descriptor,
        new java.lang.String[] { "GroupPictureVideoMessage", "Checksum", });
    internal_static_com_lanjiu_pro_file_GroupTransmissionResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_lanjiu_pro_file_GroupTransmissionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_pro_file_GroupTransmissionResponse_descriptor,
        new java.lang.String[] { "GroupPictureVideoMessage", "Checksum", });
    internal_static_com_lanjiu_pro_file_OriginalPictureVideoFriendsTransmission_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_lanjiu_pro_file_OriginalPictureVideoFriendsTransmission_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_pro_file_OriginalPictureVideoFriendsTransmission_descriptor,
        new java.lang.String[] { "UserType", "SettingsType", "Picture", "Video", "FileContent", "Friends", "Tourists", "RegisteredUser", "StatusDetail", "Head", });
    internal_static_com_lanjiu_pro_file_OriginalPictureVideoGroupTransmission_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_lanjiu_pro_file_OriginalPictureVideoGroupTransmission_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_pro_file_OriginalPictureVideoGroupTransmission_descriptor,
        new java.lang.String[] { "UserType", "SettingsType", "Picture", "Video", "FileContent", "GroupMember", "Group", "Tourists", "RegisteredUser", "StatusDetail", "Head", });
    internal_static_com_lanjiu_pro_file_FileContent_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_lanjiu_pro_file_FileContent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_pro_file_FileContent_descriptor,
        new java.lang.String[] { "BigFileHead", "BigFileFragment", "BigFileFoot", "PackageKind", });
    internal_static_com_lanjiu_pro_file_BigFileHead_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_lanjiu_pro_file_BigFileHead_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_pro_file_BigFileHead_descriptor,
        new java.lang.String[] { "Count", "Length", "ServerUrl", "ClientUrl", });
    internal_static_com_lanjiu_pro_file_BigFileFragment_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_lanjiu_pro_file_BigFileFragment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_pro_file_BigFileFragment_descriptor,
        new java.lang.String[] { "Length", "Data", "Position", });
    internal_static_com_lanjiu_pro_file_BigFileFoot_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_lanjiu_pro_file_BigFileFoot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_pro_file_BigFileFoot_descriptor,
        new java.lang.String[] { "IsSuccess", });
    internal_static_com_lanjiu_pro_file_RegisteredUser_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_lanjiu_pro_file_RegisteredUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_pro_file_RegisteredUser_descriptor,
        new java.lang.String[] { "UserId", "Secret", "Nickname", "UserPhone", "IpAddress", });
    internal_static_com_lanjiu_pro_file_Tourists_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_lanjiu_pro_file_Tourists_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_pro_file_Tourists_descriptor,
        new java.lang.String[] { "TemporaryId", "IpAddress", "MacAddress", "Ime", });
    internal_static_com_lanjiu_pro_file_Friends_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_com_lanjiu_pro_file_Friends_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_pro_file_Friends_descriptor,
        new java.lang.String[] { "FriendsId", "FriendsNickname", "FriendsUserType", "FriendsOfflineMessage", "FriendsBurnAfterReading", "FriendsOnlineStatus", "Tourists", "RegisteredUser", });
    internal_static_com_lanjiu_pro_file_GroupMember_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_com_lanjiu_pro_file_GroupMember_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_pro_file_GroupMember_descriptor,
        new java.lang.String[] { "GroupMemberId", "GroupMemberNickname", "GroupMemberType", "Tourists", "RegisteredUser", "Group", });
    internal_static_com_lanjiu_pro_file_Group_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_com_lanjiu_pro_file_Group_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_pro_file_Group_descriptor,
        new java.lang.String[] { "GroupId", "GroupNickname", "GroupType", "GroupQuantity", });
    internal_static_com_lanjiu_pro_file_Picture_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_com_lanjiu_pro_file_Picture_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_pro_file_Picture_descriptor,
        new java.lang.String[] { "Url", "OriginPicture", "Thumbnail", "Pos", "Length", "Friends", "GroupMember", });
    internal_static_com_lanjiu_pro_file_Video_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_com_lanjiu_pro_file_Video_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_pro_file_Video_descriptor,
        new java.lang.String[] { "Url", "OriginVideo", "Pos", "Length", "Thumbnail", "Friends", "GroupMember", });
    internal_static_com_lanjiu_pro_file_Voice_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_com_lanjiu_pro_file_Voice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_pro_file_Voice_descriptor,
        new java.lang.String[] { "AllLength", "Content", "Pos", "Length", "Friends", "GroupMember", });
    internal_static_com_lanjiu_pro_file_Expression_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_com_lanjiu_pro_file_Expression_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_pro_file_Expression_descriptor,
        new java.lang.String[] { "ExpressionId", "Friends", "GroupMember", });
    internal_static_com_lanjiu_pro_file_Head_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_com_lanjiu_pro_file_Head_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_pro_file_Head_descriptor,
        new java.lang.String[] { "MsgId", "MsgType", "MsgContentType", "FromId", "ToId", "Timestamp", "Token", "StatusReport", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
