// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file_transfer_communication_grpc.proto

package com.lanjiu.pro.file;

public interface GroupMemberOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.lanjiu.pro.file.GroupMember)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 群成员ID
   * </pre>
   *
   * <code>string group_member_id = 1;</code>
   * @return The groupMemberId.
   */
  java.lang.String getGroupMemberId();
  /**
   * <pre>
   * 群成员ID
   * </pre>
   *
   * <code>string group_member_id = 1;</code>
   * @return The bytes for groupMemberId.
   */
  com.google.protobuf.ByteString
      getGroupMemberIdBytes();

  /**
   * <pre>
   * 群成员昵称
   * </pre>
   *
   * <code>string group_member_nickname = 2;</code>
   * @return The groupMemberNickname.
   */
  java.lang.String getGroupMemberNickname();
  /**
   * <pre>
   * 群成员昵称
   * </pre>
   *
   * <code>string group_member_nickname = 2;</code>
   * @return The bytes for groupMemberNickname.
   */
  com.google.protobuf.ByteString
      getGroupMemberNicknameBytes();

  /**
   * <pre>
   *群成员类型 (游客,注册用户)
   * </pre>
   *
   * <code>string group_member_type = 3;</code>
   * @return The groupMemberType.
   */
  java.lang.String getGroupMemberType();
  /**
   * <pre>
   *群成员类型 (游客,注册用户)
   * </pre>
   *
   * <code>string group_member_type = 3;</code>
   * @return The bytes for groupMemberType.
   */
  com.google.protobuf.ByteString
      getGroupMemberTypeBytes();

  /**
   * <pre>
   *兼容游客类型成员
   * </pre>
   *
   * <code>.com.lanjiu.pro.file.Tourists tourists = 4;</code>
   * @return Whether the tourists field is set.
   */
  boolean hasTourists();
  /**
   * <pre>
   *兼容游客类型成员
   * </pre>
   *
   * <code>.com.lanjiu.pro.file.Tourists tourists = 4;</code>
   * @return The tourists.
   */
  com.lanjiu.pro.file.Tourists getTourists();
  /**
   * <pre>
   *兼容游客类型成员
   * </pre>
   *
   * <code>.com.lanjiu.pro.file.Tourists tourists = 4;</code>
   */
  com.lanjiu.pro.file.TouristsOrBuilder getTouristsOrBuilder();

  /**
   * <pre>
   *兼容注册用户类型成员
   * </pre>
   *
   * <code>.com.lanjiu.pro.file.RegisteredUser registered_user = 5;</code>
   * @return Whether the registeredUser field is set.
   */
  boolean hasRegisteredUser();
  /**
   * <pre>
   *兼容注册用户类型成员
   * </pre>
   *
   * <code>.com.lanjiu.pro.file.RegisteredUser registered_user = 5;</code>
   * @return The registeredUser.
   */
  com.lanjiu.pro.file.RegisteredUser getRegisteredUser();
  /**
   * <pre>
   *兼容注册用户类型成员
   * </pre>
   *
   * <code>.com.lanjiu.pro.file.RegisteredUser registered_user = 5;</code>
   */
  com.lanjiu.pro.file.RegisteredUserOrBuilder getRegisteredUserOrBuilder();

  /**
   * <pre>
   *兼容群类型成员
   * </pre>
   *
   * <code>.com.lanjiu.pro.file.Group group = 6;</code>
   * @return Whether the group field is set.
   */
  boolean hasGroup();
  /**
   * <pre>
   *兼容群类型成员
   * </pre>
   *
   * <code>.com.lanjiu.pro.file.Group group = 6;</code>
   * @return The group.
   */
  com.lanjiu.pro.file.Group getGroup();
  /**
   * <pre>
   *兼容群类型成员
   * </pre>
   *
   * <code>.com.lanjiu.pro.file.Group group = 6;</code>
   */
  com.lanjiu.pro.file.GroupOrBuilder getGroupOrBuilder();
}
