// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: information_other_storage_grpc.proto

package com.lanjiu.im.grpc;

public final class FileStorageProto {
  private FileStorageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_FriendsTransmissionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_FriendsTransmissionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_FriendsTransmissionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_FriendsTransmissionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_GroupTransmissionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_GroupTransmissionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_GroupTransmissionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_GroupTransmissionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_OriginalPictureVideoFriendsTransmission_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_OriginalPictureVideoFriendsTransmission_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_OriginalPictureVideoGroupTransmission_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_OriginalPictureVideoGroupTransmission_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_FileContent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_FileContent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_BigFileHead_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_BigFileHead_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_BigFileFragment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_BigFileFragment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_BigFileFoot_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_BigFileFoot_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_RegisteredUser_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_RegisteredUser_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_Tourists_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_Tourists_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_Friends_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_Friends_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_GroupMember_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_GroupMember_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_Group_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_Group_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_Picture_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_Picture_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_Video_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_Video_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_Voice_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_Voice_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_Expression_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_Expression_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanjiu_im_grpc_Head_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanjiu_im_grpc_Head_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$information_other_storage_grpc.proto\022\022" +
      "com.lanjiu.im.grpc\"\222\001\n\032FriendsTransmissi" +
      "onRequest\022b\n\035friends_picture_video_messa" +
      "ge\030\001 \001(\0132;.com.lanjiu.im.grpc.OriginalPi" +
      "ctureVideoFriendsTransmission\022\020\n\010checksu" +
      "m\030\002 \001(\t\"\223\001\n\033FriendsTransmissionResponse\022" +
      "b\n\035friends_picture_video_message\030\001 \001(\0132;" +
      ".com.lanjiu.im.grpc.OriginalPictureVideo" +
      "FriendsTransmission\022\020\n\010checksum\030\002 \001(\t\"\214\001" +
      "\n\030GroupTransmissionRequest\022^\n\033Group_pict" +
      "ure_video_message\030\001 \001(\01329.com.lanjiu.im." +
      "grpc.OriginalPictureVideoGroupTransmissi" +
      "on\022\020\n\010checksum\030\002 \001(\t\"\215\001\n\031GroupTransmissi" +
      "onResponse\022^\n\033Group_picture_video_messag" +
      "e\030\001 \001(\01329.com.lanjiu.im.grpc.OriginalPic" +
      "tureVideoGroupTransmission\022\020\n\010checksum\030\002" +
      " \001(\t\"\274\003\n\'OriginalPictureVideoFriendsTran" +
      "smission\022\021\n\tuser_type\030\001 \001(\t\022\025\n\rsettings_" +
      "type\030\002 \001(\t\022,\n\007picture\030\003 \001(\0132\033.com.lanjiu" +
      ".im.grpc.Picture\022(\n\005video\030\004 \001(\0132\031.com.la" +
      "njiu.im.grpc.Video\0225\n\014file_content\030\005 \001(\013" +
      "2\037.com.lanjiu.im.grpc.FileContent\022,\n\007fri" +
      "ends\030\006 \001(\0132\033.com.lanjiu.im.grpc.Friends\022" +
      ".\n\010tourists\030\007 \001(\0132\034.com.lanjiu.im.grpc.T" +
      "ourists\022;\n\017registered_user\030\010 \001(\0132\".com.l" +
      "anjiu.im.grpc.RegisteredUser\022\025\n\rstatus_d" +
      "etail\030\t \001(\t\022&\n\004head\030\n \001(\0132\030.com.lanjiu.i" +
      "m.grpc.Head\"\354\003\n%OriginalPictureVideoGrou" +
      "pTransmission\022\021\n\tuser_type\030\001 \001(\t\022\025\n\rsett" +
      "ings_type\030\002 \001(\t\022,\n\007picture\030\003 \001(\0132\033.com.l" +
      "anjiu.im.grpc.Picture\022(\n\005video\030\004 \001(\0132\031.c" +
      "om.lanjiu.im.grpc.Video\0225\n\014file_content\030" +
      "\005 \001(\0132\037.com.lanjiu.im.grpc.FileContent\0224" +
      "\n\013GroupMember\030\006 \001(\0132\037.com.lanjiu.im.grpc" +
      ".GroupMember\022(\n\005group\030\007 \001(\0132\031.com.lanjiu" +
      ".im.grpc.Group\022.\n\010tourists\030\010 \001(\0132\034.com.l" +
      "anjiu.im.grpc.Tourists\022;\n\017registered_use" +
      "r\030\t \001(\0132\".com.lanjiu.im.grpc.RegisteredU" +
      "ser\022\025\n\rstatus_detail\030\n \001(\t\022&\n\004head\030\013 \001(\013" +
      "2\030.com.lanjiu.im.grpc.Head\"\323\001\n\013FileConte" +
      "nt\0226\n\rbig_file_head\030\001 \001(\0132\037.com.lanjiu.i" +
      "m.grpc.BigFileHead\022>\n\021big_file_fragment\030" +
      "\002 \001(\0132#.com.lanjiu.im.grpc.BigFileFragme" +
      "nt\0226\n\rbig_file_foot\030\003 \001(\0132\037.com.lanjiu.i" +
      "m.grpc.BigFileFoot\022\024\n\014package_kind\030\004 \001(\t" +
      "\"T\n\013BigFileHead\022\r\n\005count\030\001 \001(\005\022\016\n\006length" +
      "\030\002 \001(\003\022\022\n\nserver_url\030\003 \001(\t\022\022\n\nclient_url" +
      "\030\004 \001(\t\"A\n\017BigFileFragment\022\016\n\006length\030\001 \001(" +
      "\003\022\014\n\004data\030\002 \001(\014\022\020\n\010position\030\003 \001(\003\" \n\013Big" +
      "FileFoot\022\021\n\tisSuccess\030\001 \001(\010\"k\n\016Registere" +
      "dUser\022\017\n\007user_id\030\001 \001(\t\022\016\n\006secret\030\002 \001(\t\022\020" +
      "\n\010nickname\030\003 \001(\t\022\022\n\nuser_phone\030\004 \001(\t\022\022\n\n" +
      "ip_address\030\005 \001(\t\"V\n\010Tourists\022\024\n\014temporar" +
      "y_id\030\001 \001(\t\022\022\n\nip_address\030\002 \001(\t\022\023\n\013mac_ad" +
      "dress\030\003 \001(\t\022\013\n\003ime\030\004 \001(\t\"\243\002\n\007Friends\022\022\n\n" +
      "friends_id\030\001 \001(\t\022\030\n\020friends_nickname\030\002 \001" +
      "(\t\022\031\n\021friends_user_type\030\003 \001(\t\022\037\n\027friends" +
      "_offline_message\030\004 \001(\t\022\"\n\032friends_burn_a" +
      "fter_reading\030\005 \001(\t\022\035\n\025friends_online_sta" +
      "tus\030\006 \001(\t\022.\n\010tourists\030\007 \001(\0132\034.com.lanjiu" +
      ".im.grpc.Tourists\022;\n\017registered_user\030\010 \001" +
      "(\0132\".com.lanjiu.im.grpc.RegisteredUser\"\367" +
      "\001\n\013GroupMember\022\027\n\017group_member_id\030\001 \001(\t\022" +
      "\035\n\025group_member_nickname\030\002 \001(\t\022\031\n\021group_" +
      "member_type\030\003 \001(\t\022.\n\010tourists\030\004 \001(\0132\034.co" +
      "m.lanjiu.im.grpc.Tourists\022;\n\017registered_" +
      "user\030\005 \001(\0132\".com.lanjiu.im.grpc.Register" +
      "edUser\022(\n\005group\030\006 \001(\0132\031.com.lanjiu.im.gr" +
      "pc.Group\"]\n\005Group\022\020\n\010group_id\030\001 \001(\t\022\026\n\016g" +
      "roup_nickname\030\002 \001(\t\022\022\n\ngroup_type\030\003 \001(\t\022" +
      "\026\n\016group_quantity\030\004 \001(\005\"\302\001\n\007Picture\022\013\n\003u" +
      "rl\030\001 \001(\t\022\026\n\016origin_picture\030\002 \001(\014\022\021\n\tthum" +
      "bnail\030\003 \001(\014\022\013\n\003pos\030\004 \001(\005\022\016\n\006length\030\005 \001(\005" +
      "\022,\n\007friends\030\006 \001(\0132\033.com.lanjiu.im.grpc.F" +
      "riends\0224\n\013groupMember\030\007 \001(\0132\037.com.lanjiu" +
      ".im.grpc.GroupMember\"\276\001\n\005Video\022\013\n\003url\030\001 " +
      "\001(\t\022\024\n\014origin_video\030\002 \001(\014\022\013\n\003pos\030\003 \001(\005\022\016" +
      "\n\006length\030\004 \001(\005\022\021\n\tthumbnail\030\005 \001(\014\022,\n\007fri" +
      "ends\030\006 \001(\0132\033.com.lanjiu.im.grpc.Friends\022" +
      "4\n\013groupMember\030\007 \001(\0132\037.com.lanjiu.im.grp" +
      "c.GroupMember\"\255\001\n\005Voice\022\022\n\nall_length\030\001 " +
      "\001(\t\022\017\n\007content\030\002 \001(\014\022\013\n\003pos\030\003 \001(\005\022\016\n\006len" +
      "gth\030\004 \001(\005\022,\n\007friends\030\005 \001(\0132\033.com.lanjiu." +
      "im.grpc.Friends\0224\n\013groupMember\030\006 \001(\0132\037.c" +
      "om.lanjiu.im.grpc.GroupMember\"\207\001\n\nExpres" +
      "sion\022\025\n\rexpression_id\030\001 \001(\t\022,\n\007friends\030\002" +
      " \001(\0132\033.com.lanjiu.im.grpc.Friends\0224\n\013gro" +
      "upMember\030\003 \001(\0132\037.com.lanjiu.im.grpc.Grou" +
      "pMember\"\224\001\n\004Head\022\r\n\005msgId\030\001 \001(\t\022\017\n\007msgTy" +
      "pe\030\002 \001(\005\022\026\n\016msgContentType\030\003 \001(\005\022\016\n\006from" +
      "Id\030\004 \001(\t\022\014\n\004toId\030\005 \001(\t\022\021\n\ttimestamp\030\006 \001(" +
      "\003\022\r\n\005token\030\007 \001(\t\022\024\n\014statusReport\030\010 \001(\t2\270" +
      "\005\n\022FileStorageService\022\205\001\n storageFileInf" +
      "ormationWithFriend\022..com.lanjiu.im.grpc." +
      "FriendsTransmissionRequest\032/.com.lanjiu." +
      "im.grpc.FriendsTransmissionResponse\"\000\022\200\001" +
      "\n\037storageFileInformationWithGroup\022,.com." +
      "lanjiu.im.grpc.GroupTransmissionRequest\032" +
      "-.com.lanjiu.im.grpc.GroupTransmissionRe" +
      "sponse\"\000\022\204\001\n\037deleteFileInformationWithFr" +
      "iend\022..com.lanjiu.im.grpc.FriendsTransmi" +
      "ssionRequest\032/.com.lanjiu.im.grpc.Friend" +
      "sTransmissionResponse\"\000\022\216\001\n)deleteFileIn" +
      "formationWithFriendByFriendId\022..com.lanj" +
      "iu.im.grpc.FriendsTransmissionRequest\032/." +
      "com.lanjiu.im.grpc.FriendsTransmissionRe" +
      "sponse\"\000\022\177\n\036deleteFileInformationWithGro" +
      "up\022,.com.lanjiu.im.grpc.GroupTransmissio" +
      "nRequest\032-.com.lanjiu.im.grpc.GroupTrans" +
      "missionResponse\"\000B*\n\022com.lanjiu.im.grpcB" +
      "\020FileStorageProtoH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_lanjiu_im_grpc_FriendsTransmissionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_lanjiu_im_grpc_FriendsTransmissionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_FriendsTransmissionRequest_descriptor,
        new java.lang.String[] { "FriendsPictureVideoMessage", "Checksum", });
    internal_static_com_lanjiu_im_grpc_FriendsTransmissionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_lanjiu_im_grpc_FriendsTransmissionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_FriendsTransmissionResponse_descriptor,
        new java.lang.String[] { "FriendsPictureVideoMessage", "Checksum", });
    internal_static_com_lanjiu_im_grpc_GroupTransmissionRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_lanjiu_im_grpc_GroupTransmissionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_GroupTransmissionRequest_descriptor,
        new java.lang.String[] { "GroupPictureVideoMessage", "Checksum", });
    internal_static_com_lanjiu_im_grpc_GroupTransmissionResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_lanjiu_im_grpc_GroupTransmissionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_GroupTransmissionResponse_descriptor,
        new java.lang.String[] { "GroupPictureVideoMessage", "Checksum", });
    internal_static_com_lanjiu_im_grpc_OriginalPictureVideoFriendsTransmission_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_lanjiu_im_grpc_OriginalPictureVideoFriendsTransmission_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_OriginalPictureVideoFriendsTransmission_descriptor,
        new java.lang.String[] { "UserType", "SettingsType", "Picture", "Video", "FileContent", "Friends", "Tourists", "RegisteredUser", "StatusDetail", "Head", });
    internal_static_com_lanjiu_im_grpc_OriginalPictureVideoGroupTransmission_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_lanjiu_im_grpc_OriginalPictureVideoGroupTransmission_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_OriginalPictureVideoGroupTransmission_descriptor,
        new java.lang.String[] { "UserType", "SettingsType", "Picture", "Video", "FileContent", "GroupMember", "Group", "Tourists", "RegisteredUser", "StatusDetail", "Head", });
    internal_static_com_lanjiu_im_grpc_FileContent_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_lanjiu_im_grpc_FileContent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_FileContent_descriptor,
        new java.lang.String[] { "BigFileHead", "BigFileFragment", "BigFileFoot", "PackageKind", });
    internal_static_com_lanjiu_im_grpc_BigFileHead_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_lanjiu_im_grpc_BigFileHead_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_BigFileHead_descriptor,
        new java.lang.String[] { "Count", "Length", "ServerUrl", "ClientUrl", });
    internal_static_com_lanjiu_im_grpc_BigFileFragment_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_lanjiu_im_grpc_BigFileFragment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_BigFileFragment_descriptor,
        new java.lang.String[] { "Length", "Data", "Position", });
    internal_static_com_lanjiu_im_grpc_BigFileFoot_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_lanjiu_im_grpc_BigFileFoot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_BigFileFoot_descriptor,
        new java.lang.String[] { "IsSuccess", });
    internal_static_com_lanjiu_im_grpc_RegisteredUser_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_lanjiu_im_grpc_RegisteredUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_RegisteredUser_descriptor,
        new java.lang.String[] { "UserId", "Secret", "Nickname", "UserPhone", "IpAddress", });
    internal_static_com_lanjiu_im_grpc_Tourists_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_lanjiu_im_grpc_Tourists_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_Tourists_descriptor,
        new java.lang.String[] { "TemporaryId", "IpAddress", "MacAddress", "Ime", });
    internal_static_com_lanjiu_im_grpc_Friends_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_com_lanjiu_im_grpc_Friends_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_Friends_descriptor,
        new java.lang.String[] { "FriendsId", "FriendsNickname", "FriendsUserType", "FriendsOfflineMessage", "FriendsBurnAfterReading", "FriendsOnlineStatus", "Tourists", "RegisteredUser", });
    internal_static_com_lanjiu_im_grpc_GroupMember_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_com_lanjiu_im_grpc_GroupMember_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_GroupMember_descriptor,
        new java.lang.String[] { "GroupMemberId", "GroupMemberNickname", "GroupMemberType", "Tourists", "RegisteredUser", "Group", });
    internal_static_com_lanjiu_im_grpc_Group_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_com_lanjiu_im_grpc_Group_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_Group_descriptor,
        new java.lang.String[] { "GroupId", "GroupNickname", "GroupType", "GroupQuantity", });
    internal_static_com_lanjiu_im_grpc_Picture_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_com_lanjiu_im_grpc_Picture_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_Picture_descriptor,
        new java.lang.String[] { "Url", "OriginPicture", "Thumbnail", "Pos", "Length", "Friends", "GroupMember", });
    internal_static_com_lanjiu_im_grpc_Video_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_com_lanjiu_im_grpc_Video_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_Video_descriptor,
        new java.lang.String[] { "Url", "OriginVideo", "Pos", "Length", "Thumbnail", "Friends", "GroupMember", });
    internal_static_com_lanjiu_im_grpc_Voice_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_com_lanjiu_im_grpc_Voice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_Voice_descriptor,
        new java.lang.String[] { "AllLength", "Content", "Pos", "Length", "Friends", "GroupMember", });
    internal_static_com_lanjiu_im_grpc_Expression_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_com_lanjiu_im_grpc_Expression_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_Expression_descriptor,
        new java.lang.String[] { "ExpressionId", "Friends", "GroupMember", });
    internal_static_com_lanjiu_im_grpc_Head_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_com_lanjiu_im_grpc_Head_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanjiu_im_grpc_Head_descriptor,
        new java.lang.String[] { "MsgId", "MsgType", "MsgContentType", "FromId", "ToId", "Timestamp", "Token", "StatusReport", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
