// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: information_other_storage_grpc.proto

package com.lanjiu.im.grpc;

public interface RpcRegisteredGroupGuestUserMemberRelationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.lanjiu.im.grpc.RpcRegisteredGroupGuestUserMemberRelation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 registered_group_id = 1;</code>
   * @return The registeredGroupId.
   */
  int getRegisteredGroupId();

  /**
   * <code>int32 guest_user_member_id = 2;</code>
   * @return The guestUserMemberId.
   */
  int getGuestUserMemberId();
}
