// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_group_storage_grpc.proto

package com.lanjiu.pro.groupStorage;

public interface ResponseCountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.lanjiu.pro.groupStorage.ResponseCount)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 count = 1;</code>
   * @return The count.
   */
  int getCount();
}
