// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_group_storage_grpc.proto

package com.lanjiu.pro.groupStorage;

public interface TextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.lanjiu.pro.groupStorage.Text)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 文本内容
   * </pre>
   *
   * <code>string content = 1;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <pre>
   * 文本内容
   * </pre>
   *
   * <code>string content = 1;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <pre>
   * 文本长度
   * </pre>
   *
   * <code>string length = 2;</code>
   * @return The length.
   */
  java.lang.String getLength();
  /**
   * <pre>
   * 文本长度
   * </pre>
   *
   * <code>string length = 2;</code>
   * @return The bytes for length.
   */
  com.google.protobuf.ByteString
      getLengthBytes();
}
