package com.lanjiu.im.storage.util;

public class ConstantsContent {
    //登录请求-注册用户-注册用户
    public final static String LOGIN_REGISTERED_REGISTERED_REQUEST_MSG_ID = "100100100100";
    public final static String LOGIN_REGISTERED_REGISTERED_RESPONSE_MSG_ID = "100100100101";

    //登录请求-登录-注册用户
    public final static String LOGIN_LOGIN_REGISTERED_REQUEST_MSG_ID = "100101100100";
    public final static String LOGIN_LOGIN_REGISTERED_RESPONSE_MSG_ID = "100101100101";

    //登录请求-登录-游客
    public final static String LOGIN_LOGIN_TOURISTS_REQUEST_MSG_ID = "100101101100";
    public final static String LOGIN_LOGIN_TOURISTS_RESPONSE_MSG_ID = "100101101101";

    //查找请求-查找用户-注册用户
    public final static String LOOKUP_USER_REGISTERED_REQUEST_MSG_ID = "101100100100";
    public final static String LOOKUP_USER_REGISTERED_RESPONSE_MSG_ID = "101100100101";

    //查找请求-查找用户-游客
    public final static String LOOKUP_USER_TOURISTS_REQUEST_MSG_ID = "101100101100";
    public final static String LOOKUP_USER_TOURISTS_RESPONSE_MSG_ID = "101100101101";

    //查找请求-查找群-注册用户
    public final static String LOOKUP_GROUP_REGISTERED_REQUEST_MSG_ID = "101101100100";
    public final static String LOOKUP_GROUP_REGISTERED_RESPONSE_MSG_ID = "101101100101";

    //查找请求-查找群-游客
    public final static String LOOKUP_GROUP_TOURISTS_REQUEST_MSG_ID = "101101101100";
    public final static String LOOKUP_GROUP_TOURISTS_RESPONSE_MSG_ID = "101101101101";

    //好友列表维护-好友添加-注册用户
    public final static String FRIENDS_LIST_MAINTENANCE_ADD_REGISTERED_REQUEST_MSG_ID = "102100100100";
    public final static String FRIENDS_LIST_MAINTENANCE_ADD_REGISTERED_RESPONSE_MSG_ID = "102100100101";

    //好友列表维护-好友添加-游客
    public final static String FRIENDS_LIST_MAINTENANCE_ADD_TOURISTS_REQUEST_MSG_ID = "102100101100";
    public final static String FRIENDS_LIST_MAINTENANCE_ADD_TOURISTS_RESPONSE_MSG_ID = "102100101101";

    //好友列表维护-好友申请-注册用户-接收好友申请/返回好友申请请求
    public final static String FRIENDS_LIST_MAINTENANCE_APPLICATION_REGISTERED_REQUEST_MSG_ID = "102101100001";
    public final static String FRIENDS_LIST_MAINTENANCE_APPLICATION_REGISTERED_RESPONSE_MSG_ID = "102101100100";

    //好友列表维护-好友申请-游客-接收好友申请/返回好友申请请求
    public final static String FRIENDS_LIST_MAINTENANCE_APPLICATION_TOURISTS_REQUEST_MSG_ID = "102101101001";
    public final static String FRIENDS_LIST_MAINTENANCE_APPLICATION_TOURISTS_RESPONSE_MSG_ID = "102101101100";

    //好友列表维护-删除好友-注册用户-请求/返回
    public final static String FRIENDS_LIST_MAINTENANCE_DELETE_REGISTERED_REQUEST_MSG_ID = "102102100100";
    public final static String FRIENDS_LIST_MAINTENANCE_DELETE_REGISTERED_RESPONSE_MSG_ID = "102102100101";

    //好友列表维护-删除好友-游客-请求/返回
    public final static String FRIENDS_LIST_MAINTENANCE_DELETE_TOURISTS_REQUEST_MSG_ID = "102102101100";
    public final static String FRIENDS_LIST_MAINTENANCE_DELETE_TOURISTS_RESPONSE_MSG_ID = "102102101101";

    //好友列表维护-资料更新-注册用户-请求/返回
    public final static String FRIENDS_LIST_MAINTENANCE_UPDATE_REGISTERED_REQUEST_MSG_ID = "12131010";
    public final static String FRIENDS_LIST_MAINTENANCE_UPDATE_REGISTERED_RESPONSE_MSG_ID = "12131011";

    //好友列表维护-资料更新-游客-请求/返回
    public final static String FRIENDS_LIST_MAINTENANCE_UPDATE_TOURISTS_REQUEST_MSG_ID = "102103101100";
    public final static String FRIENDS_LIST_MAINTENANCE_UPDATE_TOURISTS_RESPONSE_MSG_ID = "102103101101";

    //群成员管理-群成员添加-注册用户-请求/返回
    public final static String GROUP_MEMBER_MANAGEMENT_MEMBER_ADD_REGISTERED_REQUEST_MSG_ID = "103100100100";
    public final static String GROUP_MEMBER_MANAGEMENT_MEMBER_ADD_REGISTERED_RESPONSE_MSG_ID = "103100100101";

    //群成员管理-群成员添加-游客-请求/返回
    public final static String GROUP_MEMBER_MANAGEMENT_MEMBER_ADD_TOURISTS_REQUEST_MSG_ID = "103100101100";
    public final static String GROUP_MEMBER_MANAGEMENT_MEMBER_ADD_TOURISTS_RESPONSE_MSG_ID = "103100101101";

    //群成员管理-成员确认添加-注册用户-请求/返回
    public final static String GROUP_MEMBER_MANAGEMENT_MEMBER_ADD_SUCCESS_REGISTERED_REQUEST_MSG_ID = "103101100001";
    public final static String GROUP_MEMBER_MANAGEMENT_MEMBER_ADD_SUCCESS_REGISTERED_RESPONSE_MSG_ID = "103101100100";

    //群成员管理-成员确认添加-游客-请求/返回
    public final static String GROUP_MEMBER_MANAGEMENT_MEMBER_ADD_SUCCESS_TOURISTS_REQUEST_MSG_ID = "103101101001";
    public final static String GROUP_MEMBER_MANAGEMENT_MEMBER_ADD_SUCCESS_TOURISTS_RESPONSE_MSG_ID = "103101101100";

    //群成员管理-删除群成员-注册用户-请求/返回
    public final static String GROUP_MEMBER_MANAGEMENT_MEMBER_DELETE_REGISTERED_REQUEST_MSG_ID = "103102100100";
    public final static String GROUP_MEMBER_MANAGEMENT_MEMBER_DELETE_REGISTERED_RESPONSE_MSG_ID = "103102100101";

    //群成员管理-删除群成员-游客-请求/返回
    public final static String GROUP_MEMBER_MANAGEMENT_MEMBER_DELETE_TOURISTS_REQUEST_MSG_ID = "103102101100";
    public final static String GROUP_MEMBER_MANAGEMENT_MEMBER_DELETE_TOURISTS_RESPONSE_MSG_ID = "103102101101";

    //群成员管理-申请加入群-注册用户-请求/返回
    public final static String GROUP_MEMBER_MANAGEMENT_MEMBER_ADD_APPLICATION_REGISTERED_REQUEST_MSG_ID = "103103100100";
    public final static String GROUP_MEMBER_MANAGEMENT_MEMBER_ADD_APPLICATION_REGISTERED_RESPONSE_MSG_ID = "103103100101";

    //群成员管理-申请加入群-游客-请求/返回
    public final static String GROUP_MEMBER_MANAGEMENT_MEMBER_ADD_APPLICATION_TOURISTS_REQUEST_MSG_ID = "103103101100";
    public final static String GROUP_MEMBER_MANAGEMENT_MEMBER_ADD_APPLICATION_TOURISTS_RESPONSE_MSG_ID = "103103101101";

    //群成员管理-管理员确认申请-注册用户-请求/返回
    public final static String GROUP_MEMBER_MANAGEMENT_ADMINISTRATOR_APPLICATION_CONFIRM_REGISTERED_REQUEST_MSG_ID = "103104100001";
    public final static String GROUP_MEMBER_MANAGEMENT_ADMINISTRATOR_APPLICATION_CONFIRM_REGISTERED_RESPONSE_MSG_ID = "103104100100";

    //群成员管理-管理员确认申请-游客-请求/返回
    public final static String GROUP_MEMBER_MANAGEMENT_ADMINISTRATOR_APPLICATION_CONFIRM_TOURISTS_REQUEST_MSG_ID = "103104101001";
    public final static String GROUP_MEMBER_MANAGEMENT_ADMINISTRATOR_APPLICATION_CONFIRM_TOURISTS_RESPONSE_MSG_ID = "103104101100";

    //群成员管理-群资料更新-注册用户-请求/返回
    public final static String GROUP_MEMBER_MANAGEMENT_GROUP_DATA_UPDATE_REGISTERED_REQUEST_MSG_ID = "103105100100";
    public final static String GROUP_MEMBER_MANAGEMENT_GROUP_DATA_UPDATE_REGISTERED_RESPONSE_MSG_ID = "103105100101";

    //群成员管理-群资料更新-游客-请求/返回
    public final static String GROUP_MEMBER_MANAGEMENT_GROUP_DATA_UPDATE_TOURISTS_REQUEST_MSG_ID = "103105101100";
    public final static String GROUP_MEMBER_MANAGEMENT_GROUP_DATA_UPDATE_TOURISTS_RESPONSE_MSG_ID = "103105101101";

    //个人设置管理-用户在线状态更新-注册用户-在线/离线
    public final static String PERSONAL_SETTINGS_MANAGEMENT_USER_ONLINE_STATUS_UPDATE_REGISTERED_ONLINE_MSG_ID = "104100100100";
    public final static String PERSONAL_SETTINGS_MANAGEMENT_USER_ONLINE_STATUS_UPDATE_REGISTERED_OFFLINE_MSG_ID = "104100100101";

    //个人设置管理-用户在线状态更新-游客-在线/离线
    public final static String PERSONAL_SETTINGS_MANAGEMENT_USER_ONLINE_STATUS_UPDATE_TOURISTS_ONLINE_MSG_ID = "104100101100";
    public final static String PERSONAL_SETTINGS_MANAGEMENT_USER_ONLINE_STATUS_UPDATE_TOURISTS_OFFLINE_MSG_ID = "104100101101";

    //个人设置管理-个人设置（离线消息）-注册用户-请求/返回
    public final static String PERSONAL_SETTINGS_MANAGEMENT_OFFLINE_MESSAGE_REGISTERED_REQUEST_MSG_ID = "104101100100";
    public final static String PERSONAL_SETTINGS_MANAGEMENT_OFFLINE_MESSAGE_REGISTERED_RESPONSE_MSG_ID = "104101100101";

    //个人设置管理-个人设置（离线消息）-游客-请求/返回
    public final static String PERSONAL_SETTINGS_MANAGEMENT_OFFLINE_MESSAGE_TOURISTS_REQUEST_MSG_ID = "104101101100";
    public final static String PERSONAL_SETTINGS_MANAGEMENT_OFFLINE_MESSAGE_TOURISTS_RESPONSE_MSG_ID = "104101101101";

    //个人设置管理-个人设置（阅后即焚）-注册用户-请求/返回
    public final static String PERSONAL_SETTINGS_MANAGEMENT_BURN_AFTER_READING_REGISTERED_REQUEST_MSG_ID = "104102100100";
    public final static String PERSONAL_SETTINGS_MANAGEMENT_BURN_AFTER_READING_REGISTERED_RESPONSE_MSG_ID = "104102100101";

    //个人设置管理-个人设置（阅后即焚）-游客-请求/返回
    public final static String PERSONAL_SETTINGS_MANAGEMENT_BURN_AFTER_READING_TOURISTS_REQUEST_MSG_ID = "104102101100";
    public final static String PERSONAL_SETTINGS_MANAGEMENT_BURN_AFTER_READING_TOURISTS_RESPONSE_MSG_ID = "104102101101";

    //好友离线消息管理-好友离线消息设置-注册用户-请求/返回
    public final static String FRIENDS_OFFLINE_MESSAGE_MANAGEMENT_SETTINGS_REGISTERED_REQUEST_MSG_ID = "105100100100";
    public final static String FRIENDS_OFFLINE_MESSAGE_MANAGEMENT_SETTINGS_REGISTERED_RESPONSE_MSG_ID = "105100100101";

    //好友离线消息管理-好友离线消息设置-游客-请求/返回
    public final static String FRIENDS_OFFLINE_MESSAGE_MANAGEMENT_SETTINGS_TOURISTS_REQUEST_MSG_ID = "105100101100";
    public final static String FRIENDS_OFFLINE_MESSAGE_MANAGEMENT_SETTINGS_TOURISTS_RESPONSE_MSG_ID = "105100101101";

    //好友阅后即焚消息管理-好友阅后即焚设置-注册用户-请求/返回
    public final static String FRIENDS_BURN_AFTER_READING_MESSAGE_MANAGEMENT_SETTINGS_REGISTERED_REQUEST_MSG_ID = "106100100100";
    public final static String FRIENDS_BURN_AFTER_READING_MESSAGE_MANAGEMENT_SETTINGS_REGISTERED_RESPONSE_MSG_ID = "106100100101";

    //好友阅后即焚消息管理-好友阅后即焚设置-游客-请求/返回
    public final static String FRIENDS_BURN_AFTER_READING_MESSAGE_MANAGEMENT_SETTINGS_TOURISTS_REQUEST_MSG_ID = "106100101100";
    public final static String FRIENDS_BURN_AFTER_READING_MESSAGE_MANAGEMENT_SETTINGS_TOURISTS_RESPONSE_MSG_ID = "106100101101";

    //好友在线状态管理-群用户在线状态-注册用户-在线/离线
    public final static String FRIENDS_ONLINE_STATUS_MANAGEMENT_ONLINE_GROUP_USERS_REGISTERED_REQUEST_MSG_ID = "107100100100";
    public final static String FRIENDS_ONLINE_STATUS_MANAGEMENT_ONLINE_GROUP_USERS_REGISTERED_RESPONSE_MSG_ID = "107100100101";

    //好友在线状态管理-群用户在线状态-游客-在线/离线
    public final static String FRIENDS_ONLINE_STATUS_MANAGEMENT_ONLINE_GROUP_USERS_TOURISTS_REQUEST_MSG_ID = "107100101100";
    public final static String FRIENDS_ONLINE_STATUS_MANAGEMENT_ONLINE_GROUP_USERS_TOURISTS_RESPONSE_MSG_ID = "107100101101";

    //群公告提交-群公告提交-注册用户-请求/返回
    public final static String GROUP_BULLETIN_COMMIT_REGISTERED_REQUEST_MSG_ID = "108100100100";
    public final static String GROUP_BULLETIN_COMMIT_REGISTERED_RESPONSE_MSG_ID = "108100100101";

    //群公告提交-群公告提交-游客-请求/返回
    public final static String GROUP_BULLETIN_COMMIT_TOURISTS_REQUEST_MSG_ID = "108100101100";
    public final static String GROUP_BULLETIN_COMMIT_TOURISTS_RESPONSE_MSG_ID = "108100101101";

    //群公告消息管理-群公告更新-注册用户-群公告编辑请求/群公告返回
    public final static String GROUP_ANNOUNCEMENT_MESSAGE_MANAGEMENT_GROUP_BULLETIN_EDITOR_REGISTERED_REQUEST_MSG_ID = "109100100100";
    public final static String GROUP_ANNOUNCEMENT_MESSAGE_MANAGEMENT_GROUP_BULLETIN_EDITOR_REGISTERED_RESPONSE_MSG_ID = "109100100101";

    //群公告消息管理-群公告更新-游客-群公告编辑请求/群公告返回
    public final static String GROUP_ANNOUNCEMENT_MESSAGE_MANAGEMENT_GROUP_BULLETIN_EDITOR_TOURISTS_REQUEST_MSG_ID = "109100101100";
    public final static String GROUP_ANNOUNCEMENT_MESSAGE_MANAGEMENT_GROUP_BULLETIN_EDITOR_TOURISTS_RESPONSE_MSG_ID = "109100101101";

    //群阅后即焚管理-群阅后即焚设置-注册用户-阅后即焚（On或Off）请求请求/阅后即焚（On或Off）
    public final static String GROUP_BURN_AFTER_READING_MANAGEMENT_SETTINGS_REGISTERED_REQUEST_MSG_ID = "200100100100";
    public final static String GROUP_BURN_AFTER_READING_MANAGEMENT_SETTINGS_REGISTERED_RESPONSE_MSG_ID = "200100100101";

    //群阅后即焚管理-群阅后即焚设置-游客-阅后即焚（On或Off）请求请求/阅后即焚（On或Off）
    public final static String GROUP_BURN_AFTER_READING_MANAGEMENT_SETTINGS_TOURISTS_REQUEST_MSG_ID = "200100101100";
    public final static String GROUP_BURN_AFTER_READING_MANAGEMENT_SETTINGS_TOURISTS_RESPONSE_MSG_ID = "200100101101";

    //1V1聊天消息发送-文字聊天发送-注册用户-发送文字请求/发送文字返回
    public final static String OVO_CHAT_MESSAGE_SENDING_TEXT_CHAT_SENDING_REGISTERED_REQUEST_MSG_ID = "201100100100";
    public final static String OVO_CHAT_MESSAGE_SENDING_TEXT_CHAT_SENDING_REGISTERED_RESPONSE_MSG_ID = "201100100101";
    //1V1聊天消息发送-文字聊天发送-游客-发送文字请求/发送文字返回
    public final static String OVO_CHAT_MESSAGE_SENDING_TEXT_CHAT_SENDING_TOURISTS_REQUEST_MSG_ID = "201100101100";
    public final static String OVO_CHAT_MESSAGE_SENDING_TEXT_CHAT_SENDING_TOURISTS_RESPONSE_MSG_ID = "201100101101";
    //1V1聊天消息发送-表情发送-注册用户-发送表情请求/发送表情返回
    public final static String OVO_CHAT_MESSAGE_SENDING_EXPRESSION_SENDING_REGISTERED_REQUEST_MSG_ID = "201101100100";
    public final static String OVO_CHAT_MESSAGE_SENDING_EXPRESSION_SENDING_REGISTERED_RESPONSE_MSG_ID = "201101100101";
    //1V1聊天消息发送-表情发送-游客-发送表情请求/发送表情返回
    public final static String OVO_CHAT_MESSAGE_SENDING_EXPRESSION_SENDING_TOURISTS_REQUEST_MSG_ID = "201101101100";
    public final static String OVO_CHAT_MESSAGE_SENDING_EXPRESSION_SENDING_TOURISTS_RESPONSE_MSG_ID = "201101101101";
    //1V1聊天消息发送-图片发送-注册用户-发送图片请求/发送图片返回
    public final static String OVO_CHAT_MESSAGE_SENDING_PICTURE_SENDING_REGISTERED_REQUEST_MSG_ID = "201102100100";
    public final static String OVO_CHAT_MESSAGE_SENDING_PICTURE_SENDING_REGISTERED_RESPONSE_MSG_ID = "201102100101";
    //1V1聊天消息发送-图片发送-游客-发送图片请求/发送图片返回
    public final static String OVO_CHAT_MESSAGE_SENDING_PICTURE_SENDING_TOURISTS_REQUEST_MSG_ID = "201102101100";
    public final static String OVO_CHAT_MESSAGE_SENDING_PICTURE_SENDING_TOURISTS_RESPONSE_MSG_ID = "201102101101";
    //1V1聊天消息发送-视频发送-注册用户-发送视频请求/发送视频返回
    public final static String OVO_CHAT_MESSAGE_SENDING_VIDEO_SENDING_REGISTERED_REQUEST_MSG_ID = "201103100100";
    public final static String OVO_CHAT_MESSAGE_SENDING_VIDEO_SENDING_REGISTERED_RESPONSE_MSG_ID = "201103100101";
    //1V1聊天消息发送-视频发送-游客-发送视频请求/发送视频返回
    public final static String OVO_CHAT_MESSAGE_SENDING_VIDEO_SENDING_TOURISTS_REQUEST_MSG_ID = "201103101100";
    public final static String OVO_CHAT_MESSAGE_SENDING_VIDEO_SENDING_TOURISTS_RESPONSE_MSG_ID = "201103101101";
    //1V1聊天消息发送-语音聊天发送-注册用户-发送语音请求/发送语音返回
    public final static String OVO_CHAT_MESSAGE_SENDING_VOICE_CHAT_SENDING_REGISTERED_REQUEST_MSG_ID = "201104100100";
    public final static String OVO_CHAT_MESSAGE_SENDING_VOICE_CHAT_SENDING_REGISTERED_RESPONSE_MSG_ID = "201104100101";
    //1V1聊天消息发送-语音聊天发送-游客-发送语音请求/发送语音返回
    public final static String OVO_CHAT_MESSAGE_SENDING_VOICE_CHAT_SENDING_TOURISTS_REQUEST_MSG_ID = "201104101100";
    public final static String OVO_CHAT_MESSAGE_SENDING_VOICE_CHAT_SENDING_TOURISTS_RESPONSE_MSG_ID = "201104101101";

    //1V1聊天消息接收-文字聊天接收-注册用户-接收文字请求/接收文字返回
    public final static String OVO_CHAT_MESSAGE_RECEPTION_TEXT_CHAT_RECEPTION_REGISTERED_REQUEST_MSG_ID = "202100100001";
    public final static String OVO_CHAT_MESSAGE_RECEPTION_TEXT_CHAT_RECEPTION_REGISTERED_RESPONSE_MSG_ID = "202100100100";
    //1V1聊天消息接收-文字聊天接收-游客-接收文字请求/接收文字返回 TEXT_OR_VOICE_CHAT_SENDING
    public final static String OVO_CHAT_MESSAGE_RECEPTION_TEXT_CHAT_RECEPTION_TOURISTS_REQUEST_MSG_ID = "202100101001";
    public final static String OVO_CHAT_MESSAGE_RECEPTION_TEXT_CHAT_RECEPTION_TOURISTS_RESPONSE_MSG_ID = "202100101100";
    //1V1聊天消息接收-表情接收-注册用户-接收表情请求/接收表情返回
    public final static String OVO_CHAT_MESSAGE_RECEPTION_EXPRESSION_RECEPTION_REGISTERED_REQUEST_MSG_ID = "202101100001";
    public final static String OVO_CHAT_MESSAGE_RECEPTION_EXPRESSION_RECEPTION_REGISTERED_RESPONSE_MSG_ID = "202101100100";
    //1V1聊天消息接收-表情接收-游客-接收表情请求/接收表情返回
    public final static String OVO_CHAT_MESSAGE_RECEPTION_EXPRESSION_RECEPTION_TOURISTS_REQUEST_MSG_ID = "202101101001";
    public final static String OVO_CHAT_MESSAGE_RECEPTION_EXPRESSION_RECEPTION_TOURISTS_RESPONSE_MSG_ID = "202101101100";
    //1V1聊天消息接收-图片接收-注册用户-接收图片请求/接收图片返回
    public final static String OVO_CHAT_MESSAGE_RECEPTION_PICTURE_RECEPTION_REGISTERED_REQUEST_MSG_ID = "202102100001";
    public final static String OVO_CHAT_MESSAGE_RECEPTION_PICTURE_RECEPTION_REGISTERED_RESPONSE_MSG_ID = "202102100100";
    //1V1聊天消息接收-图片接收-游客-接收图片请求/接收图片返回
    public final static String OVO_CHAT_MESSAGE_RECEPTION_PICTURE_RECEPTION_TOURISTS_REQUEST_MSG_ID = "202102101001";
    public final static String OVO_CHAT_MESSAGE_RECEPTION_PICTURE_RECEPTION_TOURISTS_RESPONSE_MSG_ID = "202102101100";
    //1V1聊天消息接收-视频接收-注册用户-接收视频请求/接收视频返回
    public final static String OVO_CHAT_MESSAGE_RECEPTION_VIDEO_RECEPTION_REGISTERED_REQUEST_MSG_ID = "202103100001";
    public final static String OVO_CHAT_MESSAGE_RECEPTION_VIDEO_RECEPTION_REGISTERED_RESPONSE_MSG_ID = "202103100100";
    //1V1聊天消息接收-视频接收-游客-接收视频请求/接收视频返回
    public final static String OVO_CHAT_MESSAGE_RECEPTION_VIDEO_RECEPTION_TOURISTS_REQUEST_MSG_ID = "202103101001";
    public final static String OVO_CHAT_MESSAGE_RECEPTION_VIDEO_RECEPTION_TOURISTS_RESPONSE_MSG_ID = "202103101100";
    //1V1聊天消息接收-语音聊天接收-注册用户-接收语音请求/接收语音返回
    public final static String OVO_CHAT_MESSAGE_RECEPTION_VOICE_CHAT_RECEPTION_REGISTERED_REQUEST_MSG_ID = "202104100001";
    public final static String OVO_CHAT_MESSAGE_RECEPTION_VOICE_CHAT_RECEPTION_REGISTERED_RESPONSE_MSG_ID = "202104100100";
    //1V1聊天消息接收-语音聊天接收-游客-接收语音请求/接收语音返回
    public final static String OVO_CHAT_MESSAGE_RECEPTION_VOICE_CHAT_RECEPTION_TOURISTS_REQUEST_MSG_ID = "202104101001";
    public final static String OVO_CHAT_MESSAGE_RECEPTION_VOICE_CHAT_RECEPTION_TOURISTS_RESPONSE_MSG_ID = "202104101100";

    //群消息发送-文字聊天发送-注册用户-发送文字请求/发送文字返回   Group messaging Group message reception
    public final static String GROUP_MESSAGING_TEXT_CHAT_SENDING_REGISTERED_REQUEST_MSG_ID = "203100100100";
    public final static String GROUP_MESSAGING_TEXT_CHAT_SENDING_REGISTERED_RESPONSE_MSG_ID = "203100100101";
    //群消息发送-文字聊天发送-游客-发送文字请求/发送文字返回 RECEPTION GROUP_MESSAGING
    public final static String GROUP_MESSAGING_TEXT_CHAT_SENDING_TOURISTS_REQUEST_MSG_ID = "203100101100";
    public final static String GROUP_MESSAGING_TEXT_CHAT_SENDING_TOURISTS_RESPONSE_MSG_ID = "203100101101";
    //群消息发送-表情发送-注册用户-发送表情请求/发送表情返回 GROUP_MESSAGE_RECEPTION
    public final static String GROUP_MESSAGING_EXPRESSION_SENDING_REGISTERED_REQUEST_MSG_ID = "203101100100";
    public final static String GROUP_MESSAGING_EXPRESSION_SENDING_REGISTERED_RESPONSE_MSG_ID = "203101100101";
    //群消息发送-表情发送-游客-发送表情请求/发送表情返回
    public final static String GROUP_MESSAGING_EXPRESSION_SENDING_TOURISTS_REQUEST_MSG_ID = "203101101100";
    public final static String GROUP_MESSAGING_EXPRESSION_SENDING_TOURISTS_RESPONSE_MSG_ID = "203101101101";
    //群消息发送-图片发送-注册用户-发送图片请求/发送图片返回
    public final static String GROUP_MESSAGING_PICTURE_SENDING_REGISTERED_REQUEST_MSG_ID = "203102100100";
    public final static String GROUP_MESSAGING_PICTURE_SENDING_REGISTERED_RESPONSE_MSG_ID = "203102100101";
    //群消息发送-图片发送-游客-发送图片请求/发送图片返回
    public final static String GROUP_MESSAGING_PICTURE_SENDING_TOURISTS_REQUEST_MSG_ID = "203102101100";
    public final static String GROUP_MESSAGING_PICTURE_SENDING_TOURISTS_RESPONSE_MSG_ID = "203102101101";
    //群消息发送-视频发送-注册用户-发送视频请求/发送视频返回
    public final static String GROUP_MESSAGING_VIDEO_SENDING_REGISTERED_REQUEST_MSG_ID = "203103100100";
    public final static String GROUP_MESSAGING_VIDEO_SENDING_REGISTERED_RESPONSE_MSG_ID = "203103100101";
    //群消息发送-视频发送-游客-发送视频请求/发送视频返回
    public final static String GROUP_MESSAGING_VIDEO_SENDING_TOURISTS_REQUEST_MSG_ID = "203103101100";
    public final static String GROUP_MESSAGING_VIDEO_SENDING_TOURISTS_RESPONSE_MSG_ID = "203103101101";
    //群消息发送-语音聊天发送-注册用户-发送语音请求/发送语音返回
    public final static String GROUP_MESSAGING_VOICE_CHAT_SENDING_REGISTERED_REQUEST_MSG_ID = "203104100100";
    public final static String GROUP_MESSAGING_VOICE_CHAT_SENDING_REGISTERED_RESPONSE_MSG_ID = "203104100101";
    //群消息发送-语音聊天发送-游客-发送语音请求/发送语音返回
    public final static String GROUP_MESSAGING_VOICE_CHAT_SENDING_TOURISTS_REQUEST_MSG_ID = "203104101100";
    public final static String GROUP_MESSAGING_VOICE_CHAT_SENDING_TOURISTS_RESPONSE_MSG_ID = "203104101101";

    //群消息接收-文字聊天接收-注册用户-接收文字请求/接收文字返回
    public final static String GROUP_MESSAGE_RECEPTION_TEXT_CHAT_RECEPTION_REGISTERED_REQUEST_MSG_ID = "204100100001";
    public final static String GROUP_MESSAGE_RECEPTION_TEXT_CHAT_RECEPTION_REGISTERED_RESPONSE_MSG_ID = "204100100100";
    //群消息接收-文字聊天接收-游客-接收文字请求/接收文字返回 TEXT_OR_VOICE_CHAT_SENDING
    public final static String GROUP_MESSAGE_RECEPTION_TEXT_CHAT_RECEPTION_TOURISTS_REQUEST_MSG_ID = "204100101001";
    public final static String GROUP_MESSAGE_RECEPTION_TEXT_CHAT_RECEPTION_TOURISTS_RESPONSE_MSG_ID = "204100101100";
    //群消息接收-表情接收-注册用户-接收表情请求/接收表情返回
    public final static String GROUP_MESSAGE_RECEPTION_EXPRESSION_RECEPTION_REGISTERED_REQUEST_MSG_ID = "204101100001";
    public final static String GROUP_MESSAGE_RECEPTION_EXPRESSION_RECEPTION_REGISTERED_RESPONSE_MSG_ID = "204101100100";
    //群消息接收-表情接收-游客-接收表情请求/接收表情返回
    public final static String GROUP_MESSAGE_RECEPTION_EXPRESSION_RECEPTION_TOURISTS_REQUEST_MSG_ID = "204101101001";
    public final static String GROUP_MESSAGE_RECEPTION_EXPRESSION_RECEPTION_TOURISTS_RESPONSE_MSG_ID = "204101101100";
    //群消息接收-图片接收-注册用户-接收图片请求/接收图片返回
    public final static String GROUP_MESSAGE_RECEPTION_PICTURE_RECEPTION_REGISTERED_REQUEST_MSG_ID = "204102100001";
    public final static String GROUP_MESSAGE_RECEPTION_PICTURE_RECEPTION_REGISTERED_RESPONSE_MSG_ID = "204102100100";
    //群消息接收-图片接收-游客-接收图片请求/接收图片返回
    public final static String GROUP_MESSAGE_RECEPTION_PICTURE_RECEPTION_TOURISTS_REQUEST_MSG_ID = "204102101001";
    public final static String GROUP_MESSAGE_RECEPTION_PICTURE_RECEPTION_TOURISTS_RESPONSE_MSG_ID = "204102101100";
    //群消息接收-视频接收-注册用户-接收视频请求/接收视频返回
    public final static String GROUP_MESSAGE_RECEPTION_VIDEO_RECEPTION_REGISTERED_REQUEST_MSG_ID = "204103100001";
    public final static String GROUP_MESSAGE_RECEPTION_VIDEO_RECEPTION_REGISTERED_RESPONSE_MSG_ID = "204103100100";
    //群消息接收-视频接收-游客-接收视频请求/接收视频返回
    public final static String GROUP_MESSAGE_RECEPTION_VIDEO_RECEPTION_TOURISTS_REQUEST_MSG_ID = "204103101001";
    public final static String GROUP_MESSAGE_RECEPTION_VIDEO_RECEPTION_TOURISTS_RESPONSE_MSG_ID = "204103101100";
    //群消息接收-语音聊天接收-注册用户-接收语音请求/接收语音返回
    public final static String GROUP_MESSAGE_RECEPTION_VOICE_CHAT_RECEPTION_REGISTERED_REQUEST_MSG_ID = "204104100001";
    public final static String GROUP_MESSAGE_RECEPTION_VOICE_CHAT_RECEPTION_REGISTERED_RESPONSE_MSG_ID = "204104100100";
    //群消息接收-语音聊天接收-游客-接收语音请求/接收语音返回
    public final static String GROUP_MESSAGE_RECEPTION_VOICE_CHAT_RECEPTION_TOURISTS_REQUEST_MSG_ID = "204104101001";
    public final static String GROUP_MESSAGE_RECEPTION_VOICE_CHAT_RECEPTION_TOURISTS_RESPONSE_MSG_ID = "204104101100";

    //原始图片视频传输,分为群传输和好友传输
    public final static String ORIGINAL_PICTURE_VIDEO_TRANSMISSION_GUEST_GROUP_GUEST_MEMBER_GUEST_USER = "GuestGroupGuestMemberGuestUser";
    public final static String ORIGINAL_PICTURE_VIDEO_TRANSMISSION_GUEST_GROUP_GUEST_MEMBER_REGISTERED_USER = "GuestGroupGuestMemberRegisteredUser";
    public final static String ORIGINAL_PICTURE_VIDEO_TRANSMISSION_GUEST_GROUP_REGISTERED_MEMBER_GUEST_USER = "GuestGroupRegisteredMemberGuestUser";
    public final static String ORIGINAL_PICTURE_VIDEO_TRANSMISSION_GUEST_GROUP_REGISTERED_MEMBER_REGISTERED_USER = "GuestGroupRegisteredMemberRegisteredUser";
    public final static String ORIGINAL_PICTURE_VIDEO_TRANSMISSION_REGISTERED_GROUP_GUEST_MEMBER_GUEST_USER = "RegisteredGroupGuestMemberGuestUser";
    public final static String ORIGINAL_PICTURE_VIDEO_TRANSMISSION_REGISTERED_GROUP_GUEST_MEMBER_REGISTERED_USER = "RegisteredGroupGuestMemberRegisteredUser";
    public final static String ORIGINAL_PICTURE_VIDEO_TRANSMISSION_REGISTERED_GROUP_REGISTERED_MEMBER_GUEST_USER = "RegisteredGroupRegisteredMemberGuestUser";
    public final static String ORIGINAL_PICTURE_VIDEO_TRANSMISSION_REGISTERED_GROUP_REGISTERED_MEMBER_REGISTERED_USER = "RegisteredGroupRegisteredMemberRegisteredUser";
    public final static String ORIGINAL_PICTURE_VIDEO_TRANSMISSION_FRIENDS_REGISTERED_USER = "RegisteredUserFriend";
    public final static String ORIGINAL_PICTURE_VIDEO_TRANSMISSION_FRIENDS_GUEST_USER = "GuestUserFriend";
    public final static String ORIGINAL_PICTURE_VIDEO_TRANSMISSION_VIDEO = "VIDEO";
    public final static String ORIGINAL_PICTURE_VIDEO_TRANSMISSION_PICTURE = "PICTURE";

    //消息响应类型  Success/Failure/Network Timeout Transmission
    public final static String RESPONSE_SUCCESS = "success";
    public final static String RESPONSE_FAILURE = "failure";
    public final static String RESPONSE_NETWORK_TIMEOUT = "timeout";
    public final static String RESPONSE_AGREE = "agree";
    public final static String RESPONSE_REFUSE = "refuse";
    public final static String RESPONSE_SET_UNRECIEVE = "Friend or you have set not to receive offline messages";

    //当前服务模块类型 RegisteredUser,Tourists  Current service module type
    public final static String CURRENT_SERVICE_MODULE_REGISTERED_USER_TYPE = "RegisteredUser";
    public final static String CURRENT_SERVICE_MODULE_TOURISTS_TYPE = "Tourists";
    //心跳监测
    public final static String MSGTYPE_HEARTBEAT_REQUEST = "heat beat";
    //协议包校验情况
    public final static String RESPONSE_CHECK_FAILURE = "package check failure";

    //微服务形式文件传输
    public static final String FILE_HEAD = "head";
    public static final String FILE_FRAGMENT = "fragment";
    public static final String FILE_FOOT = "foot";
    public static final String CONSTANT_TOKEN = "token";
    public static final String CRC_FAILURE = "failure";
    public static final String CRC_SUCCESS = "success";
    public static final String FILE_DOWNLOAD = "download";
    public static final String FILE_DELETE_SUCCESS = "success";
    public static final String FILE_DELETE__FAILURE = "failure";
    public static final String FILE_PROTECT_SUCCESS = "success";
    public static final String FILE_PROTECT__FAILURE = "failure";
    public static final int FRAGMENT_LENGTH = 819200;//1473492251

}
